export type Permission =
  | 'VIEW_ALL_TENANTS'
  | 'PROVISION_TENANT'
  | 'MANAGE_TENANT_STORE'
  | 'VIEW_TENANT_TIMELINE'
  | 'VIEW_TENANT_ORDERS'
  | 'VIEW_OWN_ORDERS'
  | 'PLACE_ORDER'
  | 'MANAGE_SYSTEM_SETTINGS';
