/**
 * Background Systems — Complete Background Style Catalog
 *
 * Provides 20+ background configurations for consistent visual design.
 */

export interface BackgroundStyle {
  id: string;
  name: string;
  style: string;
  description: string;
  values: {
    primary: string;
    secondary?: string;
    gradient?: string;
    pattern?: string;
    patternColor?: string;
    image?: string;
    overlay?: string;
  };
  type: 'solid' | 'gradient' | 'pattern' | 'image' | 'mixed';
  bestFor: string[];
  notRecommendedFor: string[];
  industries: string[];
  mood: string[];
  compatibility: string[];
  preview: string;
}

export const backgroundStyles: BackgroundStyle[] = [
  {
    id: 'background-solid',
    name: 'Solid',
    style: 'solid',
    description: 'Single color background for clean designs',
    values: { primary: '#FFFFFF' },
    type: 'solid',
    bestFor: ['all purposes', 'clean design', 'minimal'],
    notRecommendedFor: ['dramatic', 'atmospheric', 'creative'],
    industries: ['all'],
    mood: ['modern', 'clean', 'minimal', 'professional'],
    compatibility: ['cards-minimal', 'buttons-solid', 'radius-rounded'],
    preview: 'background-color: #FFFFFF;',
  },
  {
    id: 'background-gradient',
    name: 'Gradient',
    style: 'gradient',
    description: 'Color gradient background for dynamic designs',
    values: { primary: '#667eea', secondary: '#764ba2', gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
    type: 'gradient',
    bestFor: ['hero', 'landing', 'cta', 'showcase'],
    notRecommendedFor: ['minimal', 'flat', 'editorial'],
    industries: ['technology', 'creative-agency', 'marketing'],
    mood: ['modern', 'bold', 'impactful', 'creative'],
    compatibility: ['buttons-gradient', 'cards-elevated', 'radius-hero'],
    preview: 'background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
  },
  {
    id: 'background-dark',
    name: 'Dark',
    style: 'dark',
    description: 'Dark background for modern dark mode',
    values: { primary: '#1A1A2E', secondary: '#16213E', gradient: 'linear-gradient(135deg, #1A1A2E 0%, #16213E 100%)' },
    type: 'gradient',
    bestFor: ['dark mode', 'tech', 'gaming', 'luxury'],
    notRecommendedFor: ['light', 'minimal', 'medical'],
    industries: ['technology', 'gaming', 'luxury', 'creative-agency'],
    mood: ['dark', 'modern', 'tech', 'futuristic'],
    compatibility: ['cards-dark', 'buttons-gradient', 'radius-tech'],
    preview: 'background-color: #1A1A2E;',
  },
  {
    id: 'background-light',
    name: 'Light',
    style: 'light',
    description: 'Light background for clean, readable interfaces',
    values: { primary: '#F8FAFC', secondary: '#F1F5F9', gradient: 'linear-gradient(135deg, #F8FAFC 0%, #F1F5F9 100%)' },
    type: 'gradient',
    bestFor: ['corporate', 'medical', 'education', 'finance'],
    notRecommendedFor: ['dark', 'gaming', 'creative'],
    industries: ['corporate', 'medical', 'education', 'finance'],
    mood: ['modern', 'clean', 'professional', 'light'],
    compatibility: ['cards-elevated', 'buttons-solid', 'radius-rounded'],
    preview: 'background-color: #F8FAFC;',
  },
  {
    id: 'background-pattern',
    name: 'Pattern',
    style: 'pattern',
    description: 'Patterned background for textured designs',
    values: { primary: '#FFFFFF', pattern: 'geometric', patternColor: '#E2E8F0' },
    type: 'pattern',
    bestFor: ['creative', 'artistic', 'editorial', 'lifestyle'],
    notRecommendedFor: ['minimal', 'corporate', 'medical'],
    industries: ['creative-agency', 'art', 'design', 'lifestyle'],
    mood: ['creative', 'artistic', 'expressive', 'modern'],
    compatibility: ['cards-asymmetric', 'buttons-gradient', 'radius-artistic'],
    preview: 'background-color: #FFFFFF; background-image: url(pattern);',
  },
  {
    id: 'background-image',
    name: 'Image',
    style: 'image',
    description: 'Full image background for immersive designs',
    values: { primary: '#000000', image: 'https://example.com/hero.jpg', overlay: 'rgba(0,0,0,0.5)' },
    type: 'image',
    bestFor: ['hero', 'landing', 'portfolio', 'travel'],
    notRecommendedFor: ['minimal', 'corporate', 'forms'],
    industries: ['travel', 'photography', 'creative-agency', 'real-estate'],
    mood: ['modern', 'bold', 'impactful', 'creative'],
    compatibility: ['cards-image', 'buttons-outline', 'radius-hero'],
    preview: 'background-image: url(hero.jpg);',
  },
  {
    id: 'background-minimal',
    name: 'Minimal',
    style: 'minimal',
    description: 'Ultra-clean minimal background',
    values: { primary: '#FAFAFA', secondary: '#F5F5F5' },
    type: 'solid',
    bestFor: ['minimalist', 'clean', 'modern', 'professional'],
    notRecommendedFor: ['creative', 'dramatic', 'luxury'],
    industries: ['technology', 'saas', 'finance', 'corporate'],
    mood: ['minimal', 'clean', 'modern', 'professional'],
    compatibility: ['cards-minimal', 'buttons-minimal', 'radius-minimal'],
    preview: 'background-color: #FAFAFA;',
  },
  {
    id: 'background-luxury',
    name: 'Luxury',
    style: 'luxury',
    description: 'Premium luxury background with gold accents',
    values: { primary: '#1A1A2E', secondary: '#D4A843', gradient: 'linear-gradient(135deg, #1A1A2E 0%, #D4A843 100%)' },
    type: 'gradient',
    bestFor: ['luxury', 'premium', 'fashion', 'beauty'],
    notRecommendedFor: ['minimal', 'brutalist', 'tech'],
    industries: ['fashion', 'hotel', 'beauty', 'luxury'],
    mood: ['luxury', 'elegant', 'premium', 'refined'],
    compatibility: ['buttons-luxury', 'cards-luxury', 'radius-luxury'],
    preview: 'background: linear-gradient(135deg, #1A1A2E 0%, #D4A843 100%);',
  },
  {
    id: 'background-medical',
    name: 'Medical',
    style: 'medical',
    description: 'Clean, trustworthy medical background',
    values: { primary: '#F0F8FF', secondary: '#E0F0FF', gradient: 'linear-gradient(135deg, #F0F8FF 0%, #E0F0FF 100%)' },
    type: 'gradient',
    bestFor: ['medical', 'healthcare', 'dental', 'pharmacy'],
    notRecommendedFor: ['luxury', 'dark', 'creative'],
    industries: ['medical', 'healthcare', 'dental', 'pharmacy'],
    mood: ['clean', 'trustworthy', 'professional', 'medical'],
    compatibility: ['buttons-outline', 'cards-soft', 'radius-medical'],
    preview: 'background: linear-gradient(135deg, #F0F8FF 0%, #E0F0FF 100%);',
  },
  {
    id: 'background-creative',
    name: 'Creative',
    style: 'creative',
    description: 'Vibrant creative background for artistic designs',
    values: { primary: '#FF6B35', secondary: '#FF4500', gradient: 'linear-gradient(135deg, #FF6B35 0%, #FF4500 100%)' },
    type: 'gradient',
    bestFor: ['creative', 'artistic', 'marketing', 'agency'],
    notRecommendedFor: ['minimal', 'corporate', 'medical'],
    industries: ['creative-agency', 'marketing', 'art', 'design'],
    mood: ['creative', 'bold', 'expressive', 'vibrant'],
    compatibility: ['buttons-gradient', 'cards-asymmetric', 'radius-artistic'],
    preview: 'background: linear-gradient(135deg, #FF6B35 0%, #FF4500 100%);',
  },
  {
    id: 'background-tech',
    name: 'Tech',
    style: 'tech',
    description: 'Technology-themed background with blue tones',
    values: { primary: '#0A0A0A', secondary: '#0066CC', gradient: 'linear-gradient(135deg, #0A0A0A 0%, #0066CC 100%)' },
    type: 'gradient',
    bestFor: ['technology', 'saas', 'fintech', 'startup'],
    notRecommendedFor: ['luxury', 'editorial', 'organic'],
    industries: ['technology', 'saas', 'fintech', 'startup'],
    mood: ['tech', 'modern', 'futuristic', 'clean'],
    compatibility: ['buttons-solid', 'cards-glass', 'radius-tech'],
    preview: 'background: linear-gradient(135deg, #0A0A0A 0%, #0066CC 100%);',
  },
  {
    id: 'background-restaurant',
    name: 'Restaurant',
    style: 'restaurant',
    description: 'Warm, inviting restaurant background',
    values: { primary: '#FFF7ED', secondary: '#FDBA74', gradient: 'linear-gradient(135deg, #FFF7ED 0%, #FDBA74 100%)' },
    type: 'gradient',
    bestFor: ['restaurant', 'food', 'hospitality', 'cafe'],
    notRecommendedFor: ['dark', 'minimal', 'tech'],
    industries: ['restaurant', 'food', 'hospitality', 'cafe'],
    mood: ['warm', 'inviting', 'appetizing', 'cozy'],
    compatibility: ['buttons-outline', 'cards-soft', 'radius-soft'],
    preview: 'background: linear-gradient(135deg, #FFF7ED 0%, #FDBA74 100%);',
  },
  {
    id: 'background-ocean',
    name: 'Ocean',
    style: 'ocean',
    description: 'Ocean-inspired blue background',
    values: { primary: '#006994', secondary: '#48BFE3', gradient: 'linear-gradient(135deg, #006994 0%, #48BFE3 100%)' },
    type: 'gradient',
    bestFor: ['travel', 'marine', 'ocean', 'water'],
    notRecommendedFor: ['luxury', 'brutalist', 'creative'],
    industries: ['travel', 'marine', 'ocean', 'water'],
    mood: ['ocean', 'calm', 'fresh', 'clean'],
    compatibility: ['buttons-outline', 'cards-image', 'radius-rounded'],
    preview: 'background: linear-gradient(135deg, #006994 0%, #48BFE3 100%);',
  },
  {
    id: 'background-forest',
    name: 'Forest',
    style: 'forest',
    description: 'Nature-inspired green background',
    values: { primary: '#064E3B', secondary: '#34D399', gradient: 'linear-gradient(135deg, #064E3B 0%, #34D399 100%)' },
    type: 'gradient',
    bestFor: ['nature', 'eco', 'wellness', 'organic'],
    notRecommendedFor: ['luxury', 'tech', 'dark'],
    industries: ['nature', 'eco', 'wellness', 'organic'],
    mood: ['nature', 'organic', 'calm', 'fresh'],
    compatibility: ['buttons-pill', 'cards-soft', 'radius-organic'],
    preview: 'background: linear-gradient(135deg, #064E3B 0%, #34D399 100%);',
  },
  {
    id: 'background-sunset',
    name: 'Sunset',
    style: 'sunset',
    description: 'Warm sunset-inspired background',
    values: { primary: '#FEF3C7', secondary: '#F59E0B', gradient: 'linear-gradient(135deg, #FEF3C7 0%, #F59E0B 100%)' },
    type: 'gradient',
    bestFor: ['restaurant', 'lifestyle', 'travel', 'warm'],
    notRecommendedFor: ['dark', 'tech', 'minimal'],
    industries: ['restaurant', 'lifestyle', 'travel', 'warm'],
    mood: ['warm', 'sunset', 'cozy', 'inviting'],
    compatibility: ['buttons-outline', 'cards-soft', 'radius-soft'],
    preview: 'background: linear-gradient(135deg, #FEF3C7 0%, #F59E0B 100%);',
  },
  {
    id: 'background-rose',
    name: 'Rose',
    style: 'rose',
    description: 'Elegant rose-gold background',
    values: { primary: '#1A1A2E', secondary: '#B76E79', gradient: 'linear-gradient(135deg, #1A1A2E 0%, #B76E79 100%)' },
    type: 'gradient',
    bestFor: ['beauty', 'fashion', 'luxury', 'elegant'],
    notRecommendedFor: ['tech', 'brutalist', 'minimal'],
    industries: ['beauty', 'fashion', 'luxury', 'elegant'],
    mood: ['luxury', 'elegant', 'rose', 'feminine'],
    compatibility: ['buttons-luxury', 'cards-luxury', 'radius-luxury'],
    preview: 'background: linear-gradient(135deg, #1A1A2E 0%, #B76E79 100%);',
  },
  {
    id: 'background-arctic',
    name: 'Arctic',
    style: 'arctic',
    description: 'Cool arctic-inspired background',
    values: { primary: '#F0F9FF', secondary: '#BAE6FD', gradient: 'linear-gradient(135deg, #F0F9FF 0%, #BAE6FD 100%)' },
    type: 'gradient',
    bestFor: ['medical', 'clean', 'modern', 'cool'],
    notRecommendedFor: ['warm', 'creative', 'luxury'],
    industries: ['medical', 'technology', 'clean', 'modern'],
    mood: ['arctic', 'cool', 'clean', 'modern'],
    compatibility: ['buttons-outline', 'cards-soft', 'radius-rounded'],
    preview: 'background: linear-gradient(135deg, #F0F9FF 0%, #BAE6FD 100%);',
  },
  {
    id: 'background-desert',
    name: 'Desert',
    style: 'desert',
    description: 'Warm desert-inspired background',
    values: { primary: '#FEF3C7', secondary: '#D97706', gradient: 'linear-gradient(135deg, #FEF3C7 0%, #D97706 100%)' },
    type: 'gradient',
    bestFor: ['travel', 'adventure', 'warm', 'natural'],
    notRecommendedFor: ['dark', 'tech', 'minimal'],
    industries: ['travel', 'adventure', 'warm', 'natural'],
    mood: ['warm', 'desert', 'natural', 'adventure'],
    compatibility: ['buttons-outline', 'cards-soft', 'radius-organic'],
    preview: 'background: linear-gradient(135deg, #FEF3C7 0%, #D97706 100%);',
  },
  {
    id: 'background-urban',
    name: 'Urban',
    style: 'urban',
    description: 'City-inspired urban background',
    values: { primary: '#1E293B', secondary: '#475569', gradient: 'linear-gradient(135deg, #1E293B 0%, #475569 100%)' },
    type: 'gradient',
    bestFor: ['urban', 'modern', 'corporate', 'real-estate'],
    notRecommendedFor: ['organic', 'wellness', 'luxury'],
    industries: ['real-estate', 'urban', 'corporate', 'modern'],
    mood: ['urban', 'modern', 'professional', 'clean'],
    compatibility: ['buttons-solid', 'cards-elevated', 'radius-tech'],
    preview: 'background: linear-gradient(135deg, #1E293B 0%, #475569 100%);',
  },
  {
    id: 'background-vintage',
    name: 'Vintage',
    style: 'vintage',
    description: 'Retro vintage-inspired background',
    values: { primary: '#FAF5E8', secondary: '#C4A882', gradient: 'linear-gradient(135deg, #FAF5E8 0%, #C4A882 100%)' },
    type: 'gradient',
    bestFor: ['retro', 'vintage', 'nostalgic', 'creative'],
    notRecommendedFor: ['modern', 'tech', 'minimal'],
    industries: ['retro', 'vintage', 'creative', 'lifestyle'],
    mood: ['retro', 'vintage', 'nostalgic', 'warm'],
    compatibility: ['buttons-text', 'cards-soft', 'radius-soft'],
    preview: 'background: linear-gradient(135deg, #FAF5E8 0%, #C4A882 100%);',
  },
];

export const getBackgroundStyle = (id: string): BackgroundStyle | undefined =>
  backgroundStyles.find((b) => b.id === id);

export const getBackgroundValues = (id: string) => {
  const style = getBackgroundStyle(id);
  return style?.values;
};

export default backgroundStyles;
