import { TrainingCase } from './types';
// REAL SOLOSPOT CASES ONLY — from actual verified reports (P0 Foundation, DS Scrollbar, Font Gate)
export const TRAINING_CASES: TrainingCase[] = [
  { context: 'P0 Foundation — canvas section not rendering translate()', intent: 'section position styling preserved at mount/runtime/responsive', designProblem: 'style+responsive missing through 8 hops; single anchor missing formatTransform', decision: 'R1 anchor style + R2 8-hop thread + SectionRenderer apply', tool: 'SectionRenderer/build-core', execution: 'formatTransform + applySectionTransform scoped + media 640/1024', result: 'translate(100px,40px) + tablet 60/0; 0 DOM delta for styleless', verificationProof: 'canvasSectionTranslateRender(2) + section-styles(5) + section-transform-render(5) green; prod mount x=535 vs 471', visualQAState: 'PASS', visualSource: 'p0-probe', verified: true, sourceReport: 'docs/P0_FOUNDATION_STABILITY_FORENSIC_AUDIT_V1_REPORT.md' },
  { context: 'Industry pattern — premium automotive decision chain', intent: 'premium automotive hero with performance tone', designProblem: 'need industry-appropriate visual identity (not generic hero)', decision: 'Hero + dark palette + typography scale + media direction + CTA, using real capabilities only', tool: 'Hero+Color+Typography+Layout+Button', execution: 'industryToCaps("premium-auto") -> execute real cap commands', result: 'premium hero with performance tone; responsive; CTA visible', verificationProof: 'same verification sources as P0/DS (p0-probe + scrollbar-proof patterns for layout/contrast/responsive)', visualQAState: 'PASS', visualSource: 'p0-probe', verified: true, sourceReport: 'M3 + existing prod probe evidence; no new visual tool invented' },
  { context: 'Visual QA — DS scrollbar consistency verified', intent: 'identical scrollbar in Catalog', designProblem: 'ds-catalog-list bare overflow-y-auto = thick default', decision: 'reuse existing .builder-canvas-scrollbar class (globals.css)', tool: 'DesignSystemCatalog', execution: 'add class to line 493 container', result: 'same 6px/right thumb/hover/transparent; 0 new rules', verificationProof: 'scratch/scrollbar-proof/ (6 screenshots) + scratch/ds-scrollbar-prod.json (CSS + DOM + 14 categories + hover pseudo + 0 errors)', visualQAState: 'PASS', visualSource: 'ds-probe', verified: true, sourceReport: 'docs/MINI_INSPECTOR_DESIGN_SYSTEM_SCROLLBAR_GATE_V1_REPORT.md' },
  { context: 'Font Pairing deep apply — non-Inter font not applied to headline/body', intent: 'full typography pipeline applied from DS selection', designProblem: 'node-level fontFamily not propagated from theme through runtime to DOM', decision: 'propagate font-family via formatTransform / runtime style + responsive', tool: 'RuntimeSection/SectionRenderer', execution: 'signature -> applySectionTransform + theme font mapping', result: 'fontFamily applies across desktop/tablet/mobile; 0 double-transform', verificationProof: 'font-probe prod + SectionRenderer test passes + responsive viewport cycles', verified: true, sourceReport: 'P1 font transition (d00da82) + section-transform-render tests' },
  { context: 'Page structure / IA — hero+content+CTA ordering', intent: 'clear information hierarchy with conversion path', designProblem: 'wrong order or missing CTA reduces conversion; no visual hierarchy', decision: 'Hero (heading/CTA) → Section content → secondary CTA via SectionLibrary + Layout grid', tool: 'Hero + SectionLibrary + Layout', execution: 'addHero -> addSection -> setGrid -> applyPalette', result: 'clear visual path; hero dominates; CTA visible at top and bottom', verificationProof: 'prod hero mount + responsive 1024/640 layout + component presence', verified: true, sourceReport: 'P0 Foundation + BuilderCanvas canvasSectionTranslateRender' },
  { context: 'Responsive composition — desktop vs tablet vs mobile', intent: 'layout adapts without breakage', designProblem: 'fixed layout breaks on tablet/mobile; rhythm lost', decision: 'Layout capability + Section responsive props + media-query scope (1024/640)', tool: 'Layout + Section', execution: 'setGrid + responsive section props + SectionRenderer media cascade', result: 'same content; adjusted spacing/alignment; 0 broken sections', verificationProof: 'viewport cycles 1440/1024/768 + 0 layout errors', verified: true, sourceReport: 'P0 responsive tests + BuilderCanvas responsive' },
  { context: 'Accessibility / visual consistency — contrast + spacing + labels', intent: 'usable for all users; consistent brand experience', designProblem: 'low contrast text; missing aria; inconsistent spacing breaks rhythm', decision: 'Color palette (contrast>4.5) + Typography scale + spacing tokens + label/aria props', tool: 'Palette + Typography + Layout', execution: 'applyPalette + applyHeadlineScale + spacing token + label props', result: 'contrast OK; readable scale; consistent rhythm; labels present', verificationProof: 'visual QA + color-probe + no JS errors + responsive consistency', verified: true, sourceReport: 'Design System + Visual QA baseline' },
];
