export interface WebsiteTemplate {
  id: string;
  name: string;
  tagline: string;
  description: string;
  badge?: string;
  iconName: string;
  sectionTemplateIds: string[];
  tags?: string[];
  style?: string;
  industry?: string[];
}

export const WEBSITE_TEMPLATES: WebsiteTemplate[] = [
  {
    id: 'modern-saas',
    name: 'Modern SaaS',
    tagline: 'High-converting SaaS landing page',
    description: 'Hero with gradient mesh, trusted-by logos, feature grid, product showcase, stats, testimonials, pricing, FAQ, CTA, and footer.',
    badge: 'Popular',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-gradient-mesh', 'logos-row', 'features-3-cards', 'products-featured', 'stats-4-col', 'testimonials-cards', 'pricing-3-tier', 'faq-centered', 'cta-banner', 'footer-modern'],
    tags: ['saas', 'startup', 'technology', 'landing'],
    style: 'modern',
    industry: ['saas', 'startup', 'technology'],
  },
  {
    id: 'luxury-fashion',
    name: 'Luxury Fashion',
    tagline: 'Premium fashion brand experience',
    description: 'Editorial hero, featured collection, product grid, brand story, gallery, brand values, newsletter, and footer.',
    iconName: 'Palette',
    sectionTemplateIds: ['hero-editorial', 'products-grid-3', 'gallery-masonry', 'about-story', 'testimonials-minimal', 'newsletter-centered', 'footer-full'],
    tags: ['fashion', 'luxury', 'editorial', 'ecommerce'],
    style: 'luxury',
    industry: ['fashion', 'luxury', 'ecommerce'],
  },
  {
    id: 'restaurant-fine',
    name: 'Fine Dining Restaurant',
    tagline: 'Elegant restaurant experience',
    description: 'Atmospheric hero, about the chef, menu highlights, gallery, testimonials, reservation CTA, contact, and footer.',
    iconName: 'Utensils',
    sectionTemplateIds: ['hero-fullscreen-dark', 'about-story', 'features-icon-left', 'gallery-collage', 'testimonials-featured', 'cta-card', 'contact-split', 'footer-columns'],
    tags: ['restaurant', 'dining', 'luxury', 'food'],
    style: 'luxury',
    industry: ['restaurant', 'cafe'],
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    tagline: 'Bold agency portfolio',
    description: 'Asymmetric hero, selected work, services, case study, clients, testimonials, about, contact, and footer.',
    iconName: 'Palette',
    sectionTemplateIds: ['hero-asymmetric', 'portfolio-grid', 'services-3-cards', 'testimonials-cards', 'logos-row', 'about-story', 'cta-gradient', 'footer-columns'],
    tags: ['agency', 'creative', 'portfolio', 'design'],
    style: 'creative',
    industry: ['creative', 'agency'],
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    tagline: 'Modern startup landing page',
    description: 'Video hero, feature grid, product showcase, stats, testimonials, pricing, FAQ, CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-video-ambient', 'features-bento', 'products-featured', 'stats-4-col', 'testimonials-grid-4', 'pricing-toggle', 'faq-2col', 'cta-gradient', 'footer-modern'],
    tags: ['startup', 'technology', 'saas', 'innovation'],
    style: 'modern',
    industry: ['startup', 'technology'],
  },
  {
    id: 'ecommerce-modern',
    name: 'Modern E-Commerce',
    tagline: 'Full-featured online store',
    description: 'Product hero, featured products, product grid, testimonials, newsletter, and footer.',
    badge: 'E-Commerce',
    iconName: 'ShoppingBag',
    sectionTemplateIds: ['hero-product-showcase', 'products-grid-3', 'products-carousel', 'testimonials-cards', 'newsletter-centered', 'cta-banner', 'footer-full'],
    tags: ['ecommerce', 'store', 'shopping', 'products'],
    style: 'modern',
    industry: ['ecommerce'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    tagline: 'Premium property listings',
    description: 'Property hero, featured listings, agent team, testimonials, contact, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-split-gradient', 'products-featured', 'team-grid', 'testimonials-cards', 'stats-3-center', 'contact-form', 'footer-columns'],
    tags: ['real-estate', 'property', 'luxury'],
    style: 'premium',
    industry: ['real-estate'],
  },
  {
    id: 'photography-portfolio',
    name: 'Photography Portfolio',
    tagline: 'Stunning visual portfolio',
    description: 'Fullscreen hero, photo gallery, about the photographer, testimonials, contact, and footer.',
    iconName: 'Camera',
    sectionTemplateIds: ['hero-fullscreen-dark', 'gallery-masonry', 'about-story', 'testimonials-featured', 'contact-minimal', 'footer-minimal'],
    tags: ['photography', 'portfolio', 'creative', 'visual'],
    style: 'minimal',
    industry: ['photography', 'creative'],
  },
  {
    id: 'digital-agency',
    name: 'Digital Agency',
    tagline: 'Results-driven digital agency',
    description: 'Stats hero, services, case studies, team, testimonials, CTA, and footer.',
    iconName: 'Palette',
    sectionTemplateIds: ['hero-stats', 'services-3-cards', 'portfolio-filterable', 'team-grid', 'testimonials-logo-quote', 'cta-banner', 'footer-columns'],
    tags: ['agency', 'digital', 'marketing', 'services'],
    style: 'modern',
    industry: ['agency', 'marketing'],
  },
  {
    id: 'fitness-gym',
    name: 'Fitness & Gym',
    tagline: 'High-energy fitness brand',
    description: 'Dark hero, class schedule, trainer profiles, testimonials, pricing, CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-fullscreen-dark', 'services-pricing-cards', 'team-cards', 'testimonials-grid-4', 'pricing-3-tier', 'cta-urgency', 'footer-columns'],
    tags: ['fitness', 'gym', 'health', 'wellness'],
    style: 'bold',
    industry: ['fitness', 'personal-trainer'],
  },
  {
    id: 'consulting',
    name: 'Consulting Firm',
    tagline: 'Professional consulting services',
    description: 'Split hero, services, about, team, testimonials, contact, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-split-image', 'services-list', 'about-timeline', 'team-grid', 'testimonials-cards', 'contact-form', 'footer-modern'],
    tags: ['consulting', 'business', 'professional', 'corporate'],
    style: 'corporate',
    industry: ['consulting', 'finance'],
  },
  {
    id: 'architecture',
    name: 'Architecture Studio',
    tagline: 'Architectural design portfolio',
    description: 'Minimal hero, project gallery, about the firm, team, testimonials, contact, and footer.',
    iconName: 'Palette',
    sectionTemplateIds: ['hero-minimal-white', 'portfolio-fullwidth', 'about-values', 'team-leadership', 'testimonials-minimal', 'contact-split', 'footer-minimal'],
    tags: ['architecture', 'design', 'portfolio', 'minimal'],
    style: 'minimal',
    industry: ['architecture', 'interior-design'],
  },
  {
    id: 'beauty-salon',
    name: 'Beauty & Salon',
    tagline: 'Elegant beauty brand',
    description: 'Soft hero, services, gallery, team, testimonials, booking CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-editorial', 'services-icon-top', 'gallery-grid', 'team-cards', 'testimonials-featured', 'cta-card', 'footer-newsletter'],
    tags: ['beauty', 'salon', 'wellness', 'spa'],
    style: 'elegant',
    industry: ['beauty', 'wellness'],
  },
  {
    id: 'online-course',
    name: 'Online Course',
    tagline: 'Course creator landing page',
    description: 'Course hero, curriculum, testimonials, instructor bio, pricing, FAQ, CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-centered', 'features-timeline', 'testimonials-cards', 'about-story', 'pricing-3-tier', 'faq-centered', 'cta-newsletter', 'footer-modern'],
    tags: ['education', 'course', 'creator', 'learning'],
    style: 'modern',
    industry: ['education', 'course-creator'],
  },
  {
    id: 'music-artist',
    name: 'Music & Artist',
    tagline: 'Artist or band website',
    description: 'Video hero, latest release, tour dates, gallery, testimonials, newsletter, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-video-ambient', 'products-featured', 'gallery-carousel', 'testimonials-logo-quote', 'newsletter-gradient', 'footer-dark'],
    tags: ['music', 'artist', 'entertainment', 'creative'],
    style: 'dark',
    industry: ['music', 'artist'],
  },
  {
    id: 'law-firm',
    name: 'Law Firm',
    tagline: 'Professional legal services',
    description: 'Corporate hero, practice areas, case results, team, testimonials, contact, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-split-image', 'services-list', 'stats-4-col', 'team-leadership', 'testimonials-cards', 'contact-form', 'footer-columns'],
    tags: ['law', 'legal', 'professional', 'corporate'],
    style: 'corporate',
    industry: ['law-firm'],
  },
  {
    id: 'construction',
    name: 'Construction Company',
    tagline: 'Builds trust and credibility',
    description: 'Project hero, services, project gallery, team, testimonials, contact, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-split-gradient', 'services-grid-4', 'gallery-2col', 'team-grid', 'testimonials-cards', 'contact-cards', 'footer-columns'],
    tags: ['construction', 'building', 'industrial'],
    style: 'bold',
    industry: ['construction'],
  },
  {
    id: 'automotive',
    name: 'Automotive Dealership',
    tagline: 'Premium car dealership',
    description: 'Car hero, featured vehicles, services, testimonials, contact, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-product-showcase', 'products-grid-3', 'services-list', 'testimonials-cards', 'stats-3-center', 'contact-form', 'footer-full'],
    tags: ['automotive', 'cars', 'dealership', 'luxury'],
    style: 'premium',
    industry: ['automotive'],
  },
  {
    id: 'local-business',
    name: 'Local Business',
    tagline: 'Community-focused business',
    description: 'Friendly hero, services, about, testimonials, contact with map, and footer.',
    iconName: 'Briefcase',
    sectionTemplateIds: ['hero-centered', 'services-3-cards', 'about-story', 'testimonials-cards', 'contact-map', 'footer-compact'],
    tags: ['local', 'business', 'community', 'services'],
    style: 'modern',
    industry: ['local-business'],
  },
  {
    id: 'personal-brand',
    name: 'Personal Brand',
    tagline: 'Build your personal brand',
    description: 'Bold hero, about me, services, testimonials, blog, newsletter, and footer.',
    iconName: 'Camera',
    sectionTemplateIds: ['hero-asymmetric', 'about-values', 'services-3-cards', 'testimonials-featured', 'blog-3-cards', 'newsletter-centered', 'footer-minimal'],
    tags: ['personal', 'brand', 'freelancer', 'creator'],
    style: 'creative',
    industry: ['personal-brand', 'freelancer'],
  },
  {
    id: 'startup-landing',
    name: 'Startup Landing',
    tagline: 'Launch your startup in style',
    description: 'Gradient hero, trusted by, features, product, stats, testimonials, pricing, FAQ, CTA, and footer.',
    badge: 'New',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-gradient-mesh', 'logos-row', 'features-4-grid', 'products-featured', 'stats-4-col', 'testimonials-grid-4', 'pricing-toggle', 'faq-centered', 'cta-banner', 'footer-modern'],
    tags: ['startup', 'launch', 'saas', 'technology'],
    style: 'bold',
    industry: ['startup'],
  },
  {
    id: 'wedding',
    name: 'Wedding & Events',
    tagline: 'Beautiful event website',
    description: 'Elegant hero, event details, photo gallery, RSVP, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-fullscreen-dark', 'about-story', 'gallery-masonry', 'stats-3-center', 'newsletter-centered', 'footer-minimal'],
    tags: ['wedding', 'event', 'celebration'],
    style: 'elegant',
    industry: ['events'],
  },
  {
    id: 'dark-saas',
    name: 'Dark SaaS',
    tagline: 'Sleek dark-mode SaaS page',
    description: 'Dark hero, feature grid, integrations, pricing, testimonials, FAQ, CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-fullscreen-dark', 'features-bento', 'logos-grid', 'pricing-featured', 'testimonials-sidebar', 'faq-2col', 'cta-card', 'footer-dark'],
    tags: ['saas', 'dark', 'modern', 'technology'],
    style: 'dark',
    industry: ['saas', 'technology'],
  },
  {
    id: 'minimal-portfolio',
    name: 'Minimal Portfolio',
    tagline: 'Clean portfolio showcase',
    description: 'White hero, project grid, about, testimonials, contact, and minimal footer.',
    iconName: 'Camera',
    sectionTemplateIds: ['hero-minimal-white', 'portfolio-grid', 'about-minimal', 'testimonials-minimal', 'contact-minimal', 'footer-minimal'],
    tags: ['portfolio', 'minimal', 'clean', 'design'],
    style: 'minimal',
    industry: ['portfolio', 'freelancer'],
  },
  {
    id: 'saas-enterprise',
    name: 'Enterprise SaaS',
    tagline: 'Enterprise-grade SaaS platform',
    description: 'Stats hero, enterprise features, case studies, pricing, security, testimonials, CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-stats', 'features-with-image', 'portfolio-case-study', 'pricing-enterprise', 'logos-centered', 'testimonials-logo-quote', 'cta-banner', 'footer-columns'],
    tags: ['enterprise', 'saas', 'b2b', 'technology'],
    style: 'corporate',
    industry: ['saas', 'technology'],
  },
  {
    id: 'organic-wellness',
    name: 'Organic Wellness',
    tagline: 'Natural wellness brand',
    description: 'Nature hero, product showcase, about, testimonials, newsletter, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-split-image', 'products-grid-3', 'about-values', 'testimonials-featured', 'newsletter-split', 'footer-newsletter'],
    tags: ['wellness', 'organic', 'health', 'natural'],
    style: 'organic',
    industry: ['health', 'wellness'],
  },
  {
    id: 'magazine',
    name: 'Online Magazine',
    tagline: 'Digital publication layout',
    description: 'Editorial hero, featured articles, categories, newsletter, and footer.',
    iconName: 'Palette',
    sectionTemplateIds: ['hero-editorial', 'blog-featured', 'portfolio-filterable', 'newsletter-centered', 'logos-scrolling', 'footer-columns'],
    tags: ['magazine', 'editorial', 'publishing', 'content'],
    style: 'editorial',
    industry: ['editorial'],
  },
  {
    id: 'app-showcase',
    name: 'App Showcase',
    tagline: 'Mobile app landing page',
    description: 'App hero, features, screenshots, testimonials, pricing, download CTA, and footer.',
    iconName: 'Sparkles',
    sectionTemplateIds: ['hero-product-showcase', 'features-4-grid', 'products-carousel', 'testimonials-cards', 'pricing-simple', 'cta-gradient', 'footer-modern'],
    tags: ['app', 'mobile', 'technology', 'startup'],
    style: 'modern',
    industry: ['technology', 'startup'],
  },
  {
    id: 'cafe-bakery',
    name: 'Cafe & Bakery',
    tagline: 'Warm and inviting cafe',
    description: 'Warm hero, menu highlights, gallery, about, testimonials, and footer.',
    iconName: 'Utensils',
    sectionTemplateIds: ['hero-editorial', 'services-icon-top', 'gallery-grid', 'about-story', 'testimonials-cards', 'contact-simple', 'footer-compact'],
    tags: ['cafe', 'bakery', 'food', 'restaurant'],
    style: 'organic',
    industry: ['cafe', 'restaurant'],
  },
  {
    id: 'blank',
    name: 'Blank Canvas',
    tagline: 'Start from scratch',
    description: 'Begin with an empty canvas and add sections and components according to your own idea.',
    iconName: 'FilePlus',
    sectionTemplateIds: [],
    tags: ['blank', 'empty', 'custom'],
    style: 'minimal',
    industry: [],
  },
];
