/**
 * LayoutFieldCatalog.ts — Sprint S30 Layout Inspector Field Catalog
 *
 * Defines PropertyFieldDefinition[] catalog for layout properties matching S29 LayoutStyle/LayoutConstraints
 * DTO contracts and Inspector 2.0 registry types.
 *
 * NO DOM, NO React, NO requestAnimationFrame, NO Browser API, ZERO Runtime execution.
 */

import type { PropertyFieldDefinition, ValidationResult } from '../inspector/registry/types';

function toValidationResult(valid: boolean, error: string): ValidationResult {
  return valid ? { valid: true } : { valid: false, error };
}

export const LAYOUT_FIELD_DEFINITIONS: PropertyFieldDefinition[] = [
  {
    id: 'layout.mode',
    label: 'Layout Mode',
    description: 'Auto layout flexbox behavior vs free positioning',
    widget: 'select',
    category: 'layout',
    defaultValue: 'auto',
    options: [
      { label: 'Auto (Flex)', value: 'auto' },
      { label: 'Free (Absolute)', value: 'free' },
    ],
    validation: (val) => toValidationResult(val === 'auto' || val === 'free', 'Invalid layout mode'),
  },
  {
    id: 'layout.direction',
    label: 'Direction',
    description: 'Primary layout flow direction',
    widget: 'select',
    category: 'layout',
    defaultValue: 'vertical',
    options: [
      { label: 'Vertical (Column)', value: 'vertical' },
      { label: 'Horizontal (Row)', value: 'horizontal' },
    ],
    validation: (val) => toValidationResult(val === 'vertical' || val === 'horizontal', 'Invalid layout direction'),
  },
  {
    id: 'layout.gap',
    label: 'Gap',
    description: 'Spacing between children in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    step: 1,
    unit: 'px',
    responsive: true,
    validation: (val) => toValidationResult(typeof val === 'number' && val >= 0, 'Gap must be a non-negative number'),
  },
  {
    id: 'layout.paddingTop',
    label: 'Padding Top',
    description: 'Top internal padding',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    step: 1,
    unit: 'px',
    responsive: true,
    validation: (val) => toValidationResult(typeof val === 'number' && val >= 0, 'Padding top must be a non-negative number'),
  },
  {
    id: 'layout.paddingRight',
    label: 'Padding Right',
    description: 'Right internal padding',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    step: 1,
    unit: 'px',
    responsive: true,
    validation: (val) => toValidationResult(typeof val === 'number' && val >= 0, 'Padding right must be a non-negative number'),
  },
  {
    id: 'layout.paddingBottom',
    label: 'Padding Bottom',
    description: 'Bottom internal padding',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    step: 1,
    unit: 'px',
    responsive: true,
    validation: (val) => toValidationResult(typeof val === 'number' && val >= 0, 'Padding bottom must be a non-negative number'),
  },
  {
    id: 'layout.paddingLeft',
    label: 'Padding Left',
    description: 'Left internal padding',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    step: 1,
    unit: 'px',
    responsive: true,
    validation: (val) => toValidationResult(typeof val === 'number' && val >= 0, 'Padding left must be a non-negative number'),
  },
  {
    id: 'layout.alignItems',
    label: 'Align Items',
    description: 'Cross axis alignment of children',
    widget: 'select',
    category: 'layout',
    defaultValue: 'start',
    options: [
      { label: 'Start', value: 'start' },
      { label: 'Center', value: 'center' },
      { label: 'End', value: 'end' },
      { label: 'Stretch', value: 'stretch' },
    ],
    validation: (val) => toValidationResult(['start', 'center', 'end', 'stretch'].includes(val as string), 'Invalid align items value'),
  },
  {
    id: 'layout.justifyContent',
    label: 'Justify Content',
    description: 'Main axis distribution of children',
    widget: 'select',
    category: 'layout',
    defaultValue: 'start',
    options: [
      { label: 'Start', value: 'start' },
      { label: 'Center', value: 'center' },
      { label: 'End', value: 'end' },
      { label: 'Space Between', value: 'space-between' },
      { label: 'Space Around', value: 'space-around' },
      { label: 'Space Evenly', value: 'space-evenly' },
    ],
    validation: (val) =>
      toValidationResult(
        ['start', 'center', 'end', 'space-between', 'space-around', 'space-evenly'].includes(val as string),
        'Invalid justify content value'
      ),
  },
  {
    id: 'layout.wrap',
    label: 'Wrap',
    description: 'Wrap children to multiple lines',
    widget: 'boolean',
    category: 'layout',
    defaultValue: false,
    validation: (val) => toValidationResult(typeof val === 'boolean', 'Wrap must be a boolean'),
  },
  {
    id: 'layout.left',
    label: 'Left Constraint',
    description: 'Left pin offset in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    responsive: true,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number', 'Left constraint must be a number'),
  },
  {
    id: 'layout.right',
    label: 'Right Constraint',
    description: 'Right pin offset in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number', 'Right constraint must be a number'),
  },
  {
    id: 'layout.top',
    label: 'Top Constraint',
    description: 'Top pin offset in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    responsive: true,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number', 'Top constraint must be a number'),
  },
  {
    id: 'layout.bottom',
    label: 'Bottom Constraint',
    description: 'Bottom pin offset in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number', 'Bottom constraint must be a number'),
  },
  {
    id: 'layout.centerX',
    label: 'Center Horizontally',
    description: 'Pin to horizontal center',
    widget: 'boolean',
    category: 'layout',
    defaultValue: false,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'boolean', 'Center X must be a boolean'),
  },
  {
    id: 'layout.centerY',
    label: 'Center Vertically',
    description: 'Pin to vertical center',
    widget: 'boolean',
    category: 'layout',
    defaultValue: false,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'boolean', 'Center Y must be a boolean'),
  },
  {
    id: 'layout.width',
    label: 'Width',
    description: 'Width in pixels or percentage',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    responsive: true,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number' || typeof val === 'string', 'Width must be a number or string'),
  },
  {
    id: 'layout.height',
    label: 'Height',
    description: 'Height in pixels or percentage',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    responsive: true,
    validation: (val) => toValidationResult(val === undefined || typeof val === 'number' || typeof val === 'string', 'Height must be a number or string'),
  },
  {
    id: 'layout.minWidth',
    label: 'Min Width',
    description: 'Minimum width in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    validation: (val) => toValidationResult(val === undefined || (typeof val === 'number' && val >= 0), 'Min width must be a non-negative number'),
  },
  {
    id: 'layout.maxWidth',
    label: 'Max Width',
    description: 'Maximum width in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    validation: (val) => toValidationResult(val === undefined || (typeof val === 'number' && val >= 0), 'Max width must be a non-negative number'),
  },
  {
    id: 'layout.minHeight',
    label: 'Min Height',
    description: 'Minimum height in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    validation: (val) => toValidationResult(val === undefined || (typeof val === 'number' && val >= 0), 'Min height must be a non-negative number'),
  },
  {
    id: 'layout.maxHeight',
    label: 'Max Height',
    description: 'Maximum height in pixels',
    widget: 'number',
    category: 'layout',
    defaultValue: 0,
    min: 0,
    validation: (val) => toValidationResult(val === undefined || (typeof val === 'number' && val >= 0), 'Max height must be a non-negative number'),
  },
  {
    id: 'layout.aspectRatio',
    label: 'Aspect Ratio',
    description: 'Width over height aspect ratio',
    widget: 'number',
    category: 'layout',
    defaultValue: 1,
    min: 0,
    validation: (val) => toValidationResult(val === undefined || (typeof val === 'number' && val > 0), 'Aspect ratio must be a positive number'),
  },
  {
    id: 'layout.sizingWidth',
    label: 'Width Sizing',
    description: 'Width sizing behavior mode',
    widget: 'select',
    category: 'layout',
    defaultValue: 'fixed',
    options: [
      { label: 'Fixed', value: 'fixed' },
      { label: 'Fill Container', value: 'fill' },
      { label: 'Fit Content', value: 'fit' },
      { label: 'Stretch', value: 'stretch' },
    ],
    validation: (val) => toValidationResult(['fixed', 'fill', 'fit', 'stretch'].includes(val as string), 'Invalid sizing width value'),
  },
  {
    id: 'layout.sizingHeight',
    label: 'Height Sizing',
    description: 'Height sizing behavior mode',
    widget: 'select',
    category: 'layout',
    defaultValue: 'fixed',
    options: [
      { label: 'Fixed', value: 'fixed' },
      { label: 'Fill Container', value: 'fill' },
      { label: 'Fit Content', value: 'fit' },
      { label: 'Stretch', value: 'stretch' },
    ],
    validation: (val) => toValidationResult(['fixed', 'fill', 'fit', 'stretch'].includes(val as string), 'Invalid sizing height value'),
  },
];