/**
 * motion-experiences.ts — 10 Spatial 3D & Motion Experiences for SoloSpot v3.0
 *
 * Implemented using clean, hardware-accelerated CSS 3D transforms, perspective grids,
 * and spatial card depth without unnecessary external heavy WebGL dependencies.
 */

import {
  createBuilderNode,
  createSectionNode,
  generateNodeId,
} from '../../../../packages/builder-core/src';
import type { ExperienceItem } from '../ExperienceTypes';

export const motionExperiences: ExperienceItem[] = [
  {
    id: 'motion-3d-perspective-grid',
    name: '3D Perspective Grid Showcase',
    type: 'motion',
    category: 'motion',
    description: 'Spatial layout featuring CSS 3D perspective tilt, angled depth cards, and subtle elevation shadows.',
    tagline: 'Hardware-accelerated 3D depth',
    badge: '3D Motion',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'futuristic',
    motionLevel: 'animated',
    industry: ['saas', 'creative', 'technology'],
    tags: ['3d', 'perspective', 'depth', 'spatial', 'motion'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: 3D Perspective Grid',
        styles: {
          backgroundColor: '#05050c',
          padding: { top: '100px', right: '24px', bottom: '100px', left: '24px' },
          overflow: 'hidden',
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Stage Header',
            styles: { maxWidth: '800px', margin: { top: '0', right: 'auto', bottom: '50px', left: 'auto' }, textAlign: 'center', display: 'flex', flexDirection: 'column', gap: '16px' },
            children: [
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Eyebrow', props: { text: 'SPATIAL COMPOSITION' }, styles: { fontSize: '12px', fontWeight: '800', color: '#a78bfa', letterSpacing: '2px' } }),
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Title', props: { text: '3D Perspective & Spatial Depth' }, styles: { fontSize: '42px', fontWeight: '800', color: '#ffffff', letterSpacing: '-1px' } }),
              createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Subtitle', props: { text: 'Craft immersive interfaces that feel physical and reactive using clean CSS perspective transforms.' }, styles: { fontSize: '16px', color: '#94a3b8' } }),
            ],
          }),
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Perspective Stage',
            styles: {
              maxWidth: '1050px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              display: 'flex',
              flexDirection: 'row',
              gap: '28px',
              justifyContent: 'center',
              alignItems: 'center',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Angled Left Card',
                styles: {
                  width: '320px',
                  backgroundColor: '#0f0f18',
                  borderWidth: '1px',
                  borderColor: '#262638',
                  borderRadius: '18px',
                  padding: { top: '30px', right: '24px', bottom: '30px', left: '24px' },
                  boxShadow: '-15px 25px 40px -10px rgba(0, 0, 0, 0.7)',
                  transform: 'rotateY(12deg) rotateX(4deg) scale(0.95)',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Left Title', props: { text: 'Left Wing Track' }, styles: { fontSize: '18px', fontWeight: '700', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Left Desc', props: { text: 'Simulated multi-plane perspective without Three.js overhead.' }, styles: { fontSize: '13px', color: '#94a3b8', marginTop: '8px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Center Elevated Card',
                styles: {
                  width: '360px',
                  backgroundColor: '#161524',
                  borderWidth: '2px',
                  borderColor: '#8b5cf6',
                  borderRadius: '22px',
                  padding: { top: '36px', right: '28px', bottom: '36px', left: '28px' },
                  boxShadow: '0 25px 50px -12px rgba(124, 58, 237, 0.35)',
                  transform: 'scale(1.05) translateZ(30px)',
                  zIndex: 10,
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Center Title', props: { text: 'Focal Elevation' }, styles: { fontSize: '22px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Center Desc', props: { text: 'Direct attention to your primary conversion asset with hardware-accelerated Z-elevation.' }, styles: { fontSize: '14px', color: '#e2e8f0', marginTop: '10px' } }),
                  createBuilderNode({ id: generateNodeId('button'), type: 'button', label: 'Center CTA', props: { text: 'Launch Experience' }, styles: { backgroundColor: '#7c3aed', color: '#ffffff', padding: { top: '10px', right: '20px', bottom: '10px', left: '20px' }, borderRadius: '10px', fontWeight: '700', marginTop: '16px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Angled Right Card',
                styles: {
                  width: '320px',
                  backgroundColor: '#0f0f18',
                  borderWidth: '1px',
                  borderColor: '#262638',
                  borderRadius: '18px',
                  padding: { top: '30px', right: '24px', bottom: '30px', left: '24px' },
                  boxShadow: '15px 25px 40px -10px rgba(0, 0, 0, 0.7)',
                  transform: 'rotateY(-12deg) rotateX(4deg) scale(0.95)',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Right Title', props: { text: 'Right Wing Track' }, styles: { fontSize: '18px', fontWeight: '700', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Right Desc', props: { text: 'Complete responsiveness that auto-stacks on mobile devices.' }, styles: { fontSize: '13px', color: '#94a3b8', marginTop: '8px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-isometric-3d-showcase',
    name: 'Isometric 3D Showcase Stage',
    type: 'motion',
    category: 'motion',
    description: 'Elevated isometric platform showcasing multi-tiered product capabilities with 3D projection.',
    tagline: 'Isometric stage architecture',
    badge: '3D Isometric',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'futuristic',
    motionLevel: 'animated',
    industry: ['technology', 'crypto', 'saas'],
    tags: ['isometric', '3d', 'showcase', 'architecture', 'tier'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Isometric Showcase Stage',
        styles: {
          backgroundColor: '#080811',
          backgroundImage: 'radial-gradient(circle at 50% 30%, rgba(59, 130, 246, 0.15) 0%, transparent 70%)',
          padding: { top: '90px', right: '24px', bottom: '90px', left: '24px' },
          overflow: 'hidden',
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Isometric Stage Frame',
            styles: {
              maxWidth: '900px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '40px',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Title Block',
                styles: { textAlign: 'center', maxWidth: '640px' },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Title', props: { text: 'Architectural Isometric Stage' }, styles: { fontSize: '38px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Subtitle', props: { text: 'True isometric projection created with CSS coordinate rotation and elevation shadows.' }, styles: { fontSize: '15px', color: '#94a3b8', marginTop: '10px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Isometric Projected Slab',
                styles: {
                  width: '540px',
                  backgroundColor: '#111222',
                  borderWidth: '2px',
                  borderColor: '#3b82f6',
                  borderRadius: '24px',
                  padding: { top: '40px', right: '40px', bottom: '40px', left: '40px' },
                  boxShadow: '0 40px 80px -20px rgba(0, 0, 0, 0.8), 0 0 40px rgba(59, 130, 246, 0.25)',
                  transform: 'rotateX(45deg) rotateZ(-20deg)',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Platform Heading', props: { text: 'Decentralized Core Engine' }, styles: { fontSize: '20px', fontWeight: '700', color: '#60a5fa' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Platform Desc', props: { text: 'Active nodes: 1,420 • Throughput: 98,000 tx/s • Latency: 1.2ms' }, styles: { fontSize: '13px', color: '#e2e8f0', marginTop: '8px' } }),
                  createBuilderNode({
                    id: generateNodeId('container'),
                    type: 'container',
                    label: 'Elevated Tier Chip',
                    styles: {
                      marginTop: '20px',
                      backgroundColor: 'rgba(59, 130, 246, 0.15)',
                      borderWidth: '1px',
                      borderColor: '#60a5fa',
                      borderRadius: '12px',
                      padding: { top: '12px', right: '16px', bottom: '12px', left: '16px' },
                    },
                    children: [
                      createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Tier Text', props: { text: '⚡ Real-time synchronization active across all regions' }, styles: { fontSize: '12px', fontWeight: '600', color: '#93c5fd' } }),
                    ],
                  }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-parallax-depth-stack',
    name: 'Parallax Depth Layer Stack',
    type: 'motion',
    category: 'motion',
    description: 'Multi-plane layout with staggered visual depth, glass edge highlights, and spatial separation.',
    tagline: 'Layered parallax separation',
    badge: '3D Parallax',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'dark',
    motionLevel: 'animated',
    industry: ['creative', 'agency', 'luxury'],
    tags: ['parallax', 'depth', 'layers', 'spatial'],
    capabilities: { perspective3d: true, glassmorphism: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Parallax Depth Layer Stack',
        styles: {
          backgroundColor: '#07070b',
          padding: { top: '100px', right: '24px', bottom: '100px', left: '24px' },
          overflow: 'hidden',
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Depth Stack Stage',
            styles: {
              maxWidth: '840px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              position: 'relative',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Back Layer (Deep)',
                styles: {
                  width: '90%',
                  backgroundColor: '#121220',
                  borderRadius: '20px',
                  padding: { top: '30px', right: '30px', bottom: '30px', left: '30px' },
                  boxShadow: '0 20px 40px rgba(0,0,0,0.5)',
                  transform: 'scale(0.92) translateY(-20px)',
                  opacity: 0.7,
                  borderWidth: '1px',
                  borderColor: '#232338',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Layer 1 Text', props: { text: 'Back Plane: Data Pipeline Infrastructure' }, styles: { fontSize: '13px', color: '#64748b' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Mid Layer',
                styles: {
                  width: '95%',
                  backgroundColor: '#18192a',
                  borderRadius: '20px',
                  padding: { top: '35px', right: '35px', bottom: '35px', left: '35px' },
                  boxShadow: '0 25px 50px rgba(0,0,0,0.6)',
                  transform: 'scale(0.96) translateY(-10px)',
                  opacity: 0.88,
                  borderWidth: '1px',
                  borderColor: '#343654',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Layer 2 Text', props: { text: 'Mid Plane: Intelligent Synthesis & Routing Layer' }, styles: { fontSize: '14px', color: '#94a3b8' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Front Focal Layer',
                styles: {
                  width: '100%',
                  backgroundColor: '#1f2038',
                  borderRadius: '24px',
                  padding: { top: '44px', right: '40px', bottom: '44px', left: '40px' },
                  boxShadow: '0 30px 60px -15px rgba(0,0,0,0.8), 0 0 35px rgba(168, 85, 247, 0.25)',
                  borderWidth: '2px',
                  borderColor: '#a855f7',
                  transform: 'scale(1.0) translateY(0)',
                  zIndex: 5,
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Focal Title', props: { text: 'Front Focal Plane: User Experience' }, styles: { fontSize: '24px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Focal Desc', props: { text: 'Every layer moves with subtle parallax speed differential to establish cinematic physical presence.' }, styles: { fontSize: '15px', color: '#e2e8f0', marginTop: '10px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-3d-hover-tilt-product-card',
    name: '3D Hover Tilt Product Card',
    type: 'motion',
    category: 'motion',
    description: 'Interactive product card with hardware-accelerated 3D tilt reaction, specular sheen, and specs.',
    tagline: 'Kinetic product showcase',
    badge: '3D Tilt',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'futuristic',
    motionLevel: 'animated',
    industry: ['ecommerce', 'technology', 'gadgets'],
    tags: ['3d', 'tilt', 'product', 'card', 'glow'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: 3D Hover Tilt Product Card',
        styles: {
          backgroundColor: '#09090e',
          padding: { top: '90px', right: '24px', bottom: '90px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Showcase Frame',
            styles: {
              maxWidth: '460px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              backgroundColor: '#131422',
              borderRadius: '24px',
              borderWidth: '2px',
              borderColor: '#6366f1',
              padding: { top: '36px', right: '32px', bottom: '36px', left: '32px' },
              boxShadow: '0 25px 60px -15px rgba(99, 102, 241, 0.4)',
              transform: 'rotateX(8deg) rotateY(-8deg)',
            },
            children: [
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Tag', props: { text: 'PRO EDITION • GEN 3' }, styles: { fontSize: '11px', fontWeight: '800', color: '#818cf8', letterSpacing: '2px' } }),
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Name', props: { text: 'Neural Interface Ring' }, styles: { fontSize: '28px', fontWeight: '800', color: '#ffffff', marginTop: '8px' } }),
              createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Specs', props: { text: 'Titanium chassis, 48-hour battery, sub-millisecond tactile haptics.' }, styles: { fontSize: '14px', color: '#94a3b8', marginTop: '12px' } }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Price & CTA Bar',
                styles: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: '28px' },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Price', props: { text: '$349' }, styles: { fontSize: '24px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('button'), type: 'button', label: 'CTA Button', props: { text: 'Pre-order Now' }, styles: { backgroundColor: '#6366f1', color: '#ffffff', padding: { top: '10px', right: '20px', bottom: '10px', left: '20px' }, borderRadius: '10px', fontWeight: '700' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-spatial-floating-mockup-panel',
    name: 'Spatial Floating Mockup Panel',
    type: 'motion',
    category: 'motion',
    description: 'Suspended terminal/browser dashboard hovering in spatial depth with glass finish.',
    tagline: 'Floating spatial dashboard',
    badge: 'Spatial Mockup',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'dark',
    motionLevel: 'animated',
    industry: ['developer', 'saas', 'cloud'],
    tags: ['mockup', 'dashboard', 'spatial', '3d', 'terminal'],
    capabilities: { perspective3d: true, glassmorphism: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Spatial Floating Mockup',
        styles: {
          backgroundColor: '#04050a',
          backgroundImage: 'radial-gradient(circle at 50% 50%, rgba(16, 185, 129, 0.1) 0%, transparent 60%)',
          padding: { top: '90px', right: '24px', bottom: '90px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Mockup Window Frame',
            styles: {
              maxWidth: '820px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              backgroundColor: '#0f111a',
              borderRadius: '20px',
              borderWidth: '1px',
              borderColor: '#222738',
              boxShadow: '0 30px 70px -15px rgba(0, 0, 0, 0.9), 0 0 40px rgba(16, 185, 129, 0.15)',
              transform: 'rotateX(6deg) translateY(-10px)',
              overflow: 'hidden',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Window Topbar',
                styles: {
                  backgroundColor: '#161926',
                  padding: { top: '14px', right: '20px', bottom: '14px', left: '20px' },
                  display: 'flex',
                  flexDirection: 'row',
                  alignItems: 'center',
                  gap: '8px',
                  borderBottomWidth: '1px',
                  borderBottomColor: '#222738',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Window Title', props: { text: '● ● ●   terminal — bash — 80x24' }, styles: { fontSize: '12px', color: '#64748b', fontFamily: 'monospace' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Window Content',
                styles: { padding: { top: '30px', right: '30px', bottom: '30px', left: '30px' } },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Command Output', props: { text: '$ deploy-orchestrator --target global-edge' }, styles: { fontSize: '18px', color: '#34d399', fontFamily: 'monospace' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Logs', props: { text: '✓ Edge cluster synchronized in 14ms across 32 points of presence.\n✓ Zero downtime rollout completed successfully.' }, styles: { fontSize: '14px', color: '#94a3b8', marginTop: '12px', lineHeight: '1.6' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-layered-floating-glass-planes',
    name: 'Layered Floating Glass Planes',
    type: 'motion',
    category: 'motion',
    description: 'Translucent glassmorphic panels floating at varying Z-levels with backdrop blur.',
    tagline: 'Glass plane architecture',
    badge: 'Glass 3D',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'futuristic',
    motionLevel: 'animated',
    industry: ['fintech', 'luxury', 'saas'],
    tags: ['glass', 'floating', 'planes', 'backdrop-filter', 'spatial'],
    capabilities: { perspective3d: true, glassmorphism: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Layered Floating Glass Planes',
        styles: {
          backgroundColor: '#030308',
          backgroundImage: 'linear-gradient(135deg, rgba(236, 72, 153, 0.15), rgba(139, 92, 246, 0.15))',
          padding: { top: '90px', right: '24px', bottom: '90px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Glass Plane Duo',
            styles: {
              maxWidth: '900px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              display: 'flex',
              flexDirection: 'row',
              gap: '30px',
              justifyContent: 'center',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Glass Panel Alpha',
                styles: {
                  flex: '1',
                  backgroundColor: 'rgba(255, 255, 255, 0.05)',
                  backdropFilter: 'blur(20px)',
                  borderWidth: '1px',
                  borderColor: 'rgba(255, 255, 255, 0.18)',
                  borderRadius: '24px',
                  padding: { top: '36px', right: '30px', bottom: '36px', left: '30px' },
                  boxShadow: '0 30px 60px rgba(0, 0, 0, 0.5)',
                  transform: 'rotateY(8deg) translateY(-10px)',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Alpha Heading', props: { text: 'Layer Alpha: Transparency' }, styles: { fontSize: '20px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Alpha Text', props: { text: 'Real-time backdrop blur rendered natively with hardware compositor.' }, styles: { fontSize: '14px', color: '#cbd5e1', marginTop: '10px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Glass Panel Beta',
                styles: {
                  flex: '1',
                  backgroundColor: 'rgba(255, 255, 255, 0.08)',
                  backdropFilter: 'blur(24px)',
                  borderWidth: '1px',
                  borderColor: 'rgba(255, 255, 255, 0.25)',
                  borderRadius: '24px',
                  padding: { top: '36px', right: '30px', bottom: '36px', left: '30px' },
                  boxShadow: '0 30px 60px rgba(0, 0, 0, 0.5), 0 0 30px rgba(236, 72, 153, 0.2)',
                  transform: 'rotateY(-8deg) translateY(10px)',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Beta Heading', props: { text: 'Layer Beta: Refraction' }, styles: { fontSize: '20px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Beta Text', props: { text: 'Elevated spatial plane with high contrast specular border edges.' }, styles: { fontSize: '14px', color: '#cbd5e1', marginTop: '10px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-kinetic-spatial-typography',
    name: 'Kinetic Spatial Typography',
    type: 'motion',
    category: 'motion',
    description: 'Dynamic oversized display typography angled in 3D perspective space.',
    tagline: 'Angled kinetic perspective',
    badge: '3D Typography',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'bold',
    motionLevel: 'animated',
    industry: ['creative', 'fashion', 'music'],
    tags: ['kinetic', 'typography', '3d', 'bold', 'perspective'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Kinetic Typography',
        styles: {
          backgroundColor: '#0a0a12',
          padding: { top: '100px', right: '24px', bottom: '100px', left: '24px' },
          overflow: 'hidden',
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Angled Type Stage',
            styles: {
              maxWidth: '900px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              transform: 'rotateX(18deg) skewX(-6deg)',
              textAlign: 'center',
            },
            children: [
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Gigantic Word 1', props: { text: 'SPEED.' }, styles: { fontSize: '72px', fontWeight: '900', color: '#38bdf8', letterSpacing: '-3px' } }),
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Gigantic Word 2', props: { text: 'PRECISION.' }, styles: { fontSize: '72px', fontWeight: '900', color: '#a855f7', letterSpacing: '-3px' } }),
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Gigantic Word 3', props: { text: 'IMMERSION.' }, styles: { fontSize: '72px', fontWeight: '900', color: '#f43f5e', letterSpacing: '-3px' } }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-3d-rotating-badge-stage',
    name: '3D Rotating Badge Stage',
    type: 'motion',
    category: 'motion',
    description: 'Circular spatial pedestal with floating angled achievement and trust badges.',
    tagline: 'Spatial trust pedestal',
    badge: '3D Badges',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'modern',
    motionLevel: 'animated',
    industry: ['saas', 'enterprise', 'security'],
    tags: ['badges', 'pedestal', '3d', 'trust', 'security'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: 3D Rotating Badge Stage',
        styles: {
          backgroundColor: '#07070f',
          padding: { top: '80px', right: '24px', bottom: '80px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Badge Trio Row',
            styles: {
              maxWidth: '840px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'center',
              gap: '24px',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'SOC-2 Badge',
                styles: {
                  width: '240px',
                  backgroundColor: '#11121d',
                  borderRadius: '16px',
                  borderWidth: '1px',
                  borderColor: '#2a2c42',
                  padding: { top: '24px', right: '20px', bottom: '24px', left: '20px' },
                  transform: 'rotateY(15deg) translateY(-8px)',
                  textAlign: 'center',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'SOC2 Title', props: { text: 'SOC 2 Type II' }, styles: { fontSize: '18px', fontWeight: '700', color: '#10b981' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'SOC2 Desc', props: { text: 'Certified Enterprise Security' }, styles: { fontSize: '12px', color: '#94a3b8', marginTop: '6px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'ISO Badge',
                styles: {
                  width: '240px',
                  backgroundColor: '#161726',
                  borderRadius: '16px',
                  borderWidth: '2px',
                  borderColor: '#6366f1',
                  padding: { top: '24px', right: '20px', bottom: '24px', left: '20px' },
                  transform: 'scale(1.06) translateZ(20px)',
                  boxShadow: '0 15px 35px rgba(99, 102, 241, 0.3)',
                  textAlign: 'center',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'ISO Title', props: { text: 'ISO 27001' }, styles: { fontSize: '18px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'ISO Desc', props: { text: 'Audited Global Compliance' }, styles: { fontSize: '12px', color: '#c7d2fe', marginTop: '6px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'GDPR Badge',
                styles: {
                  width: '240px',
                  backgroundColor: '#11121d',
                  borderRadius: '16px',
                  borderWidth: '1px',
                  borderColor: '#2a2c42',
                  padding: { top: '24px', right: '20px', bottom: '24px', left: '20px' },
                  transform: 'rotateY(-15deg) translateY(-8px)',
                  textAlign: 'center',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'GDPR Title', props: { text: 'GDPR / HIPAA' }, styles: { fontSize: '18px', fontWeight: '700', color: '#38bdf8' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'GDPR Desc', props: { text: 'End-to-End Privacy Shield' }, styles: { fontSize: '12px', color: '#94a3b8', marginTop: '6px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-3d-depth-card-gallery',
    name: '3D Depth Card Gallery',
    type: 'motion',
    category: 'motion',
    description: 'Rotated perspective cards arranged in carousel depth with illuminated edges.',
    tagline: 'Perspective depth gallery',
    badge: '3D Carousel',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'vibrant',
    motionLevel: 'animated',
    industry: ['creative', 'entertainment', 'portfolio'],
    tags: ['gallery', '3d', 'depth', 'carousel', 'cards'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: 3D Depth Card Gallery',
        styles: {
          backgroundColor: '#05050a',
          padding: { top: '90px', right: '24px', bottom: '90px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Gallery Row',
            styles: {
              maxWidth: '960px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'center',
              gap: '20px',
            },
            children: [
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Left Gallery Item',
                styles: {
                  width: '280px',
                  backgroundColor: '#0e1017',
                  borderRadius: '20px',
                  padding: { top: '30px', right: '22px', bottom: '30px', left: '22px' },
                  transform: 'rotateY(16deg) scale(0.92)',
                  borderWidth: '1px',
                  borderColor: '#1e2433',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Item 1', props: { text: 'Concept Zero' }, styles: { fontSize: '18px', fontWeight: '700', color: '#f59e0b' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Desc 1', props: { text: 'Rapid prototypes and initial vision explorations.' }, styles: { fontSize: '13px', color: '#94a3b8', marginTop: '6px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Center Gallery Item',
                styles: {
                  width: '320px',
                  backgroundColor: '#151924',
                  borderRadius: '20px',
                  padding: { top: '36px', right: '26px', bottom: '36px', left: '26px' },
                  transform: 'scale(1.05)',
                  borderWidth: '2px',
                  borderColor: '#f59e0b',
                  boxShadow: '0 20px 50px rgba(245, 158, 11, 0.25)',
                  zIndex: 4,
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Item 2', props: { text: 'Production Alpha' }, styles: { fontSize: '22px', fontWeight: '800', color: '#ffffff' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Desc 2', props: { text: 'High-throughput execution with enterprise hardening.' }, styles: { fontSize: '14px', color: '#cbd5e1', marginTop: '8px' } }),
                ],
              }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Right Gallery Item',
                styles: {
                  width: '280px',
                  backgroundColor: '#0e1017',
                  borderRadius: '20px',
                  padding: { top: '30px', right: '22px', bottom: '30px', left: '22px' },
                  transform: 'rotateY(-16deg) scale(0.92)',
                  borderWidth: '1px',
                  borderColor: '#1e2433',
                },
                children: [
                  createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Item 3', props: { text: 'Autonomous Scale' }, styles: { fontSize: '18px', fontWeight: '700', color: '#10b981' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Desc 3', props: { text: 'Self-healing cluster topologies on the edge.' }, styles: { fontSize: '13px', color: '#94a3b8', marginTop: '6px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
  {
    id: 'motion-spatial-orbit-ecosystem',
    name: 'Spatial Orbit Ecosystem',
    type: 'motion',
    category: 'motion',
    description: 'Central nucleus node surrounded by satellite integration cards angled in 3D orbit.',
    tagline: 'Orbital integration stage',
    badge: '3D Orbit',
    source: 'builtin',
    schemaVersion: '2.0.0',
    contentVersion: '2.0.0',
    mood: 'futuristic',
    motionLevel: 'animated',
    industry: ['saas', 'integrations', 'technology'],
    tags: ['orbit', 'nucleus', 'integrations', 'ecosystem', '3d'],
    capabilities: { perspective3d: true },
    createNode: () => {
      return createSectionNode({
        id: generateNodeId('section'),
        type: 'section',
        label: 'Motion: Spatial Orbit Ecosystem',
        styles: {
          backgroundColor: '#06060c',
          backgroundImage: 'radial-gradient(circle at 50% 50%, rgba(139, 92, 246, 0.2) 0%, transparent 60%)',
          padding: { top: '100px', right: '24px', bottom: '100px', left: '24px' },
        },
        children: [
          createBuilderNode({
            id: generateNodeId('container'),
            type: 'container',
            label: 'Central Core Nucleus',
            styles: {
              maxWidth: '520px',
              margin: { top: '0', right: 'auto', bottom: '0', left: 'auto' },
              backgroundColor: '#121324',
              borderRadius: '28px',
              borderWidth: '2px',
              borderColor: '#8b5cf6',
              padding: { top: '44px', right: '36px', bottom: '44px', left: '36px' },
              boxShadow: '0 25px 60px -10px rgba(139, 92, 246, 0.4)',
              textAlign: 'center',
            },
            children: [
              createBuilderNode({ id: generateNodeId('heading'), type: 'heading', label: 'Core Title', props: { text: 'Universal Orchestration Core' }, styles: { fontSize: '26px', fontWeight: '800', color: '#ffffff' } }),
              createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Core Desc', props: { text: 'Connect 100+ data sources, AI agents, and webhooks in a unified spatial control plane.' }, styles: { fontSize: '14px', color: '#cbd5e1', marginTop: '10px' } }),
              createBuilderNode({
                id: generateNodeId('container'),
                type: 'container',
                label: 'Satellite Badge Orbit',
                styles: { display: 'flex', flexDirection: 'row', justifyContent: 'center', gap: '12px', marginTop: '24px' },
                children: [
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Sat 1', props: { text: '⚡ Stripe' }, styles: { fontSize: '12px', color: '#e2e8f0', backgroundColor: '#1e2038', padding: { top: '6px', right: '12px', bottom: '6px', left: '12px' }, borderRadius: '8px' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Sat 2', props: { text: '✦ OpenAI' }, styles: { fontSize: '12px', color: '#e2e8f0', backgroundColor: '#1e2038', padding: { top: '6px', right: '12px', bottom: '6px', left: '12px' }, borderRadius: '8px' } }),
                  createBuilderNode({ id: generateNodeId('text'), type: 'text', label: 'Sat 3', props: { text: '☁ AWS' }, styles: { fontSize: '12px', color: '#e2e8f0', backgroundColor: '#1e2038', padding: { top: '6px', right: '12px', bottom: '6px', left: '12px' }, borderRadius: '8px' } }),
                ],
              }),
            ],
          }),
        ],
      });
    },
  },
];
