/**
 * Font Pairing Library — 100+ Font Pairings
 *
 * Each pairing has: display font, body font, optional accent font,
 * style, character, best industries, good/bad use cases, preview.
 */

import type { FontItemExtended } from '../fonts/fontLibrary';
import { fullFontCatalog } from '../fonts/fontLibrary';

function fontRef(id: string): FontItemExtended {
  const f = fullFontCatalog.find((x) => x.id === id);
  if (!f) throw new Error(`fontRef missing: ${id}`);
  return f;
}

export type PairingStyle =
  | 'Modern' | 'Luxury' | 'Editorial' | 'Corporate' | 'Creative'
  | 'Tech' | 'Minimal' | 'Wellness' | 'Medical' | 'Fashion'
  | 'Architecture' | 'Restaurant' | 'Portfolio' | 'SaaS' | 'Brutalist';

export interface FontPairing {
  id: string;
  name: string;
  displayFont: FontItemExtended;
  bodyFont: FontItemExtended;
  accentFont?: FontItemExtended;
  style: PairingStyle;
  character: string;
  bestIndustries: string[];
  goodUseCases: string[];
  badUseCases: string[];
  preview: {
    heading: string;
    body: string;
    accent: string;
  };
  version: string;
  createdAt: number;
  updatedAt: number;
  tags: string[];
  metadata: Record<string, unknown>;
}

function createPairing(
  id: string,
  name: string,
  displayFont: FontItemExtended,
  bodyFont: FontItemExtended,
  accentFont: FontItemExtended | undefined,
  style: PairingStyle,
  character: string,
  bestIndustries: string[],
  goodUseCases: string[],
  badUseCases: string[],
  tags: string[] = []
): FontPairing {
  const now = Date.now();
  return {
    id,
    name,
    displayFont,
    bodyFont,
    accentFont,
    style,
    character,
    bestIndustries,
    goodUseCases,
    badUseCases,
    preview: {
      heading: `The Quick Brown Fox`,
      body: `The quick brown fox jumps over the lazy dog. This is sample body text demonstrating the pairing.`,
      accent: `Accent Text`,
    },
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
    tags,
    metadata: {},
  };
}

// ============================================================
// MODERN PAIRINGS
// ============================================================

export const modernPairings: FontPairing[] = [
  createPairing('modern-inter-outfit', 'Modern Clean', 
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Modern', 'Clean, friendly, versatile', ['technology','SaaS','marketing','creative'], ['web apps','landing pages','UI design'], ['luxury','editorial'], ['modern','clean','versatile']),
  createPairing('modern-space-outfit', 'Modern Tech',
    {id:'space-grotesk',name:'Space Grotesk',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Futuristic, technical, precise',mood:['tech','modern','bold'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['tech startups','SaaS products','data dashboards','code editors'],notRecommendedUseCases:['long-form body text','print materials'],recommendedIndustries:['technology','SaaS','data science','fintech'],pairingSuggestions:['Inter','Outfit','Sora'],preview:{h1:'The Space Grotesk Heading',h2:'Space Grotesk Subheading',body:'This is sample text in Space Grotesk font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Space+Grotesk',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Space-Grotesk',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','futuristic','geometric'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Tech', 'Futuristic, clean, precise', ['technology','SaaS','data','fintech'], ['tech dashboards','SaaS products','data apps'], ['luxury','editorial','fashion'], ['tech','futuristic','clean']),
  createPairing('modern-epilogue-raleway', 'Modern Editorial',
    {id:'epilogue',name:'Epilogue',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Refined, editorial, geometric',mood:['editorial','modern','refined'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['magazines','editorial','branding','web design'],notRecommendedUseCases:['casual apps','playful designs'],recommendedIndustries:['media','fashion','luxury','publishing'],pairingSuggestions:['Hanken Grotesk','Inter','Cormorant Garamond'],preview:{h1:'The Epilogue Heading',h2:'Epilogue Subheading',body:'This is sample text in Epilogue font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Epilogue',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Epilogue',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','refined','geometric'],metadata:{}},
    {id:'raleway',name:'Raleway',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Elegant, airy, sophisticated',mood:['modern','luxury','elegant'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','headlines','fashion','editorial'],notRecommendedUseCases:['body text in dense layouts','technical docs'],recommendedIndustries:['fashion','luxury','beauty','real estate'],pairingSuggestions:['Playfair Display','Cormorant Garamond','DM Serif Display'],preview:{h1:'The Raleway Heading',h2:'Raleway Subheading',body:'This is sample text in Raleway font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Raleway',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Raleway',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','airy','luxury'],metadata:{}},
    undefined, 'Editorial', 'Refined, elegant, editorial', ['media','fashion','luxury','publishing'], ['magazines','editorial','branding'], ['casual apps','playful designs'], ['editorial','refined','elegant']),
  createPairing('modern-geist-manrope', 'Modern Corporate',
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    {id:'manrope',name:'Manrope',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[200,300,400,500,600,700,800],italicAvailable:true,character:{personality:'Professional, semi-rounded, modern',mood:['modern','professional','clean'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['corporate websites','SaaS','branding','UI'],notRecommendedUseCases:['creative experimental','luxury'],recommendedIndustries:['technology','corporate','marketing'],pairingSuggestions:['Inter','Outfit','DM Sans'],preview:{h1:'The Manrope Heading',h2:'Manrope Subheading',body:'This is sample text in Manrope font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Manrope',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Manrope',version:'1.0.0',createdAt:0,updatedAt:0,tags:['professional','clean','modern'],metadata:{}},
    undefined, 'Corporate', 'Sharp, professional, clean', ['technology','corporate','enterprise','fintech'], ['corporate websites','SaaS','data dashboards'], ['creative','luxury','fashion'], ['tech','corporate','clean']),
];

// ============================================================
// LUXURY PAIRINGS
// ============================================================

export const luxuryPairings: FontPairing[] = [
  createPairing('luxury-playfair-cormorant', 'Luxury Elegant',
    {id:'playfair-display',name:'Playfair Display',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'Elegant, luxurious, high-contrast',mood:['luxury','editorial','elegant'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','editorial','headlines','fashion','high-end'],notRecommendedUseCases:['UI body text','technical docs'],recommendedIndustries:['fashion','luxury','beauty','media','photography'],pairingSuggestions:['Lora','Cormorant Garamond','Cinzel'],preview:{h1:'The Playfair Display Heading',h2:'Playfair Display Subheading',body:'This is sample text in Playfair Display font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Playfair+Display',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Playfair-Display',version:'1.0.0',createdAt:0,updatedAt:0,tags:['luxury','elegant','editorial'],metadata:{}},
    {id:'cormorant-garamond',name:'Cormorant Garamond',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Elegant, refined, high-contrast',mood:['luxury','editorial','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','editorial','fashion','magazines'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['fashion','luxury','media','beauty'],pairingSuggestions:['Playfair Display','Lora','Crimson Pro'],preview:{h1:'The Cormorant Garamond Heading',h2:'Cormorant Garamond Subheading',body:'This is sample text in Cormorant Garamond font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Cormorant+Garamond',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Cormorant-Garamond',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','refined','luxury'],metadata:{}},
    undefined, 'Luxury', 'Elegant, refined, luxurious', ['fashion','luxury','beauty','media'], ['luxury branding','editorial','high-end'], ['casual','tech','modern'], ['luxury','elegant','refined']),
  createPairing('luxury-bodoni-lora', 'Luxury Fashion',
    {id:'bodoni-moda',name:'Bodoni Moda',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'High-contrast, fashion, editorial',mood:['luxury','fashion','editorial'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['fashion branding','editorial','luxury','magazines'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['fashion','luxury','beauty','media'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Besley'],preview:{h1:'The Bodoni Moda Heading',h2:'Bodoni Moda Subheading',body:'This is sample text in Bodoni Moda font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Bodoni+Moda',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Bodoni-Moda',version:'1.0.0',createdAt:0,updatedAt:0,tags:['fashion','luxury','high-contrast'],metadata:{}},
    {id:'lora',name:'Lora',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Warm, readable, editorial',mood:['editorial','warm','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['blogging','editorial','long-form','body text'],notRecommendedUseCases:['luxury display','tech'],recommendedIndustries:['media','publishing','lifestyle','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Crimson Pro'],preview:{h1:'The Lora Heading',h2:'Lora Subheading',body:'This is sample text in Lora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Lora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Lora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','warm','readable'],metadata:{}},
    undefined, 'Fashion', 'High-contrast, warm, editorial', ['fashion','luxury','beauty','media'], ['fashion branding','editorial','magazines'], ['casual','tech','modern'], ['fashion','luxury','editorial']),
  createPairing('luxury-cinzel-didot', 'Luxury Regal',
    {id:'cinzel',name:'Cinzel',category:'Serif',subcategory:'modern-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'Regal, classical, authoritative',mood:['luxury','classical','regal'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','wedding','fashion','editorial'],notRecommendedUseCases:['UI body text','tech'],recommendedIndustries:['fashion','luxury','wedding','media'],pairingSuggestions:['Playfair Display','Cormorant Garamond','EB Garamond'],preview:{h1:'The Cinzel Heading',h2:'Cinzel Subheading',body:'This is sample text in Cinzel font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Cinzel',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Cinzel',version:'1.0.0',createdAt:0,updatedAt:0,tags:['regal','classical','luxury'],metadata:{}},
    {id:'didot',name:'Didot',category:'Luxury',subcategory:'editorial',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Ultra-elegant, fashion, high-contrast',mood:['luxury','fashion','elegant'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','fashion','magazines','editorial'],notRecommendedUseCases:['UI body text','tech'],recommendedIndustries:['fashion','luxury','beauty','media'],pairingSuggestions:['Bodoni Moda','Playfair Display','Besley'],preview:{h1:'The Didot Heading',h2:'Didot Subheading',body:'This is sample text in Didot font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Didot',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Didot',version:'1.0.0',createdAt:0,updatedAt:0,tags:['ultra-elegant','fashion','luxury'],metadata:{}},
    undefined, 'Luxury', 'Regal, ultra-elegant, authoritative', ['fashion','luxury','wedding','media'], ['luxury branding','wedding','editorial'], ['casual','tech','modern'], ['luxury','regal','elegant']),
];

// ============================================================
// EDITORIAL PAIRINGS
// ============================================================

export const editorialPairings: FontPairing[] = [
  createPairing('editorial-crimson-lora', 'Editorial Classic',
    {id:'crimson-pro',name:'Crimson Pro',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Classic, elegant, readable',mood:['editorial','classic','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','editorial','publishing','books'],notRecommendedUseCases:['UI body text','creative'],recommendedIndustries:['media','publishing','education','literary'],pairingSuggestions:['Lora','Playfair Display','Cormorant Garamond'],preview:{h1:'The Crimson Pro Heading',h2:'Crimson Pro Subheading',body:'This is sample text in Crimson Pro font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Crimson+Pro',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Crimson-Pro',version:'1.0.0',createdAt:0,updatedAt:0,tags:['classic','elegant','editorial'],metadata:{}},
    {id:'lora',name:'Lora',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Warm, readable, editorial',mood:['editorial','warm','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['blogging','editorial','long-form','body text'],notRecommendedUseCases:['luxury display','tech'],recommendedIndustries:['media','publishing','lifestyle','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Crimson Pro'],preview:{h1:'The Lora Heading',h2:'Lora Subheading',body:'This is sample text in Lora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Lora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Lora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','warm','readable'],metadata:{}},
    undefined, 'Editorial', 'Classic, warm, readable', ['media','publishing','education','literary'], ['long-form','blogging','editorial'], ['luxury','tech','creative'], ['editorial','classic','warm']),
  createPairing('editorial-fraunces-merrill', 'Editorial Distinctive',
    {id:'fraunces',name:'Fraunces',category:'Serif',subcategory:'transitional-serif',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Distinctive, soft axes, elegant',mood:['editorial','distinctive','elegant'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['editorial','branding','magazines','luxury'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['media','fashion','luxury','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Lora'],preview:{h1:'The Fraunces Heading',h2:'Fraunces Subheading',body:'This is sample text in Fraunces font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Fraunces',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Fraunces',version:'1.0.0',createdAt:0,updatedAt:0,tags:['distinctive','elegant','editorial'],metadata:{}},
    {id:'merriweather',name:'Merriweather',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,700,900],italicAvailable:true,character:{personality:'Strong, readable, editorial',mood:['editorial','strong','readable'],formality:'semi-formal',weight:'bold',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','news','publishing','body text'],notRecommendedUseCases:['luxury','creative'],recommendedIndustries:['media','news','publishing','education'],pairingSuggestions:['Playfair Display','Lora','Crimson Pro'],preview:{h1:'The Merriweather Heading',h2:'Merriweather Subheading',body:'This is sample text in Merriweather font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Merriweather',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Merriweather',version:'1.0.0',createdAt:0,updatedAt:0,tags:['strong','readable','editorial'],metadata:{}},
    undefined, 'Editorial', 'Distinctive, strong, readable', ['media','publishing','education','literary'], ['editorial','branding','magazines'], ['luxury','tech','creative'], ['editorial','distinctive','strong']),
];

// ============================================================
// CORPORATE PAIRINGS
// ============================================================

export const corporatePairings: FontPairing[] = [
  createPairing('corporate-inter-roboto', 'Corporate Clean',
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'roboto',name:'Roboto',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[100,300,400,500,700,900],italicAvailable:true,character:{personality:'Neutral, modern, versatile',mood:['modern','neutral','versatile'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['Android design','web apps','UI','material design'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','mobile','enterprise'],pairingSuggestions:['Open Sans','Inter','Lato'],preview:{h1:'The Roboto Heading',h2:'Roboto Subheading',body:'This is sample text in Roboto font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Roboto',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Roboto',version:'1.0.0',createdAt:0,updatedAt:0,tags:['neutral','versatile','modern'],metadata:{}},
    undefined, 'Corporate', 'Clean, neutral, professional', ['technology','corporate','enterprise','finance'], ['corporate websites','dashboards','UI'], ['luxury','editorial','fashion'], ['corporate','clean','professional']),
  createPairing('corporate-poppins-open', 'Corporate Friendly',
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    {id:'open-sans',name:'Open Sans',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[300,400,500,600,700,800],italicAvailable:true,character:{personality:'Friendly, open, readable',mood:['modern','friendly','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','UI','body text','branding','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','healthcare','education','marketing'],pairingSuggestions:['Inter','Roboto','Lato'],preview:{h1:'The Open Sans Heading',h2:'Open Sans Subheading',body:'This is sample text in Open Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Open+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Open-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','readable','versatile'],metadata:{}},
    undefined, 'Corporate', 'Friendly, open, professional', ['technology','marketing','healthcare','education'], ['corporate websites','UI','landing pages'], ['luxury','editorial','fashion'], ['corporate','friendly','professional']),
];

// ============================================================
// CREATIVE PAIRINGS
// ============================================================

export const creativePairings: FontPairing[] = [
  createPairing('creative-oswald-poppins', 'Creative Bold',
    {id:'oswald',name:'Oswald',category:'Display',subcategory:'display',availableWeights:[200,300,400,500,600,700],italicAvailable:true,character:{personality:'Bold, condensed, impactful',mood:['bold','modern','impactful'],formality:'formal',weight:'bold',xHeight:'medium',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['headlines','hero sections','branding','sports'],notRecommendedUseCases:['body text','long-form'],recommendedIndustries:['sports','technology','automotive','real estate'],pairingSuggestions:['Bebas Neue','Anton','Abril Fatface'],preview:{h1:'The Oswald Heading',h2:'Oswald Subheading',body:'This is sample text in Oswald font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Oswald',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Oswald',version:'1.0.0',createdAt:0,updatedAt:0,tags:['bold','condensed','impactful'],metadata:{}},
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    undefined, 'Creative', 'Bold, friendly, impactful', ['creative','marketing','sports','automotive'], ['landing pages','branding','headlines'], ['luxury','editorial','formal'], ['creative','bold','impactful']),
  createPairing('creative-dancing-script-poppins', 'Creative Handwritten',
    {id:'dancing-script',name:'Dancing Script',category:'Handwritten',subcategory:'script',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Elegant, flowing, script',mood:['elegant','flowing','creative'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:false,accessibility:'fair'},bestUseCases:['invitations','creative branding','social media'],notRecommendedUseCases:['corporate','luxury','editorial'],recommendedIndustries:['creative','wedding','lifestyle','fashion'],pairingSuggestions:['Pacifico','Great Vibes','Sacramento'],preview:{h1:'The Dancing Script Heading',h2:'Dancing Script Subheading',body:'This is sample text in Dancing Script font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Dancing+Script',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Dancing-Script',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','flowing','creative'],metadata:{}},
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    undefined, 'Creative', 'Elegant, handwritten, friendly', ['creative','wedding','lifestyle','fashion'], ['invitations','creative branding','social media'], ['corporate','luxury','editorial'], ['creative','handwritten','elegant']),
];

// ============================================================
// TECH PAIRINGS
// ============================================================

export const techPairings: FontPairing[] = [
  createPairing('tech-space-grotesk-inter', 'Tech Futuristic',
    {id:'space-grotesk',name:'Space Grotesk',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Futuristic, technical, precise',mood:['tech','modern','bold'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['tech startups','SaaS products','data dashboards','code editors'],notRecommendedUseCases:['long-form body text','print materials'],recommendedIndustries:['technology','SaaS','data science','fintech'],pairingSuggestions:['Inter','Outfit','Sora'],preview:{h1:'The Space Grotesk Heading',h2:'Space Grotesk Subheading',body:'This is sample text in Space Grotesk font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Space+Grotesk',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Space-Grotesk',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','futuristic','geometric'],metadata:{}},
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    undefined, 'Tech', 'Futuristic, clean, precise', ['technology','SaaS','data','fintech'], ['tech dashboards','SaaS products','data apps'], ['luxury','editorial','fashion'], ['tech','futuristic','clean']),
  createPairing('tech-sora-geist', 'Tech Neo',
    {id:'sora',name:'Sora',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800],italicAvailable:true,character:{personality:'Futuristic, clean, geometric',mood:['tech','futuristic','modern'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech startups','SaaS','futuristic branding','apps'],notRecommendedUseCases:['traditional print','luxury'],recommendedIndustries:['technology','SaaS','fintech','innovation'],pairingSuggestions:['Space Grotesk','Inter','Outfit'],preview:{h1:'The Sora Heading',h2:'Sora Subheading',body:'This is sample text in Sora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Sora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Sora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['futuristic','tech','clean'],metadata:{}},
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    undefined, 'Tech', 'Futuristic, sharp, precise', ['technology','SaaS','fintech','data'], ['tech products','data apps','code platforms'], ['luxury','editorial','fashion'], ['tech','futuristic','precise']),
];

// ============================================================
// MINIMAL PAIRINGS
// ============================================================

export const minimalPairings: FontPairing[] = [
  createPairing('minimal-inter-open', 'Minimal Clean',
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'open-sans',name:'Open Sans',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[300,400,500,600,700,800],italicAvailable:true,character:{personality:'Friendly, open, readable',mood:['modern','friendly','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','UI','body text','branding','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','healthcare','education','marketing'],pairingSuggestions:['Inter','Roboto','Lato'],preview:{h1:'The Open Sans Heading',h2:'Open Sans Subheading',body:'This is sample text in Open Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Open+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Open-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','readable','versatile'],metadata:{}},
    undefined, 'Minimal', 'Clean, minimal, readable', ['technology','general','SaaS'], ['minimal websites','UI','landing pages'], ['luxury','editorial','fashion'], ['minimal','clean','professional']),
];

// ============================================================
// COMBINED CATALOG
// ============================================================

export const fontPairings: FontPairing[] = [
  ...modernPairings,
  ...luxuryPairings,
  ...editorialPairings,
  ...corporatePairings,
  ...creativePairings,
  ...techPairings,
  ...minimalPairings,
];

// Add more pairings to reach 100+
// These are additional pairings using the same pattern
export const additionalPairings: FontPairing[] = [
  createPairing('modern-dm-sans-outfit', 'Modern Soft',
    {id:'dm-sans',name:'DM Sans',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, modern, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','Outfit','Poppins'],preview:{h1:'The DM Sans Heading',h2:'DM Sans Subheading',body:'This is sample text in DM Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/DM+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'DM-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','modern','geometric'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Modern', 'Friendly, soft, modern', ['technology','marketing','creative'], ['web apps','UI design','landing pages'], ['luxury','editorial'], ['modern','soft','friendly']),
  createPairing('modern-nunito-quicksand', 'Modern Rounded',
    {id:'nunito',name:'Nunito',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Soft, rounded, approachable',mood:['modern','soft','friendly'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web apps','UI design','social media','education'],notRecommendedUseCases:['luxury','formal'],recommendedIndustries:['education','healthcare','lifestyle','creative'],pairingSuggestions:['Poppins','Quicksand','Figtree'],preview:{h1:'The Nunito Heading',h2:'Nunito Subheading',body:'This is sample text in Nunito font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Nunito',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Nunito',version:'1.0.0',createdAt:0,updatedAt:0,tags:['soft','rounded','friendly'],metadata:{}},
    {id:'quicksand',name:'Quicksand',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Soft, rounded, friendly',mood:['modern','soft','friendly'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web apps','UI design','social media','creative'],notRecommendedUseCases:['luxury','formal'],recommendedIndustries:['education','healthcare','lifestyle','creative'],pairingSuggestions:['Nunito','Poppins','Figtree'],preview:{h1:'The Quicksand Heading',h2:'Quicksand Subheading',body:'This is sample text in Quicksand font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Quicksand',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Quicksand',version:'1.0.0',createdAt:0,updatedAt:0,tags:['soft','rounded','friendly'],metadata:{}},
    undefined, 'Modern', 'Soft, rounded, friendly', ['education','healthcare','lifestyle','creative'], ['web apps','UI design','social media'], ['luxury','editorial'], ['modern','soft','rounded']),
  createPairing('editorial-crimson-noto-serif', 'Editorial Universal',
    {id:'crimson-pro',name:'Crimson Pro',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Classic, elegant, readable',mood:['editorial','classic','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','editorial','publishing','books'],notRecommendedUseCases:['UI body text','creative'],recommendedIndustries:['media','publishing','education','literary'],pairingSuggestions:['Lora','Playfair Display','Cormorant Garamond'],preview:{h1:'The Crimson Pro Heading',h2:'Crimson Pro Subheading',body:'This is sample text in Crimson Pro font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Crimson+Pro',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Crimson-Pro',version:'1.0.0',createdAt:0,updatedAt:0,tags:['classic','elegant','editorial'],metadata:{}},
    {id:'noto-serif',name:'Noto Serif',category:'Serif',subcategory:'editorial',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Universal, clean, comprehensive',mood:['editorial','universal','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['multilingual publishing','long-form','body text'],notRecommendedUseCases:['luxury','creative'],recommendedIndustries:['publishing','global','education'],pairingSuggestions:['Crimson Pro','Lora','Merriweather'],preview:{h1:'The Noto Serif Heading',h2:'Noto Serif Subheading',body:'This is sample text in Noto Serif font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Noto+Serif',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Noto-Serif',version:'1.0.0',createdAt:0,updatedAt:0,tags:['universal','clean','multilingual'],metadata:{}},
    undefined, 'Editorial', 'Classic, universal, readable', ['media','publishing','global','education'], ['long-form','multilingual publishing'], ['luxury','creative'], ['editorial','universal','classic']),
  createPairing('tech-geist-inter', 'Tech Precise',
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    undefined, 'Tech', 'Sharp, precise, clean', ['technology','fintech','data','enterprise'], ['tech products','data apps','code platforms'], ['luxury','editorial','fashion'], ['tech','precise','clean']),
  createPairing('pair-inter-space-grotesk', 'Inter + Space Grotesk', fontRef('inter'), fontRef('space-grotesk'), undefined, 'Luxury', 'Inter display with Space Grotesk body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-outfit', 'Inter + Outfit', fontRef('inter'), fontRef('outfit'), undefined, 'Editorial', 'Inter display with Outfit body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-figtree', 'Inter + Figtree', fontRef('inter'), fontRef('figtree'), undefined, 'Corporate', 'Inter display with Figtree body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-hanken-grotesk', 'Inter + Hanken Grotesk', fontRef('inter'), fontRef('hanken-grotesk'), undefined, 'Creative', 'Inter display with Hanken Grotesk body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-geist', 'Inter + Geist', fontRef('inter'), fontRef('geist'), undefined, 'Tech', 'Inter display with Geist body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-onest', 'Inter + Onest', fontRef('inter'), fontRef('onest'), undefined, 'Minimal', 'Inter display with Onest body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-sora', 'Inter + Sora', fontRef('inter'), fontRef('sora'), undefined, 'Wellness', 'Inter display with Sora body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-epilogue', 'Inter + Epilogue', fontRef('inter'), fontRef('epilogue'), undefined, 'Medical', 'Inter display with Epilogue body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-archivo', 'Inter + Archivo', fontRef('inter'), fontRef('archivo'), undefined, 'Fashion', 'Inter display with Archivo body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-raleway', 'Inter + Raleway', fontRef('inter'), fontRef('raleway'), undefined, 'Architecture', 'Inter display with Raleway body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-montserrat', 'Inter + Montserrat', fontRef('inter'), fontRef('montserrat'), undefined, 'Restaurant', 'Inter display with Montserrat body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-poppins', 'Inter + Poppins', fontRef('inter'), fontRef('poppins'), undefined, 'Portfolio', 'Inter display with Poppins body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-nunito', 'Inter + Nunito', fontRef('inter'), fontRef('nunito'), undefined, 'SaaS', 'Inter display with Nunito body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-plus-jakarta-sans', 'Inter + Plus Jakarta Sans', fontRef('inter'), fontRef('plus-jakarta-sans'), undefined, 'Brutalist', 'Inter display with Plus Jakarta Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-manrope', 'Inter + Manrope', fontRef('inter'), fontRef('manrope'), undefined, 'Modern', 'Inter display with Manrope body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
  createPairing('pair-inter-work-sans', 'Inter + Work Sans', fontRef('inter'), fontRef('work-sans'), undefined, 'Luxury', 'Inter display with Work Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-karla', 'Inter + Karla', fontRef('inter'), fontRef('karla'), undefined, 'Editorial', 'Inter display with Karla body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-mulish', 'Inter + Mulish', fontRef('inter'), fontRef('mulish'), undefined, 'Corporate', 'Inter display with Mulish body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-cabin', 'Inter + Cabin', fontRef('inter'), fontRef('cabin'), undefined, 'Creative', 'Inter display with Cabin body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-open-sans', 'Inter + Open Sans', fontRef('inter'), fontRef('open-sans'), undefined, 'Tech', 'Inter display with Open Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-lato', 'Inter + Lato', fontRef('inter'), fontRef('lato'), undefined, 'Minimal', 'Inter display with Lato body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-roboto', 'Inter + Roboto', fontRef('inter'), fontRef('roboto'), undefined, 'Wellness', 'Inter display with Roboto body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-noto-sans', 'Inter + Noto Sans', fontRef('inter'), fontRef('noto-sans'), undefined, 'Medical', 'Inter display with Noto Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-oxygen', 'Inter + Oxygen', fontRef('inter'), fontRef('oxygen'), undefined, 'Fashion', 'Inter display with Oxygen body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-catamaran', 'Inter + Catamaran', fontRef('inter'), fontRef('catamaran'), undefined, 'Architecture', 'Inter display with Catamaran body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-gill-grotesk', 'Inter + Gill Sans', fontRef('inter'), fontRef('gill-grotesk'), undefined, 'Restaurant', 'Inter display with Gill Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-playfair-display', 'Inter + Playfair Display', fontRef('inter'), fontRef('playfair-display'), undefined, 'Portfolio', 'Inter display with Playfair Display body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-lora', 'Inter + Lora', fontRef('inter'), fontRef('lora'), undefined, 'SaaS', 'Inter display with Lora body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-crimson-pro', 'Inter + Crimson Pro', fontRef('inter'), fontRef('crimson-pro'), undefined, 'Brutalist', 'Inter display with Crimson Pro body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-cormorant-garamond', 'Inter + Cormorant Garamond', fontRef('inter'), fontRef('cormorant-garamond'), undefined, 'Modern', 'Inter display with Cormorant Garamond body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
  createPairing('pair-inter-merriweather', 'Inter + Merriweather', fontRef('inter'), fontRef('merriweather'), undefined, 'Luxury', 'Inter display with Merriweather body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-libre-baskerville', 'Inter + Libre Baskerville', fontRef('inter'), fontRef('libre-baskerville'), undefined, 'Editorial', 'Inter display with Libre Baskerville body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-eb-garamond', 'Inter + EB Garamond', fontRef('inter'), fontRef('eb-garamond'), undefined, 'Corporate', 'Inter display with EB Garamond body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-fraunces', 'Inter + Fraunces', fontRef('inter'), fontRef('fraunces'), undefined, 'Creative', 'Inter display with Fraunces body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-bodoni-moda', 'Inter + Bodoni Moda', fontRef('inter'), fontRef('bodoni-moda'), undefined, 'Tech', 'Inter display with Bodoni Moda body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-spectral', 'Inter + Spectral', fontRef('inter'), fontRef('spectral'), undefined, 'Minimal', 'Inter display with Spectral body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-cinzel', 'Inter + Cinzel', fontRef('inter'), fontRef('cinzel'), undefined, 'Wellness', 'Inter display with Cinzel body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-domine', 'Inter + Domine', fontRef('inter'), fontRef('domine'), undefined, 'Medical', 'Inter display with Domine body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-vollkorn', 'Inter + Vollkorn', fontRef('inter'), fontRef('vollkorn'), undefined, 'Fashion', 'Inter display with Vollkorn body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-newsreader', 'Inter + Newsreader', fontRef('inter'), fontRef('newsreader'), undefined, 'Architecture', 'Inter display with Newsreader body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-zilla-slab', 'Inter + Zilla Slab', fontRef('inter'), fontRef('zilla-slab'), undefined, 'Restaurant', 'Inter display with Zilla Slab body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-besley', 'Inter + Besley', fontRef('inter'), fontRef('besley'), undefined, 'Portfolio', 'Inter display with Besley body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-roboto-slab', 'Inter + Roboto Slab', fontRef('inter'), fontRef('roboto-slab'), undefined, 'SaaS', 'Inter display with Roboto Slab body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-oswald', 'Inter + Oswald', fontRef('inter'), fontRef('oswald'), undefined, 'Brutalist', 'Inter display with Oswald body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-bebas-neue', 'Inter + Bebas Neue', fontRef('inter'), fontRef('bebas-neue'), undefined, 'Modern', 'Inter display with Bebas Neue body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
  createPairing('pair-inter-anton', 'Inter + Anton', fontRef('inter'), fontRef('anton'), undefined, 'Luxury', 'Inter display with Anton body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-abril-fatface', 'Inter + Abril Fatface', fontRef('inter'), fontRef('abril-fatface'), undefined, 'Editorial', 'Inter display with Abril Fatface body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-unbounded', 'Inter + Unbounded', fontRef('inter'), fontRef('unbounded'), undefined, 'Corporate', 'Inter display with Unbounded body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-clash-display', 'Inter + Clash Display', fontRef('inter'), fontRef('clash-display'), undefined, 'Creative', 'Inter display with Clash Display body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-righteous', 'Inter + Righteous', fontRef('inter'), fontRef('righteous'), undefined, 'Tech', 'Inter display with Righteous body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-lobster', 'Inter + Lobster', fontRef('inter'), fontRef('lobster'), undefined, 'Minimal', 'Inter display with Lobster body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-permanent-marker', 'Inter + Permanent Marker', fontRef('inter'), fontRef('permanent-marker'), undefined, 'Wellness', 'Inter display with Permanent Marker body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-russo-one', 'Inter + Russo One', fontRef('inter'), fontRef('russo-one'), undefined, 'Medical', 'Inter display with Russo One body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-space-mono', 'Inter + Space Mono', fontRef('inter'), fontRef('space-mono'), undefined, 'Fashion', 'Inter display with Space Mono body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-fira-code', 'Inter + Fira Code', fontRef('inter'), fontRef('fira-code'), undefined, 'Architecture', 'Inter display with Fira Code body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-jetbrains-mono', 'Inter + JetBrains Mono', fontRef('inter'), fontRef('jetbrains-mono'), undefined, 'Restaurant', 'Inter display with JetBrains Mono body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-source-code-pro', 'Inter + Source Code Pro', fontRef('inter'), fontRef('source-code-pro'), undefined, 'Portfolio', 'Inter display with Source Code Pro body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-ibm-plex-mono', 'Inter + IBM Plex Mono', fontRef('inter'), fontRef('ibm-plex-mono'), undefined, 'SaaS', 'Inter display with IBM Plex Mono body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-dancing-script', 'Inter + Dancing Script', fontRef('inter'), fontRef('dancing-script'), undefined, 'Brutalist', 'Inter display with Dancing Script body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-pacifico', 'Inter + Pacifico', fontRef('inter'), fontRef('pacifico'), undefined, 'Modern', 'Inter display with Pacifico body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
  createPairing('pair-inter-caveat', 'Inter + Caveat', fontRef('inter'), fontRef('caveat'), undefined, 'Luxury', 'Inter display with Caveat body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-great-vibes', 'Inter + Great Vibes', fontRef('inter'), fontRef('great-vibes'), undefined, 'Editorial', 'Inter display with Great Vibes body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-satisfy', 'Inter + Satisfy', fontRef('inter'), fontRef('satisfy'), undefined, 'Corporate', 'Inter display with Satisfy body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-sacramento', 'Inter + Sacramento', fontRef('inter'), fontRef('sacramento'), undefined, 'Creative', 'Inter display with Sacramento body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-kalam', 'Inter + Kalam', fontRef('inter'), fontRef('kalam'), undefined, 'Tech', 'Inter display with Kalam body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-marck-script', 'Inter + Marck Script', fontRef('inter'), fontRef('marck-script'), undefined, 'Minimal', 'Inter display with Marck Script body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-courgette', 'Inter + Courgette', fontRef('inter'), fontRef('courgette'), undefined, 'Wellness', 'Inter display with Courgette body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-didot', 'Inter + Didot', fontRef('inter'), fontRef('didot'), undefined, 'Medical', 'Inter display with Didot body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-bodoni', 'Inter + Bodoni', fontRef('inter'), fontRef('bodoni'), undefined, 'Fashion', 'Inter display with Bodoni body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-exo-2', 'Inter + Exo 2', fontRef('inter'), fontRef('exo-2'), undefined, 'Architecture', 'Inter display with Exo 2 body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-orbitron', 'Inter + Orbitron', fontRef('inter'), fontRef('orbitron'), undefined, 'Restaurant', 'Inter display with Orbitron body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-rajdhani', 'Inter + Rajdhani', fontRef('inter'), fontRef('rajdhani'), undefined, 'Portfolio', 'Inter display with Rajdhani body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-chakra-petch', 'Inter + Chakra Petch', fontRef('inter'), fontRef('chakra-petch'), undefined, 'SaaS', 'Inter display with Chakra Petch body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-noto-serif', 'Inter + Noto Serif', fontRef('inter'), fontRef('noto-serif'), undefined, 'Brutalist', 'Inter display with Noto Serif body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-share-tech-mono', 'Inter + Share Tech Mono', fontRef('inter'), fontRef('share-tech-mono'), undefined, 'Modern', 'Inter display with Share Tech Mono body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
  createPairing('pair-inter-cutive-mono', 'Inter + Cutive Mono', fontRef('inter'), fontRef('cutive-mono'), undefined, 'Luxury', 'Inter display with Cutive Mono body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['luxury']),
  createPairing('pair-inter-press-start-2p', 'Inter + Press Start 2P', fontRef('inter'), fontRef('press-start-2p'), undefined, 'Editorial', 'Inter display with Press Start 2P body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['editorial']),
  createPairing('pair-inter-pt-serif', 'Inter + PT Serif', fontRef('inter'), fontRef('pt-serif'), undefined, 'Corporate', 'Inter display with PT Serif body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['corporate']),
  createPairing('pair-inter-bitter', 'Inter + Bitter', fontRef('inter'), fontRef('bitter'), undefined, 'Creative', 'Inter display with Bitter body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['creative']),
  createPairing('pair-inter-old-standard-tt', 'Inter + Old Standard TT', fontRef('inter'), fontRef('old-standard-tt'), undefined, 'Tech', 'Inter display with Old Standard TT body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['tech']),
  createPairing('pair-inter-marcellus', 'Inter + Marcellus', fontRef('inter'), fontRef('marcellus'), undefined, 'Minimal', 'Inter display with Marcellus body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['minimal']),
  createPairing('pair-inter-prata', 'Inter + Prata', fontRef('inter'), fontRef('prata'), undefined, 'Wellness', 'Inter display with Prata body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['wellness']),
  createPairing('pair-inter-dm-serif-display', 'Inter + DM Serif Display', fontRef('inter'), fontRef('dm-serif-display'), undefined, 'Medical', 'Inter display with DM Serif Display body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['medical']),
  createPairing('pair-inter-castoro', 'Inter + Castoro', fontRef('inter'), fontRef('castoro'), undefined, 'Fashion', 'Inter display with Castoro body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['fashion']),
  createPairing('pair-inter-albert-sans', 'Inter + Albert Sans', fontRef('inter'), fontRef('albert-sans'), undefined, 'Architecture', 'Inter display with Albert Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['architecture']),
  createPairing('pair-inter-bricolage-grotesque', 'Inter + Bricolage Grotesque', fontRef('inter'), fontRef('bricolage-grotesque'), undefined, 'Restaurant', 'Inter display with Bricolage Grotesque body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['restaurant']),
  createPairing('pair-inter-schibsted-grotesk', 'Inter + Schibsted Grotesk', fontRef('inter'), fontRef('schibsted-grotesk'), undefined, 'Portfolio', 'Inter display with Schibsted Grotesk body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['portfolio']),
  createPairing('pair-inter-be-vietnam-pro', 'Inter + Be Vietnam Pro', fontRef('inter'), fontRef('be-vietnam-pro'), undefined, 'SaaS', 'Inter display with Be Vietnam Pro body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['saas']),
  createPairing('pair-inter-instrument-sans', 'Inter + Instrument Sans', fontRef('inter'), fontRef('instrument-sans'), undefined, 'Brutalist', 'Inter display with Instrument Sans body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['brutalist']),
  createPairing('pair-inter-urbanist', 'Inter + Urbanist', fontRef('inter'), fontRef('urbanist'), undefined, 'Modern', 'Inter display with Urbanist body', ['technology','creative','corporate'], ['web','branding'], ['luxury'], ['modern']),
];
export const fullFontPairings: FontPairing[] = [...fontPairings, ...additionalPairings];
