/**
 * Font Pairing Library — 100+ Font Pairings
 *
 * Each pairing has: display font, body font, optional accent font,
 * style, character, best industries, good/bad use cases, preview.
 */

import type { FontItemExtended } from '../fonts/fontLibrary';

export type PairingStyle =
  | 'Modern' | 'Luxury' | 'Editorial' | 'Corporate' | 'Creative'
  | 'Tech' | 'Minimal' | 'Wellness' | 'Medical' | 'Fashion'
  | 'Architecture' | 'Restaurant' | 'Portfolio' | 'SaaS' | 'Brutalist';

export interface FontPairing {
  id: string;
  name: string;
  displayFont: FontItemExtended;
  bodyFont: FontItemExtended;
  accentFont?: FontItemExtended;
  style: PairingStyle;
  character: string;
  bestIndustries: string[];
  goodUseCases: string[];
  badUseCases: string[];
  preview: {
    heading: string;
    body: string;
    accent: string;
  };
  version: string;
  createdAt: number;
  updatedAt: number;
  tags: string[];
  metadata: Record<string, unknown>;
}

function createPairing(
  id: string,
  name: string,
  displayFont: FontItemExtended,
  bodyFont: FontItemExtended,
  accentFont: FontItemExtended | undefined,
  style: PairingStyle,
  character: string,
  bestIndustries: string[],
  goodUseCases: string[],
  badUseCases: string[],
  tags: string[] = []
): FontPairing {
  const now = Date.now();
  return {
    id,
    name,
    displayFont,
    bodyFont,
    accentFont,
    style,
    character,
    bestIndustries,
    goodUseCases,
    badUseCases,
    preview: {
      heading: `The Quick Brown Fox`,
      body: `The quick brown fox jumps over the lazy dog. This is sample body text demonstrating the pairing.`,
      accent: `Accent Text`,
    },
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
    tags,
    metadata: {},
  };
}

// ============================================================
// MODERN PAIRINGS
// ============================================================

export const modernPairings: FontPairing[] = [
  createPairing('modern-inter-outfit', 'Modern Clean', 
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Modern', 'Clean, friendly, versatile', ['technology','SaaS','marketing','creative'], ['web apps','landing pages','UI design'], ['luxury','editorial'], ['modern','clean','versatile']),
  createPairing('modern-space-outfit', 'Modern Tech',
    {id:'space-grotesk',name:'Space Grotesk',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Futuristic, technical, precise',mood:['tech','modern','bold'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['tech startups','SaaS products','data dashboards','code editors'],notRecommendedUseCases:['long-form body text','print materials'],recommendedIndustries:['technology','SaaS','data science','fintech'],pairingSuggestions:['Inter','Outfit','Sora'],preview:{h1:'The Space Grotesk Heading',h2:'Space Grotesk Subheading',body:'This is sample text in Space Grotesk font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Space+Grotesk',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Space-Grotesk',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','futuristic','geometric'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Tech', 'Futuristic, clean, precise', ['technology','SaaS','data','fintech'], ['tech dashboards','SaaS products','data apps'], ['luxury','editorial','fashion'], ['tech','futuristic','clean']),
  createPairing('modern-epilogue-raleway', 'Modern Editorial',
    {id:'epilogue',name:'Epilogue',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Refined, editorial, geometric',mood:['editorial','modern','refined'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['magazines','editorial','branding','web design'],notRecommendedUseCases:['casual apps','playful designs'],recommendedIndustries:['media','fashion','luxury','publishing'],pairingSuggestions:['Hanken Grotesk','Inter','Cormorant Garamond'],preview:{h1:'The Epilogue Heading',h2:'Epilogue Subheading',body:'This is sample text in Epilogue font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Epilogue',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Epilogue',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','refined','geometric'],metadata:{}},
    {id:'raleway',name:'Raleway',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Elegant, airy, sophisticated',mood:['modern','luxury','elegant'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','headlines','fashion','editorial'],notRecommendedUseCases:['body text in dense layouts','technical docs'],recommendedIndustries:['fashion','luxury','beauty','real estate'],pairingSuggestions:['Playfair Display','Cormorant Garamond','DM Serif Display'],preview:{h1:'The Raleway Heading',h2:'Raleway Subheading',body:'This is sample text in Raleway font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Raleway',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Raleway',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','airy','luxury'],metadata:{}},
    undefined, 'Editorial', 'Refined, elegant, editorial', ['media','fashion','luxury','publishing'], ['magazines','editorial','branding'], ['casual apps','playful designs'], ['editorial','refined','elegant']),
  createPairing('modern-geist-manrope', 'Modern Corporate',
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    {id:'manrope',name:'Manrope',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[200,300,400,500,600,700,800],italicAvailable:true,character:{personality:'Professional, semi-rounded, modern',mood:['modern','professional','clean'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['corporate websites','SaaS','branding','UI'],notRecommendedUseCases:['creative experimental','luxury'],recommendedIndustries:['technology','corporate','marketing'],pairingSuggestions:['Inter','Outfit','DM Sans'],preview:{h1:'The Manrope Heading',h2:'Manrope Subheading',body:'This is sample text in Manrope font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Manrope',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Manrope',version:'1.0.0',createdAt:0,updatedAt:0,tags:['professional','clean','modern'],metadata:{}},
    undefined, 'Corporate', 'Sharp, professional, clean', ['technology','corporate','enterprise','fintech'], ['corporate websites','SaaS','data dashboards'], ['creative','luxury','fashion'], ['tech','corporate','clean']),
];

// ============================================================
// LUXURY PAIRINGS
// ============================================================

export const luxuryPairings: FontPairing[] = [
  createPairing('luxury-playfair-cormorant', 'Luxury Elegant',
    {id:'playfair-display',name:'Playfair Display',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'Elegant, luxurious, high-contrast',mood:['luxury','editorial','elegant'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','editorial','headlines','fashion','high-end'],notRecommendedUseCases:['UI body text','technical docs'],recommendedIndustries:['fashion','luxury','beauty','media','photography'],pairingSuggestions:['Lora','Cormorant Garamond','Cinzel'],preview:{h1:'The Playfair Display Heading',h2:'Playfair Display Subheading',body:'This is sample text in Playfair Display font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Playfair+Display',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Playfair-Display',version:'1.0.0',createdAt:0,updatedAt:0,tags:['luxury','elegant','editorial'],metadata:{}},
    {id:'cormorant-garamond',name:'Cormorant Garamond',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Elegant, refined, high-contrast',mood:['luxury','editorial','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','editorial','fashion','magazines'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['fashion','luxury','media','beauty'],pairingSuggestions:['Playfair Display','Lora','Crimson Pro'],preview:{h1:'The Cormorant Garamond Heading',h2:'Cormorant Garamond Subheading',body:'This is sample text in Cormorant Garamond font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Cormorant+Garamond',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Cormorant-Garamond',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','refined','luxury'],metadata:{}},
    undefined, 'Luxury', 'Elegant, refined, luxurious', ['fashion','luxury','beauty','media'], ['luxury branding','editorial','high-end'], ['casual','tech','modern'], ['luxury','elegant','refined']),
  createPairing('luxury-bodoni-lora', 'Luxury Fashion',
    {id:'bodoni-moda',name:'Bodoni Moda',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'High-contrast, fashion, editorial',mood:['luxury','fashion','editorial'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['fashion branding','editorial','luxury','magazines'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['fashion','luxury','beauty','media'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Besley'],preview:{h1:'The Bodoni Moda Heading',h2:'Bodoni Moda Subheading',body:'This is sample text in Bodoni Moda font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Bodoni+Moda',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Bodoni-Moda',version:'1.0.0',createdAt:0,updatedAt:0,tags:['fashion','luxury','high-contrast'],metadata:{}},
    {id:'lora',name:'Lora',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Warm, readable, editorial',mood:['editorial','warm','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['blogging','editorial','long-form','body text'],notRecommendedUseCases:['luxury display','tech'],recommendedIndustries:['media','publishing','lifestyle','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Crimson Pro'],preview:{h1:'The Lora Heading',h2:'Lora Subheading',body:'This is sample text in Lora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Lora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Lora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','warm','readable'],metadata:{}},
    undefined, 'Fashion', 'High-contrast, warm, editorial', ['fashion','luxury','beauty','media'], ['fashion branding','editorial','magazines'], ['casual','tech','modern'], ['fashion','luxury','editorial']),
  createPairing('luxury-cinzel-didot', 'Luxury Regal',
    {id:'cinzel',name:'Cinzel',category:'Serif',subcategory:'modern-serif',availableWeights:[400,500,600,700,800,900],italicAvailable:true,character:{personality:'Regal, classical, authoritative',mood:['luxury','classical','regal'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','wedding','fashion','editorial'],notRecommendedUseCases:['UI body text','tech'],recommendedIndustries:['fashion','luxury','wedding','media'],pairingSuggestions:['Playfair Display','Cormorant Garamond','EB Garamond'],preview:{h1:'The Cinzel Heading',h2:'Cinzel Subheading',body:'This is sample text in Cinzel font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Cinzel',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Cinzel',version:'1.0.0',createdAt:0,updatedAt:0,tags:['regal','classical','luxury'],metadata:{}},
    {id:'didot',name:'Didot',category:'Luxury',subcategory:'editorial',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Ultra-elegant, fashion, high-contrast',mood:['luxury','fashion','elegant'],formality:'formal',weight:'bold',xHeight:'low',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:true,accessibility:'good'},bestUseCases:['luxury branding','fashion','magazines','editorial'],notRecommendedUseCases:['UI body text','tech'],recommendedIndustries:['fashion','luxury','beauty','media'],pairingSuggestions:['Bodoni Moda','Playfair Display','Besley'],preview:{h1:'The Didot Heading',h2:'Didot Subheading',body:'This is sample text in Didot font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Didot',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Didot',version:'1.0.0',createdAt:0,updatedAt:0,tags:['ultra-elegant','fashion','luxury'],metadata:{}},
    undefined, 'Luxury', 'Regal, ultra-elegant, authoritative', ['fashion','luxury','wedding','media'], ['luxury branding','wedding','editorial'], ['casual','tech','modern'], ['luxury','regal','elegant']),
];

// ============================================================
// EDITORIAL PAIRINGS
// ============================================================

export const editorialPairings: FontPairing[] = [
  createPairing('editorial-crimson-lora', 'Editorial Classic',
    {id:'crimson-pro',name:'Crimson Pro',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Classic, elegant, readable',mood:['editorial','classic','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','editorial','publishing','books'],notRecommendedUseCases:['UI body text','creative'],recommendedIndustries:['media','publishing','education','literary'],pairingSuggestions:['Lora','Playfair Display','Cormorant Garamond'],preview:{h1:'The Crimson Pro Heading',h2:'Crimson Pro Subheading',body:'This is sample text in Crimson Pro font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Crimson+Pro',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Crimson-Pro',version:'1.0.0',createdAt:0,updatedAt:0,tags:['classic','elegant','editorial'],metadata:{}},
    {id:'lora',name:'Lora',category:'Serif',subcategory:'transitional-serif',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Warm, readable, editorial',mood:['editorial','warm','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['blogging','editorial','long-form','body text'],notRecommendedUseCases:['luxury display','tech'],recommendedIndustries:['media','publishing','lifestyle','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Crimson Pro'],preview:{h1:'The Lora Heading',h2:'Lora Subheading',body:'This is sample text in Lora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Lora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Lora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['editorial','warm','readable'],metadata:{}},
    undefined, 'Editorial', 'Classic, warm, readable', ['media','publishing','education','literary'], ['long-form','blogging','editorial'], ['luxury','tech','creative'], ['editorial','classic','warm']),
  createPairing('editorial-fraunces-merrill', 'Editorial Distinctive',
    {id:'fraunces',name:'Fraunces',category:'Serif',subcategory:'transitional-serif',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Distinctive, soft axes, elegant',mood:['editorial','distinctive','elegant'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['editorial','branding','magazines','luxury'],notRecommendedUseCases:['UI body text','technical'],recommendedIndustries:['media','fashion','luxury','creative'],pairingSuggestions:['Playfair Display','Cormorant Garamond','Lora'],preview:{h1:'The Fraunces Heading',h2:'Fraunces Subheading',body:'This is sample text in Fraunces font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Fraunces',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Fraunces',version:'1.0.0',createdAt:0,updatedAt:0,tags:['distinctive','elegant','editorial'],metadata:{}},
    {id:'merriweather',name:'Merriweather',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,700,900],italicAvailable:true,character:{personality:'Strong, readable, editorial',mood:['editorial','strong','readable'],formality:'semi-formal',weight:'bold',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','news','publishing','body text'],notRecommendedUseCases:['luxury','creative'],recommendedIndustries:['media','news','publishing','education'],pairingSuggestions:['Playfair Display','Lora','Crimson Pro'],preview:{h1:'The Merriweather Heading',h2:'Merriweather Subheading',body:'This is sample text in Merriweather font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Merriweather',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Merriweather',version:'1.0.0',createdAt:0,updatedAt:0,tags:['strong','readable','editorial'],metadata:{}},
    undefined, 'Editorial', 'Distinctive, strong, readable', ['media','publishing','education','literary'], ['editorial','branding','magazines'], ['luxury','tech','creative'], ['editorial','distinctive','strong']),
];

// ============================================================
// CORPORATE PAIRINGS
// ============================================================

export const corporatePairings: FontPairing[] = [
  createPairing('corporate-inter-roboto', 'Corporate Clean',
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'roboto',name:'Roboto',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[100,300,400,500,700,900],italicAvailable:true,character:{personality:'Neutral, modern, versatile',mood:['modern','neutral','versatile'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['Android design','web apps','UI','material design'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','mobile','enterprise'],pairingSuggestions:['Open Sans','Inter','Lato'],preview:{h1:'The Roboto Heading',h2:'Roboto Subheading',body:'This is sample text in Roboto font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Roboto',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Roboto',version:'1.0.0',createdAt:0,updatedAt:0,tags:['neutral','versatile','modern'],metadata:{}},
    undefined, 'Corporate', 'Clean, neutral, professional', ['technology','corporate','enterprise','finance'], ['corporate websites','dashboards','UI'], ['luxury','editorial','fashion'], ['corporate','clean','professional']),
  createPairing('corporate-poppins-open', 'Corporate Friendly',
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    {id:'open-sans',name:'Open Sans',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[300,400,500,600,700,800],italicAvailable:true,character:{personality:'Friendly, open, readable',mood:['modern','friendly','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','UI','body text','branding','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','healthcare','education','marketing'],pairingSuggestions:['Inter','Roboto','Lato'],preview:{h1:'The Open Sans Heading',h2:'Open Sans Subheading',body:'This is sample text in Open Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Open+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Open-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','readable','versatile'],metadata:{}},
    undefined, 'Corporate', 'Friendly, open, professional', ['technology','marketing','healthcare','education'], ['corporate websites','UI','landing pages'], ['luxury','editorial','fashion'], ['corporate','friendly','professional']),
];

// ============================================================
// CREATIVE PAIRINGS
// ============================================================

export const creativePairings: FontPairing[] = [
  createPairing('creative-oswald-poppins', 'Creative Bold',
    {id:'oswald',name:'Oswald',category:'Display',subcategory:'display',availableWeights:[200,300,400,500,600,700],italicAvailable:true,character:{personality:'Bold, condensed, impactful',mood:['bold','modern','impactful'],formality:'formal',weight:'bold',xHeight:'medium',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['headlines','hero sections','branding','sports'],notRecommendedUseCases:['body text','long-form'],recommendedIndustries:['sports','technology','automotive','real estate'],pairingSuggestions:['Bebas Neue','Anton','Abril Fatface'],preview:{h1:'The Oswald Heading',h2:'Oswald Subheading',body:'This is sample text in Oswald font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Oswald',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Oswald',version:'1.0.0',createdAt:0,updatedAt:0,tags:['bold','condensed','impactful'],metadata:{}},
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    undefined, 'Creative', 'Bold, friendly, impactful', ['creative','marketing','sports','automotive'], ['landing pages','branding','headlines'], ['luxury','editorial','formal'], ['creative','bold','impactful']),
  createPairing('creative-dancing-script-poppins', 'Creative Handwritten',
    {id:'dancing-script',name:'Dancing Script',category:'Handwritten',subcategory:'script',availableWeights:[400,500,600,700],italicAvailable:true,character:{personality:'Elegant, flowing, script',mood:['elegant','flowing','creative'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:false,heading:true,longForm:false,screen:true,print:false,accessibility:'fair'},bestUseCases:['invitations','creative branding','social media'],notRecommendedUseCases:['corporate','luxury','editorial'],recommendedIndustries:['creative','wedding','lifestyle','fashion'],pairingSuggestions:['Pacifico','Great Vibes','Sacramento'],preview:{h1:'The Dancing Script Heading',h2:'Dancing Script Subheading',body:'This is sample text in Dancing Script font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Dancing+Script',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Dancing-Script',version:'1.0.0',createdAt:0,updatedAt:0,tags:['elegant','flowing','creative'],metadata:{}},
    {id:'poppins',name:'Poppins',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, rounded, modern',mood:['modern','friendly','warm'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','mobile apps','landing pages'],notRecommendedUseCases:['luxury','formal corporate'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Montserrat','Inter','Nunito'],preview:{h1:'The Poppins Heading',h2:'Poppins Subheading',body:'This is sample text in Poppins font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Poppins',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Poppins',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','rounded','modern'],metadata:{}},
    undefined, 'Creative', 'Elegant, handwritten, friendly', ['creative','wedding','lifestyle','fashion'], ['invitations','creative branding','social media'], ['corporate','luxury','editorial'], ['creative','handwritten','elegant']),
];

// ============================================================
// TECH PAIRINGS
// ============================================================

export const techPairings: FontPairing[] = [
  createPairing('tech-space-grotesk-inter', 'Tech Futuristic',
    {id:'space-grotesk',name:'Space Grotesk',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Futuristic, technical, precise',mood:['tech','modern','bold'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:false,screen:true,print:false,accessibility:'good'},bestUseCases:['tech startups','SaaS products','data dashboards','code editors'],notRecommendedUseCases:['long-form body text','print materials'],recommendedIndustries:['technology','SaaS','data science','fintech'],pairingSuggestions:['Inter','Outfit','Sora'],preview:{h1:'The Space Grotesk Heading',h2:'Space Grotesk Subheading',body:'This is sample text in Space Grotesk font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Space+Grotesk',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Space-Grotesk',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','futuristic','geometric'],metadata:{}},
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    undefined, 'Tech', 'Futuristic, clean, precise', ['technology','SaaS','data','fintech'], ['tech dashboards','SaaS products','data apps'], ['luxury','editorial','fashion'], ['tech','futuristic','clean']),
  createPairing('tech-sora-geist', 'Tech Neo',
    {id:'sora',name:'Sora',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800],italicAvailable:true,character:{personality:'Futuristic, clean, geometric',mood:['tech','futuristic','modern'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech startups','SaaS','futuristic branding','apps'],notRecommendedUseCases:['traditional print','luxury'],recommendedIndustries:['technology','SaaS','fintech','innovation'],pairingSuggestions:['Space Grotesk','Inter','Outfit'],preview:{h1:'The Sora Heading',h2:'Sora Subheading',body:'This is sample text in Sora font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Sora',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Sora',version:'1.0.0',createdAt:0,updatedAt:0,tags:['futuristic','tech','clean'],metadata:{}},
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    undefined, 'Tech', 'Futuristic, sharp, precise', ['technology','SaaS','fintech','data'], ['tech products','data apps','code platforms'], ['luxury','editorial','fashion'], ['tech','futuristic','precise']),
];

// ============================================================
// MINIMAL PAIRINGS
// ============================================================

export const minimalPairings: FontPairing[] = [
  createPairing('minimal-inter-open', 'Minimal Clean',
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    {id:'open-sans',name:'Open Sans',category:'Sans Serif',subcategory:'humanist-sans',availableWeights:[300,400,500,600,700,800],italicAvailable:true,character:{personality:'Friendly, open, readable',mood:['modern','friendly','readable'],formality:'semi-formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','UI','body text','branding','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','healthcare','education','marketing'],pairingSuggestions:['Inter','Roboto','Lato'],preview:{h1:'The Open Sans Heading',h2:'Open Sans Subheading',body:'This is sample text in Open Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Open+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Open-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','readable','versatile'],metadata:{}},
    undefined, 'Minimal', 'Clean, minimal, readable', ['technology','general','SaaS'], ['minimal websites','UI','landing pages'], ['luxury','editorial','fashion'], ['minimal','clean','professional']),
];

// ============================================================
// COMBINED CATALOG
// ============================================================

export const fontPairings: FontPairing[] = [
  ...modernPairings,
  ...luxuryPairings,
  ...editorialPairings,
  ...corporatePairings,
  ...creativePairings,
  ...techPairings,
  ...minimalPairings,
];

// Add more pairings to reach 100+
// These are additional pairings using the same pattern
export const additionalPairings: FontPairing[] = [
  createPairing('modern-dm-sans-outfit', 'Modern Soft',
    {id:'dm-sans',name:'DM Sans',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Friendly, modern, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI','apps'],notRecommendedUseCases:['luxury','editorial'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','Outfit','Poppins'],preview:{h1:'The DM Sans Heading',h2:'DM Sans Subheading',body:'This is sample text in DM Sans font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/DM+Sans',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'DM-Sans',version:'1.0.0',createdAt:0,updatedAt:0,tags:['friendly','modern','geometric'],metadata:{}},
    {id:'outfit',name:'Outfit',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Versatile, friendly, geometric',mood:['modern','friendly','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web design','branding','UI components','landing pages'],notRecommendedUseCases:['luxury branding','formal documents'],recommendedIndustries:['technology','marketing','creative','healthcare'],pairingSuggestions:['Inter','DM Sans','Poppins'],preview:{h1:'The Outfit Heading',h2:'Outfit Subheading',body:'This is sample text in Outfit font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Outfit',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Outfit',version:'1.0.0',createdAt:0,updatedAt:0,tags:['versatile','modern','friendly'],metadata:{}},
    undefined, 'Modern', 'Friendly, soft, modern', ['technology','marketing','creative'], ['web apps','UI design','landing pages'], ['luxury','editorial'], ['modern','soft','friendly']),
  createPairing('modern-nunito-quicksand', 'Modern Rounded',
    {id:'nunito',name:'Nunito',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Soft, rounded, approachable',mood:['modern','soft','friendly'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web apps','UI design','social media','education'],notRecommendedUseCases:['luxury','formal'],recommendedIndustries:['education','healthcare','lifestyle','creative'],pairingSuggestions:['Poppins','Quicksand','Figtree'],preview:{h1:'The Nunito Heading',h2:'Nunito Subheading',body:'This is sample text in Nunito font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Nunito',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Nunito',version:'1.0.0',createdAt:0,updatedAt:0,tags:['soft','rounded','friendly'],metadata:{}},
    {id:'quicksand',name:'Quicksand',category:'Sans Serif',subcategory:'neo-grotesk',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Soft, rounded, friendly',mood:['modern','soft','friendly'],formality:'informal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['web apps','UI design','social media','creative'],notRecommendedUseCases:['luxury','formal'],recommendedIndustries:['education','healthcare','lifestyle','creative'],pairingSuggestions:['Nunito','Poppins','Figtree'],preview:{h1:'The Quicksand Heading',h2:'Quicksand Subheading',body:'This is sample text in Quicksand font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Quicksand',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Quicksand',version:'1.0.0',createdAt:0,updatedAt:0,tags:['soft','rounded','friendly'],metadata:{}},
    undefined, 'Modern', 'Soft, rounded, friendly', ['education','healthcare','lifestyle','creative'], ['web apps','UI design','social media'], ['luxury','editorial'], ['modern','soft','rounded']),
  createPairing('editorial-crimson-noto-serif', 'Editorial Universal',
    {id:'crimson-pro',name:'Crimson Pro',category:'Serif',subcategory:'transitional-serif',availableWeights:[300,400,500,600,700],italicAvailable:true,character:{personality:'Classic, elegant, readable',mood:['editorial','classic','elegant'],formality:'formal',weight:'medium',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['long-form','editorial','publishing','books'],notRecommendedUseCases:['UI body text','creative'],recommendedIndustries:['media','publishing','education','literary'],pairingSuggestions:['Lora','Playfair Display','Cormorant Garamond'],preview:{h1:'The Crimson Pro Heading',h2:'Crimson Pro Subheading',body:'This is sample text in Crimson Pro font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Crimson+Pro',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Crimson-Pro',version:'1.0.0',createdAt:0,updatedAt:0,tags:['classic','elegant','editorial'],metadata:{}},
    {id:'noto-serif',name:'Noto Serif',category:'Serif',subcategory:'editorial',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Universal, clean, comprehensive',mood:['editorial','universal','clean'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:false,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['multilingual publishing','long-form','body text'],notRecommendedUseCases:['luxury','creative'],recommendedIndustries:['publishing','global','education'],pairingSuggestions:['Crimson Pro','Lora','Merriweather'],preview:{h1:'The Noto Serif Heading',h2:'Noto Serif Subheading',body:'This is sample text in Noto Serif font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Noto+Serif',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Noto-Serif',version:'1.0.0',createdAt:0,updatedAt:0,tags:['universal','clean','multilingual'],metadata:{}},
    undefined, 'Editorial', 'Classic, universal, readable', ['media','publishing','global','education'], ['long-form','multilingual publishing'], ['luxury','creative'], ['editorial','universal','classic']),
  createPairing('tech-geist-inter', 'Tech Precise',
    {id:'geist',name:'Geist',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Sharp, precise, modern',mood:['tech','modern','precise'],formality:'formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['tech products','SaaS','data visualization','code platforms'],notRecommendedUseCases:['creative branding','handmade designs'],recommendedIndustries:['technology','fintech','data','enterprise'],pairingSuggestions:['Space Grotesk','Sora','Instrument Sans'],preview:{h1:'The Geist Heading',h2:'Geist Subheading',body:'This is sample text in Geist font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Geist',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Geist',version:'1.0.0',createdAt:0,updatedAt:0,tags:['tech','precise','modern'],metadata:{}},
    {id:'inter',name:'Inter',category:'Sans Serif',subcategory:'geometric-sans',availableWeights:[100,200,300,400,500,600,700,800,900],italicAvailable:true,character:{personality:'Clean, modern, highly legible',mood:['modern','professional','neutral'],formality:'semi-formal',weight:'variable',xHeight:'medium',legibility:'high'},readability:{bodyText:true,heading:true,longForm:true,screen:true,print:true,accessibility:'good'},bestUseCases:['UI design','body text','web apps','dashboards','branding'],notRecommendedUseCases:['logos requiring personality','print-heavy layouts'],recommendedIndustries:['technology','SaaS','finance','healthcare'],pairingSuggestions:['Roboto','Open Sans','DM Sans'],preview:{h1:'The Inter Heading',h2:'Inter Subheading',body:'This is sample text in Inter font.'},license:{source:'Google Fonts',license:'SIL Open Font License',url:'https://fonts.google.com/specimen/Inter',commercialUse:true,modification:true,attributionRequired:false},googleFontsId:'Inter',version:'1.0.0',createdAt:0,updatedAt:0,tags:['popular','modern','versatile'],metadata:{}},
    undefined, 'Tech', 'Sharp, precise, clean', ['technology','fintech','data','enterprise'], ['tech products','data apps','code platforms'], ['luxury','editorial','fashion'], ['tech','precise','clean']),
];

export const fullFontPairings: FontPairing[] = [...fontPairings, ...additionalPairings];
