import { fullColorPalettes } from '../packages/design-system/src/colors/colorPalettes';
import { typographySystems } from '../packages/design-system/src/typography/typographySystems';
import { buttonSystems } from '../packages/design-system/src/buttons/buttonSystems';
import { cardSystems } from '../packages/design-system/src/cards/cardSystems';
import { radiusStyles } from '../packages/design-system/src/radius';
import { shadowStyles } from '../packages/design-system/src/shadows';
import { backgroundStyles } from '../packages/design-system/src/backgrounds';
import { spacingStyles } from '../packages/design-system/src/spacing';
import { sectionStyles } from '../packages/design-system/src/sections';
import { heroStyles } from '../packages/design-system/src/hero';
import { imageTreatmentStyles } from '../packages/design-system/src/images';
import { iconStyles } from '../packages/design-system/src/icons';
import { effectStyles } from '../packages/design-system/src/effects';
import { fullFontCatalog } from '../packages/design-system/src/fonts/fontLibrary';
import { industryPresets } from '../packages/design-system/src/industries';

const ids = (a: any[]) => a.map(x => x.id);
console.log('palettes', fullColorPalettes.length, JSON.stringify(ids(fullColorPalettes)));
console.log('typography', typographySystems.length, JSON.stringify(ids(typographySystems)));
console.log('buttons', buttonSystems.length, JSON.stringify(ids(buttonSystems)));
console.log('cards', cardSystems.length, JSON.stringify(ids(cardSystems)));
console.log('radius', radiusStyles.length, JSON.stringify(ids(radiusStyles)));
console.log('shadows', shadowStyles.length, JSON.stringify(ids(shadowStyles)));
console.log('bg', backgroundStyles.length, JSON.stringify(ids(backgroundStyles)));
console.log('spacing', spacingStyles.length, JSON.stringify(ids(spacingStyles)));
console.log('sections', sectionStyles.length, JSON.stringify(ids(sectionStyles)));
console.log('hero', heroStyles.length, JSON.stringify(ids(heroStyles)));
console.log('images', imageTreatmentStyles.length, JSON.stringify(ids(imageTreatmentStyles)));
console.log('icons', iconStyles.length, JSON.stringify(ids(iconStyles)));
console.log('effects', effectStyles.length, JSON.stringify(ids(effectStyles)));
console.log('fonts', fullFontCatalog.length);
console.log('industries', industryPresets.map(p => p.industry).join(','));
console.log('fontSample', JSON.stringify(fullFontCatalog.slice(0, 15).map(f => f.id)));
