/**
 * TemplateContentProfiles.ts
 *
 * Defines semantic Content Profiles for each website template in SoloSpot.
 * Each profile maps a template to its target industry, visual style, mood,
 * allowed asset categories, preferred keywords, and curated hero assets.
 */

import type {
  VisualAssetCategory,
  VisualAssetMood,
  VisualAssetStyle,
} from './AssetTypes';

export interface TemplateContentProfile {
  templateId: string;
  name: string;
  industry: string;
  primaryStyle: VisualAssetStyle;
  primaryMood: VisualAssetMood;
  paletteTheme: string;
  allowedCategories: VisualAssetCategory[];
  heroAssetId?: string;
  preferredAssetTags: string[];
  fallbackKeywords: string[];
}

export const TEMPLATE_PROFILES: Record<string, TemplateContentProfile> = {
  'modern-saas': {
    templateId: 'modern-saas',
    name: 'Modern SaaS',
    industry: 'saas',
    primaryStyle: 'futuristic',
    primaryMood: 'optimistic',
    paletteTheme: 'indigo-violet',
    allowedCategories: ['tech', 'business', 'people', 'background', '3d'],
    heroAssetId: 'ast-tec-001',
    preferredAssetTags: ['saas', 'software', 'technology', 'cloud', 'developer', 'startup'],
    fallbackKeywords: ['saas', 'software', 'code', 'dashboard', 'analytics'],
  },
  'luxury-fashion': {
    templateId: 'luxury-fashion',
    name: 'Luxury Fashion',
    industry: 'fashion',
    primaryStyle: 'luxury',
    primaryMood: 'elegant',
    paletteTheme: 'champagne-dark',
    allowedCategories: ['product', 'people', 'creative', 'background'],
    heroAssetId: 'ast-pro-014',
    preferredAssetTags: ['fashion', 'luxury', 'editorial', 'accessories', 'footwear', 'model'],
    fallbackKeywords: ['fashion', 'luxury', 'haute', 'collection', 'clothing'],
  },
  'restaurant-fine': {
    templateId: 'restaurant-fine',
    name: 'Fine Dining Restaurant',
    industry: 'restaurant',
    primaryStyle: 'luxury',
    primaryMood: 'warm',
    paletteTheme: 'burgundy-gold',
    allowedCategories: ['food', 'architecture', 'people', 'background'],
    heroAssetId: 'ast-foo-001',
    preferredAssetTags: ['gourmet', 'culinary', 'chef', 'wine', 'plating', 'dining'],
    fallbackKeywords: ['food', 'restaurant', 'gourmet', 'dining', 'culinary'],
  },
  'creative-agency': {
    templateId: 'creative-agency',
    name: 'Creative Agency',
    industry: 'creative',
    primaryStyle: 'creative',
    primaryMood: 'energetic',
    paletteTheme: 'monochrome-accent',
    allowedCategories: ['creative', 'people', 'tech', '3d', 'background'],
    heroAssetId: 'ast-cre-001',
    preferredAssetTags: ['design', 'agency', 'branding', 'creative', 'typography', 'art'],
    fallbackKeywords: ['creative', 'agency', 'design', 'portfolio', 'branding'],
  },
  'tech-startup': {
    templateId: 'tech-startup',
    name: 'Tech Startup',
    industry: 'startup',
    primaryStyle: 'technological',
    primaryMood: 'futuristic',
    paletteTheme: 'cyan-slate',
    allowedCategories: ['tech', 'business', 'video', '3d', 'people'],
    heroAssetId: 'ast-vid-001',
    preferredAssetTags: ['startup', 'ai', 'cloud', 'cybersecurity', 'engineering'],
    fallbackKeywords: ['tech', 'startup', 'innovation', 'software', 'cloud'],
  },
  'ecommerce-modern': {
    templateId: 'ecommerce-modern',
    name: 'Modern E-Commerce',
    industry: 'ecommerce',
    primaryStyle: 'minimal',
    primaryMood: 'optimistic',
    paletteTheme: 'neutral-clean',
    allowedCategories: ['product', 'people', 'creative'],
    heroAssetId: 'ast-pro-001',
    preferredAssetTags: ['ecommerce', 'product', 'electronics', 'watch', 'audio', 'gadgets'],
    fallbackKeywords: ['product', 'ecommerce', 'shopping', 'store', 'goods'],
  },
  'real-estate': {
    templateId: 'real-estate',
    name: 'Real Estate',
    industry: 'real-estate',
    primaryStyle: 'luxury',
    primaryMood: 'calm',
    paletteTheme: 'slate-gold',
    allowedCategories: ['architecture', 'people', 'background'],
    heroAssetId: 'ast-arc-001',
    preferredAssetTags: ['villa', 'residence', 'architecture', 'penthouse', 'interior', 'luxury'],
    fallbackKeywords: ['villa', 'house', 'apartment', 'architecture', 'luxury'],
  },
  'photography-portfolio': {
    templateId: 'photography-portfolio',
    name: 'Photography Portfolio',
    industry: 'photography',
    primaryStyle: 'editorial',
    primaryMood: 'dramatic',
    paletteTheme: 'monochrome-true',
    allowedCategories: ['creative', 'people', 'nature', 'travel'],
    heroAssetId: 'ast-cre-005',
    preferredAssetTags: ['photography', 'portrait', 'editorial', 'camera', 'lens', 'fine-art'],
    fallbackKeywords: ['photography', 'camera', 'visual', 'photo', 'shot'],
  },
  'digital-agency': {
    templateId: 'digital-agency',
    name: 'Digital Agency',
    industry: 'agency',
    primaryStyle: 'modern',
    primaryMood: 'energetic',
    paletteTheme: 'blue-violet',
    allowedCategories: ['business', 'tech', 'people', 'creative'],
    heroAssetId: 'ast-bus-010',
    preferredAssetTags: ['marketing', 'analytics', 'strategy', 'digital', 'consulting'],
    fallbackKeywords: ['agency', 'marketing', 'digital', 'analytics', 'growth'],
  },
  'fitness-gym': {
    templateId: 'fitness-gym',
    name: 'Fitness & Gym',
    industry: 'fitness',
    primaryStyle: 'bold',
    primaryMood: 'energetic',
    paletteTheme: 'crimson-dark',
    allowedCategories: ['people', 'product', 'background'],
    heroAssetId: 'ast-peo-036',
    preferredAssetTags: ['fitness', 'crossfit', 'workout', 'athlete', 'strength', 'training'],
    fallbackKeywords: ['fitness', 'gym', 'workout', 'training', 'exercise'],
  },
  'consulting': {
    templateId: 'consulting',
    name: 'Consulting Firm',
    industry: 'consulting',
    primaryStyle: 'corporate',
    primaryMood: 'calm',
    paletteTheme: 'navy-silver',
    allowedCategories: ['business', 'people', 'architecture'],
    heroAssetId: 'ast-bus-001',
    preferredAssetTags: ['consulting', 'strategy', 'advisory', 'executive', 'meeting'],
    fallbackKeywords: ['consulting', 'business', 'strategy', 'finance', 'corporate'],
  },
  'architecture': {
    templateId: 'architecture',
    name: 'Architecture Studio',
    industry: 'architecture',
    primaryStyle: 'minimal',
    primaryMood: 'calm',
    paletteTheme: 'stone-concrete',
    allowedCategories: ['architecture', 'product', 'creative'],
    heroAssetId: 'ast-arc-002',
    preferredAssetTags: ['brutalist', 'minimal', 'facade', 'structure', 'interior', 'geometry'],
    fallbackKeywords: ['architecture', 'building', 'structure', 'minimal', 'facade'],
  },
  'beauty-salon': {
    templateId: 'beauty-salon',
    name: 'Beauty & Salon',
    industry: 'beauty',
    primaryStyle: 'luxury',
    primaryMood: 'calm',
    paletteTheme: 'rose-cream',
    allowedCategories: ['product', 'people', 'creative'],
    heroAssetId: 'ast-pro-004',
    preferredAssetTags: ['cosmetics', 'skincare', 'wellness', 'organic', 'beauty', 'spa'],
    fallbackKeywords: ['beauty', 'skincare', 'cosmetics', 'salon', 'wellness'],
  },
  'online-course': {
    templateId: 'online-course',
    name: 'Online Course',
    industry: 'education',
    primaryStyle: 'modern',
    primaryMood: 'optimistic',
    paletteTheme: 'amber-slate',
    allowedCategories: ['people', 'tech', 'business'],
    heroAssetId: 'ast-peo-041',
    preferredAssetTags: ['education', 'learning', 'coding', 'students', 'instructor'],
    fallbackKeywords: ['course', 'education', 'learning', 'study', 'class'],
  },
  'music-artist': {
    templateId: 'music-artist',
    name: 'Music & Artist',
    industry: 'music',
    primaryStyle: 'dark',
    primaryMood: 'dramatic',
    paletteTheme: 'obsidian-purple',
    allowedCategories: ['creative', 'people', 'product', 'video'],
    heroAssetId: 'ast-vid-002',
    preferredAssetTags: ['music', 'synth', 'stage', 'concert', 'studio', 'vinyl', 'headphones'],
    fallbackKeywords: ['music', 'sound', 'audio', 'concert', 'artist'],
  },
  'law-firm': {
    templateId: 'law-firm',
    name: 'Law Firm',
    industry: 'law',
    primaryStyle: 'corporate',
    primaryMood: 'calm',
    paletteTheme: 'navy-gold',
    allowedCategories: ['business', 'people', 'architecture'],
    heroAssetId: 'ast-bus-002',
    preferredAssetTags: ['law', 'legal', 'attorney', 'courtroom', 'justice', 'corporate'],
    fallbackKeywords: ['law', 'legal', 'firm', 'attorney', 'justice'],
  },
  'construction': {
    templateId: 'construction',
    name: 'Construction Company',
    industry: 'construction',
    primaryStyle: 'bold',
    primaryMood: 'energetic',
    paletteTheme: 'amber-dark',
    allowedCategories: ['architecture', 'business', 'people'],
    heroAssetId: 'ast-arc-003',
    preferredAssetTags: ['construction', 'engineering', 'crane', 'concrete', 'infrastructure'],
    fallbackKeywords: ['construction', 'building', 'engineering', 'infrastructure', 'builder'],
  },
  'automotive': {
    templateId: 'automotive',
    name: 'Automotive Dealership',
    industry: 'automotive',
    primaryStyle: 'luxury',
    primaryMood: 'dramatic',
    paletteTheme: 'carbon-silver',
    allowedCategories: ['product', 'background', 'video'],
    heroAssetId: 'ast-vid-003',
    preferredAssetTags: ['automotive', 'vehicle', 'luxury', 'supercar', 'speed', 'design'],
    fallbackKeywords: ['car', 'automotive', 'vehicle', 'drive', 'speed'],
  },
  'local-business': {
    templateId: 'local-business',
    name: 'Local Business',
    industry: 'local-business',
    primaryStyle: 'organic',
    primaryMood: 'warm',
    paletteTheme: 'terracotta-green',
    allowedCategories: ['people', 'food', 'architecture', 'creative'],
    heroAssetId: 'ast-peo-047',
    preferredAssetTags: ['craft', 'artisan', 'community', 'handmade', 'local', 'workshop'],
    fallbackKeywords: ['local', 'store', 'shop', 'community', 'craft'],
  },
  'personal-brand': {
    templateId: 'personal-brand',
    name: 'Personal Brand',
    industry: 'personal-brand',
    primaryStyle: 'editorial',
    primaryMood: 'optimistic',
    paletteTheme: 'neutral-bold',
    allowedCategories: ['people', 'creative', 'business'],
    heroAssetId: 'ast-peo-001',
    preferredAssetTags: ['portrait', 'founder', 'author', 'speaker', 'creator', 'editorial'],
    fallbackKeywords: ['personal', 'brand', 'speaker', 'author', 'creator'],
  },
  'startup-landing': {
    templateId: 'startup-landing',
    name: 'Startup Launchpad',
    industry: 'startup',
    primaryStyle: 'futuristic',
    primaryMood: 'energetic',
    paletteTheme: 'violet-emerald',
    allowedCategories: ['tech', 'business', '3d', 'people'],
    heroAssetId: 'ast-tec-004',
    preferredAssetTags: ['startup', 'launch', 'saas', 'technology', 'innovation'],
    fallbackKeywords: ['startup', 'launch', 'app', 'product', 'tech'],
  },
  'wedding': {
    templateId: 'wedding',
    name: 'Wedding & Events',
    industry: 'events',
    primaryStyle: 'editorial',
    primaryMood: 'warm',
    paletteTheme: 'ivory-champagne',
    allowedCategories: ['people', 'creative', 'nature', 'travel'],
    heroAssetId: 'ast-peo-046',
    preferredAssetTags: ['wedding', 'celebration', 'flowers', 'love', 'ceremony', 'bride'],
    fallbackKeywords: ['wedding', 'love', 'couple', 'ceremony', 'flowers'],
  },
  'dark-saas': {
    templateId: 'dark-saas',
    name: 'Dark SaaS',
    industry: 'saas',
    primaryStyle: 'dark',
    primaryMood: 'mysterious',
    paletteTheme: 'dark-cyber',
    allowedCategories: ['tech', '3d', 'background', 'business'],
    heroAssetId: 'ast-tec-002',
    preferredAssetTags: ['cybersecurity', 'terminal', 'dark', 'code', 'neon', 'server'],
    fallbackKeywords: ['dark', 'cyber', 'security', 'terminal', 'cloud'],
  },
  'minimal-portfolio': {
    templateId: 'minimal-portfolio',
    name: 'Minimal Portfolio',
    industry: 'portfolio',
    primaryStyle: 'minimal',
    primaryMood: 'calm',
    paletteTheme: 'pure-white',
    allowedCategories: ['creative', 'architecture', 'product'],
    heroAssetId: 'ast-cre-002',
    preferredAssetTags: ['minimal', 'white', 'clean', 'grid', 'monochrome', 'poster'],
    fallbackKeywords: ['minimal', 'clean', 'portfolio', 'art', 'design'],
  },
  'saas-enterprise': {
    templateId: 'saas-enterprise',
    name: 'Enterprise SaaS',
    industry: 'enterprise',
    primaryStyle: 'corporate',
    primaryMood: 'calm',
    paletteTheme: 'slate-blue',
    allowedCategories: ['tech', 'business', 'people', 'background'],
    heroAssetId: 'ast-bus-017',
    preferredAssetTags: ['enterprise', 'datacenter', 'security', 'infrastructure', 'leadership'],
    fallbackKeywords: ['enterprise', 'b2b', 'platform', 'infrastructure', 'security'],
  },
  'organic-wellness': {
    templateId: 'organic-wellness',
    name: 'Organic Wellness',
    industry: 'wellness',
    primaryStyle: 'organic',
    primaryMood: 'calm',
    paletteTheme: 'sage-linen',
    allowedCategories: ['nature', 'product', 'people'],
    heroAssetId: 'ast-nat-001',
    preferredAssetTags: ['wellness', 'organic', 'nature', 'botanical', 'herbal', 'calm'],
    fallbackKeywords: ['wellness', 'organic', 'nature', 'spa', 'health'],
  },
  'magazine': {
    templateId: 'magazine',
    name: 'Online Magazine',
    industry: 'editorial',
    primaryStyle: 'editorial',
    primaryMood: 'optimistic',
    paletteTheme: 'classic-print',
    allowedCategories: ['creative', 'people', 'travel', 'food'],
    heroAssetId: 'ast-cre-003',
    preferredAssetTags: ['editorial', 'magazine', 'journalism', 'culture', 'stories'],
    fallbackKeywords: ['magazine', 'article', 'editorial', 'journal', 'news'],
  },
  'app-showcase': {
    templateId: 'app-showcase',
    name: 'App Showcase',
    industry: 'technology',
    primaryStyle: 'modern',
    primaryMood: 'energetic',
    paletteTheme: 'gradient-electric',
    allowedCategories: ['tech', 'product', '3d'],
    heroAssetId: 'ast-pro-042',
    preferredAssetTags: ['mobile', 'smartphone', 'ui', 'interface', 'screen', 'device'],
    fallbackKeywords: ['app', 'mobile', 'device', 'phone', 'interface'],
  },
  'cafe-bakery': {
    templateId: 'cafe-bakery',
    name: 'Cafe & Bakery',
    industry: 'cafe',
    primaryStyle: 'organic',
    primaryMood: 'warm',
    paletteTheme: 'cappuccino-wood',
    allowedCategories: ['food', 'people', 'architecture'],
    heroAssetId: 'ast-foo-004',
    preferredAssetTags: ['croissant', 'coffee', 'espresso', 'bakery', 'artisan', 'cafe'],
    fallbackKeywords: ['cafe', 'coffee', 'bakery', 'pastry', 'bread'],
  },
  // Store template profiles
  'beauty': {
    templateId: 'beauty',
    name: 'Beauty & Cosmetics Store',
    industry: 'beauty',
    primaryStyle: 'luxury',
    primaryMood: 'calm',
    paletteTheme: 'blush-gold',
    allowedCategories: ['product', 'people', 'creative'],
    heroAssetId: 'ast-pro-004',
    preferredAssetTags: ['cosmetics', 'serum', 'perfume', 'luxury', 'glow', 'beauty'],
    fallbackKeywords: ['beauty', 'cosmetics', 'serum', 'skincare', 'makeup'],
  },
  'digital': {
    templateId: 'digital',
    name: 'Digital Products Store',
    industry: 'digital',
    primaryStyle: 'futuristic',
    primaryMood: 'energetic',
    paletteTheme: 'dark-neon',
    allowedCategories: ['tech', '3d', 'creative'],
    heroAssetId: 'ast-tec-001',
    preferredAssetTags: ['code', 'presets', 'mockup', 'digital', '3d', 'mesh'],
    fallbackKeywords: ['digital', 'software', 'assets', 'templates', 'download'],
  },
  'fashionPro': {
    templateId: 'fashionPro',
    name: 'Fashion Pro Boutique',
    industry: 'fashion',
    primaryStyle: 'editorial',
    primaryMood: 'elegant',
    paletteTheme: 'noir-white',
    allowedCategories: ['product', 'people', 'creative'],
    heroAssetId: 'ast-pro-014',
    preferredAssetTags: ['fashion', 'footwear', 'bag', 'tote', 'sunglasses', 'editorial'],
    fallbackKeywords: ['fashion', 'apparel', 'shoes', 'boutique', 'couture'],
  },
  'restaurant': {
    templateId: 'restaurant',
    name: 'Gourmet Bistro',
    industry: 'restaurant',
    primaryStyle: 'organic',
    primaryMood: 'warm',
    paletteTheme: 'amber-charcoal',
    allowedCategories: ['food', 'architecture', 'people'],
    heroAssetId: 'ast-foo-001',
    preferredAssetTags: ['bistro', 'steak', 'wine', 'pasta', 'dinner', 'culinary'],
    fallbackKeywords: ['restaurant', 'bistro', 'food', 'wine', 'dining'],
  },
};

/**
 * Returns the Content Profile for a template, or constructs a sensible default.
 */
export function getTemplateContentProfile(templateId: string): TemplateContentProfile {
  if (TEMPLATE_PROFILES[templateId]) {
    return TEMPLATE_PROFILES[templateId];
  }

  // Generic fallback
  return {
    templateId,
    name: templateId,
    industry: 'general',
    primaryStyle: 'modern',
    primaryMood: 'calm',
    paletteTheme: 'neutral',
    allowedCategories: ['creative', 'business', 'people', 'background', 'product'],
    preferredAssetTags: ['modern', 'business', 'creative'],
    fallbackKeywords: ['modern', 'showcase', 'creative'],
  };
}
