import type { KnowledgeEntry } from '../types';

export const DESIGN_PRINCIPLES_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'DP-001', domain: '01-design-principles', title: 'Visual hierarchy',
    rule: 'Guide the eye with size, weight, color, and position — one primary focal point per viewport section.',
    why: 'Users scan before they read; hierarchy decides what is seen first.',
    whenToUse: 'Always — hero, section titles, card titles, CTAs.',
    whenNotToUse: 'Never skip hierarchy in dense data UIs where equal weight is intentional.',
    goodExample: 'Hero H1 (48–64px bold) > subheadline (20px) > CTA button (high contrast).',
    badExample: 'H1, H2 and body all similar size/weight — no entry point.',
    antiPattern: 'oversized-heading or flat hierarchy',
    executionHint: 'Set heading fontSize ≥ 1.6× body; CTA uses accent color + bold weight.',
    verification: 'First glance: is the headline unmistakably the dominant element?',
    relatedRules: ['DP-002', 'TY-001'], tags: ['hierarchy', 'core'],
  },
  {
    id: 'DP-002', domain: '01-design-principles', title: 'Emphasis via contrast',
    rule: 'Emphasize the primary action with contrast (color, fill vs outline), not decoration.',
    why: 'Contrast creates focus and reduces decision friction.',
    whenToUse: 'Primary CTA, active nav item, key statistic.',
    whenNotToUse: 'When everything is emphasized — nothing is.',
    goodExample: 'Solid accent “Umów wizytę” next to outline secondary button.',
    badExample: 'Two solid rainbow buttons of equal weight.',
    antiPattern: 'cta-overload',
    executionHint: 'One filled primary CTA per section; secondaries stay outline/text.',
    verification: 'Count filled CTAs per section — max 1 primary.',
    relatedRules: ['UX-001'], tags: ['contrast', 'cta', 'core'],
  },
  {
    id: 'DP-003', domain: '01-design-principles', title: 'Balance and alignment',
    rule: 'Align elements to a shared grid or axis; prefer intentional asymmetry over accidental misalignment.',
    why: 'Alignment creates order; accidental offset reads as broken layout.',
    whenToUse: 'Multi-column sections, card grids, split heroes.',
    whenNotToUse: 'Editorial intentionally staggered layouts (still align to an underlying grid).',
    goodExample: '3 feature cards equal width, equal gap, left-aligned text.',
    badExample: 'Cards with different widths and ragged left edges.',
    executionHint: 'Use CSS grid/flex with consistent gap; avoid manual margins per card.',
    verification: 'DOM rects: equal column widths; left edges align within 2px.',
    relatedRules: ['LC-001'], tags: ['alignment', 'balance', 'core'],
  },
  {
    id: 'DP-004', domain: '01-design-principles', title: 'Proximity groups related content',
    rule: 'Place related items close; separate unrelated groups with larger gaps.',
    why: 'Proximity is the cheapest grouping signal.',
    whenToUse: 'Card internals (title→body→CTA), form fields, nav items.',
    whenNotToUse: 'When distance must communicate hierarchy (hero vs next section).',
    goodExample: 'Card: title 8px above body, 16px above button; 32px between cards.',
    badExample: 'Button floating far from its card text.',
    executionHint: 'Internal padding 16–24px; gap between groups ≥ 2× internal gap.',
    verification: 'Visual: related items feel like one unit.',
    relatedRules: ['SP-001'], tags: ['proximity', 'core'],
  },
  {
    id: 'DP-005', domain: '01-design-principles', title: 'Repetition builds consistency',
    rule: 'Repeat type styles, color roles, radius, and button shapes across all sections.',
    why: 'Repetition makes the system feel designed, not assembled.',
    whenToUse: 'Whole page — one design language.',
    whenNotToUse: 'Never break mid-page without intentional design system change.',
    goodExample: 'All cards 12px radius; all primary buttons same height/padding.',
    badExample: 'Hero rounded, services square, testimonials pill-shaped.',
    antiPattern: 'inconsistent-border-radius',
    executionHint: 'Pick radius/spacing scale once; reuse via design system tokens.',
    verification: 'Sample 3 sections — same radius, button height, heading font.',
    relatedRules: ['VC-001'], tags: ['consistency', 'repetition', 'core'],
  },
  {
    id: 'DP-006', domain: '01-design-principles', title: 'Whitespace is structure',
    rule: 'Use whitespace to separate sections and breathe content — not as leftover space.',
    why: 'Whitespace reduces cognitive load and signals grouping.',
    whenToUse: 'Between sections, around headlines, inside cards.',
    whenNotToUse: 'When density is the product (dashboards, listings) — then tighten intentionally.',
    goodExample: 'Section padding 80–120px vertical on desktop; hero text has side margins.',
    badExample: 'Sections glued together or 300px voids with no content relationship.',
    antiPattern: 'insufficient-whitespace | excessive-whitespace',
    executionHint: 'Section vertical padding 64–120px desktop, 40–64px mobile.',
    verification: 'Scroll: sections feel distinct without feeling empty.',
    relatedRules: ['SP-001'], tags: ['whitespace', 'density', 'core', 'density-moderate'],
  },
  {
    id: 'DP-007', domain: '01-design-principles', title: 'Visual flow and focal points',
    rule: 'Order content so the eye moves naturally: headline → support → action.',
    why: 'Flow converts attention into action.',
    whenToUse: 'Hero, landing sections, pricing, CTA blocks.',
    whenNotToUse: 'Pure reading pages (blog) — flow is linear text.',
    goodExample: 'Z-pattern hero: logo/nav → headline left → visual right → CTA under text.',
    badExample: 'CTA above headline, decorative image blocking the message.',
    executionHint: 'DOM order should match visual order; CTA immediately after value prop.',
    verification: 'Tab order and visual order match; CTA reachable without hunting.',
    relatedRules: ['UX-001'], tags: ['flow', 'focal-point'],
  },
  {
    id: 'DP-008', domain: '01-design-principles', title: 'Simplicity and intentionality',
    rule: 'Every element must earn its place; remove decoration that does not support hierarchy or brand.',
    why: 'Visual noise competes with conversion goals.',
    whenToUse: 'Default for all marketing and service sites.',
    whenNotToUse: 'Maximalist brand directions — still keep hierarchy intact.',
    goodExample: 'Clean hero: headline, one subline, one CTA, one image.',
    badExample: 'Parallax blobs + 5 icons + gradient text + autoplay video behind copy.',
    antiPattern: 'visual-noise',
    executionHint: 'If removing an element does not hurt meaning or trust, remove it.',
    verification: 'List decorative elements — each maps to brand or hierarchy role.',
    relatedRules: ['AP-001'], tags: ['simplicity', 'core'],
  },
];
