import type { KnowledgeEntry } from '../types';

export const INFORMATION_ARCHITECTURE_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'IA-001', domain: '02-information-architecture', title: 'Structure from business, not habit',
    rule: 'Choose sections from BUSINESS + AUDIENCE + GOAL + CONTENT + INDUSTRY + USER INTENT — not a fixed Header→Hero→Services→… template.',
    why: 'A booking site and a portfolio need different IA.',
    whenToUse: 'Every new site plan.',
    whenNotToUse: 'Never hardcode one order for all briefs.',
    goodExample: 'Dental booking: navbar, hero+CTA, services, trust/testimonials, about/team, contact/booking, footer.',
    badExample: 'SaaS landing gets full restaurant menu IA.',
    executionHint: 'Map goal → required sections first; drop sections that do not serve the goal.',
    verification: 'Each section answers: which goal step does this serve?',
    relatedRules: ['IA-002', 'UX-001'], tags: ['structure', 'core'],
  },
  {
    id: 'IA-002', domain: '02-information-architecture', title: 'Section purpose contract',
    rule: 'Every section type has PURPOSE, CONTENT REQUIRED, VISUAL ROLE — fill all three or drop the section.',
    why: 'Empty or purposeless sections become orphan containers.',
    whenToUse: 'Planning any section (hero, features, about, pricing, FAQ, CTA, footer…).',
    whenNotToUse: 'Do not add gallery/testimonials if content is unavailable.',
    goodExample: 'Testimonials section only if real (or industry-plausible) quotes exist.',
    badExample: 'Pricing section with “contact for price” repeated three times and no tiers.',
    antiPattern: 'empty-containers | meaningless-galleries',
    executionHint: 'Before insert: list required content fields; soft-skip section if unfillable.',
    verification: 'No section with only placeholder or single empty heading.',
    relatedRules: ['CD-001'], tags: ['sections', 'purpose', 'core'],
  },
  {
    id: 'IA-003', domain: '02-information-architecture', title: 'Navbar and footer are mandatory frame',
    rule: 'Start with navbar (brand + nav + primary CTA) and end with footer (brand, links, contact).',
    why: 'Frame sections orient users and provide persistent conversion paths.',
    whenToUse: 'All multi-section marketing sites.',
    whenNotToUse: 'Single-purpose landing pages may slim the navbar.',
    goodExample: 'Navbar: logo, 4–5 links, “Umów wizytę” button.',
    badExample: 'Page with no navigation and no footer.',
    executionHint: 'Insert navbar as section 0; footer last; nav items match planned page sections.',
    verification: 'First and last content sections are navbar and footer.',
    relatedRules: ['IA-001'], tags: ['navbar', 'footer', 'core'],
  },
  {
    id: 'IA-004', domain: '02-information-architecture', title: 'Hero states value and next step',
    rule: 'Hero = who/what + for whom benefit + primary CTA; no vague slogans alone.',
    why: 'Hero is the 5-second pitch.',
    whenToUse: 'Top of almost every marketing page.',
    whenNotToUse: 'Internal dashboards, pure blogs may use title-only headers.',
    goodExample: '“Nowoczesna stomatologia… Umów wizytę”',
    badExample: '“Witamy na naszej stronie” with no value or CTA.',
    executionHint: 'Hero content: heading, subheading, one CTA; optional image.',
    verification: 'Hero contains benefit language + visible CTA.',
    relatedRules: ['CD-002', 'UX-001'], tags: ['hero', 'core'],
  },
  {
    id: 'IA-005', domain: '02-information-architecture', title: 'Services vs Features',
    rule: 'Services = what you do for the client (often with CTA); Features = product attributes (often for SaaS).',
    why: 'Wrong section type confuses the buyer journey.',
    whenToUse: 'Services for agencies/clinics/local; Features for products/SaaS.',
    whenNotToUse: 'Do not use feature grid for a law firm’s practice areas without service framing.',
    goodExample: 'Dental: “Implantologia”, “Ortodoncja” as services with short benefits.',
    badExample: 'Restaurant using “features grid” for menu categories without food imagery.',
    executionHint: 'Pick role: services | features; map library category accordingly.',
    verification: 'Section label matches industry language (usługi vs funkcje).',
    relatedRules: ['IA-002'], tags: ['services', 'features'],
  },
  {
    id: 'IA-006', domain: '02-information-architecture', title: 'CTA placement ladder',
    rule: 'Primary CTA appears in hero and again near decision points (after trust, before footer); footer repeats contact.',
    why: 'Users convert at different scroll depths.',
    whenToUse: 'Lead-gen, booking, ecommerce landing.',
    whenNotToUse: 'Pure content articles — soft CTA only.',
    goodExample: 'CTA in navbar, hero, mid-page block, footer.',
    badExample: 'Only footer “Send” link.',
    executionHint: 'Plan CTA locations in conversionStrategy.primaryCTALocation.',
    verification: 'Primary CTA visible at least twice without scrolling past mid-page only.',
    relatedRules: ['UX-001'], tags: ['cta', 'conversion'],
  },
];
