import type { KnowledgeEntry } from '../types';

export const LAYOUT_COMPOSITION_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'LC-001', domain: '03-layout-composition', title: 'Constrained content width',
    rule: 'Body/content max-width ~1120–1200px centered; full-bleed only for heroes/backgrounds.',
    why: 'Ultra-wide lines destroy readability and rhythm.',
    whenToUse: 'All marketing sections with text.',
    whenNotToUse: 'Immersive full-screen heroes and media walls.',
    goodExample: 'Feature grid inside 1140px container; background full width.',
    badExample: 'Text spanning 1920px edge-to-edge.',
    executionHint: 'Section inner container: max-width 1140px, margin auto, horizontal padding 24px.',
    verification: 'Line length 45–90 characters for body copy.',
    relatedRules: ['TY-003'], tags: ['container', 'max-width', 'core'],
  },
  {
    id: 'LC-002', domain: '03-layout-composition', title: 'Column count by content, not fashion',
    rule: '1 col for narrative; 2 for split hero/text-image; 3 for features/services; 4 only for 4+ equal items.',
    why: 'Random grids force uneven content and orphan cells.',
    whenToUse: 'Match column count to item count and scan pattern.',
    whenNotToUse: 'Do not use 3-col grid for 2 services (leaves hole).',
    goodExample: '4 benefits → 4 cards or 2×2; 3 services → 3 columns.',
    badExample: '2 items stretched across 4 columns with empty cells.',
    executionHint: 'grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)).',
    verification: 'No empty grid cells; equal card heights.',
    relatedRules: ['DP-003'], tags: ['grid', 'columns'],
  },
  {
    id: 'LC-003', domain: '03-layout-composition', title: 'Split vs centered hero',
    rule: 'Split hero (text | visual) for product/clinic/real-estate with strong imagery; centered for brand statements and events.',
    why: 'Layout should showcase the product’s proof (image) when one exists.',
    whenToUse: 'Split: dental, realestate, SaaS screenshots. Centered: manifesto, fundraising.',
    whenNotToUse: 'No image asset → do not force empty split.',
    goodExample: 'Dental: copy left, clinic/smile photo right.',
    badExample: 'Centered text-only hero for a photography portfolio.',
    executionHint: 'Choose hero template style: split with image slot vs centered.',
    verification: 'Hero layout matches available media and industry proof.',
    relatedRules: ['IM-001'], tags: ['hero', 'layout'],
  },
  {
    id: 'LC-004', domain: '03-layout-composition', title: 'Image/text balance in sections',
    rule: 'Alternate or balance visual weight — do not stack five text-only sections then five image-only sections without rhythm.',
    why: 'Monotone scrolls increase bounce.',
    whenToUse: 'Multi-section marketing pages.',
    whenNotToUse: 'Long-form article body.',
    goodExample: 'text-heavy → media → cards → quote → CTA.',
    badExample: 'Six identical text columns in a row.',
    executionHint: 'Plan section roles to mix: hero, features, gallery/media, testimonials, cta.',
    verification: 'Scroll sample: every other section has visual variety.',
    relatedRules: ['DP-007'], tags: ['balance', 'rhythm'],
  },
  {
    id: 'LC-005', domain: '03-layout-composition', title: 'Card layout rules',
    rule: 'Cards: consistent padding, equal structure (title, body, optional CTA/icon), consistent radius and elevation.',
    why: 'Cards are the primary repeated unit; inconsistency multiplies.',
    whenToUse: 'Features, services, pricing, team, products.',
    whenNotToUse: 'Do not card-wrap single paragraphs (use plain content section).',
    goodExample: '3 cards: icon + title + 2-line body + optional link.',
    badExample: 'Card1 has image, card2 icon, card3 nothing — same row.',
    antiPattern: 'unrelated-component-styles',
    executionHint: 'Reuse one library feature/service template for the whole grid.',
    verification: 'All cards in a row share structure and height.',
    relatedRules: ['VC-001'], tags: ['cards'],
  },
];
