import type { KnowledgeEntry } from '../types';

export const TYPOGRAPHY_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'TY-001', domain: '04-typography', title: 'Type hierarchy scale',
    rule: 'Use a small type scale: H1 40–64, H2 28–40, H3 20–24, body 16–18, small 13–14 (desktop).',
    why: 'A clear scale is the fastest hierarchy signal.',
    whenToUse: 'Every page.',
    whenNotToUse: 'Do not invent a new size per section.',
    goodExample: 'H1 56 / H2 36 / body 17 with consistent line-height.',
    badExample: 'Headings at 72, 58, 45, 40 with no system.',
    antiPattern: 'oversized-heading | no-hierarchy',
    executionHint: 'Map roles to scale steps; mobile scales ~0.85× via responsiveStrategy.',
    verification: 'Count distinct heading sizes — ideally ≤ 4 levels.',
    relatedRules: ['DP-001'], tags: ['hierarchy', 'scale', 'core'],
  },
  {
    id: 'TY-002', domain: '04-typography', title: 'Font pairing',
    rule: 'Pair one display/headline font with one readable body font (or one versatile family with weight contrast).',
    why: 'Random multi-font stacks look amateurish.',
    whenToUse: 'Brand sites wanting character (serif display + sans body).',
    whenNotToUse: 'Corporate/utility UIs — single family is fine.',
    goodExample: 'Playfair Display headlines + Inter body; or Inter 700/400 only.',
    badExample: 'Four different families across sections.',
    antiPattern: 'random-font-pairing',
    executionHint: 'designSystem.headingFont + bodyFont — set once, reuse everywhere.',
    verification: '≤ 2 font families site-wide.',
    relatedRules: ['VC-001'], tags: ['fonts', 'pairing'],
  },
  {
    id: 'TY-003', domain: '04-typography', title: 'Readable line length and line-height',
    rule: 'Body line length 45–90ch; line-height 1.5–1.7 for body, 1.1–1.25 for large headings.',
    why: 'Long lines and tight leading hurt comprehension.',
    whenToUse: 'All paragraphs and long descriptions.',
    whenNotToUse: 'Short labels, buttons, nav — normal leading.',
    goodExample: 'About paragraph max-width ~65ch, line-height 1.6.',
    badExample: 'Full-width 200-character lines at line-height 1.1.',
    antiPattern: 'long-lines | tiny-body-text',
    executionHint: 'Set paragraph max-width and line-height on text nodes.',
    verification: 'Sample paragraphs: comfortable scan, no wall-of-text.',
    relatedRules: ['LC-001'], tags: ['line-height', 'line-length', 'readability', 'core'],
  },
  {
    id: 'TY-004', domain: '04-typography', title: 'Weight contrast, not weight salad',
    rule: 'Use 2–3 weights max (e.g. 400/600/700). Bold only what must stand out.',
    why: 'Too many weights destroy hierarchy.',
    whenToUse: 'Headings bold, body regular, CTA semibold.',
    whenNotToUse: 'Do not bold every other word.',
    goodExample: 'H1 700, sub 400, CTA 600.',
    badExample: '300, 400, 500, 600, 700, 800, 900 all present.',
    antiPattern: 'too-many-font-weights',
    executionHint: 'Limit font-weight values in styles to the chosen set.',
    verification: 'Enumerate weights used — ≤ 3 families of weight steps.',
    relatedRules: ['TY-002'], tags: ['weight'],
  },
  {
    id: 'TY-005', domain: '04-typography', title: 'CTA label typography',
    rule: 'CTA text: semibold, sentence case or consistent case, short (2–5 words), high contrast on button.',
    why: 'CTA must read as action, not caption.',
    whenToUse: 'All buttons.',
    whenNotToUse: 'Do not style body paragraphs like CTAs.',
    goodExample: '“Umów wizytę” 16px/600 on filled accent.',
    badExample: '12px light gray “Kliknij tutaj aby…”',
    executionHint: 'Button padding ≥ 12×24; font-size ≥ 14–16px.',
    verification: 'CTA legible at a glance; matches conversionStrategy.primaryCTA.',
    relatedRules: ['UX-001'], tags: ['cta', 'button'],
  },
];
