import type { KnowledgeEntry } from '../types';

export const COLOR_SYSTEMS_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'CO-001', domain: '05-color-systems', title: 'Color roles, not random hex',
    rule: 'Define roles: primary, secondary, accent, background, surface, text, muted text, border, CTA — fill each role intentionally.',
    why: 'Role-based color scales and stays consistent.',
    whenToUse: 'Every design system setup.',
    whenNotToUse: 'Never pick per-component ad-hoc colors after system is set.',
    goodExample: 'primary=brand, CTA=primary, surface=card bg, muted=secondary text.',
    badExample: 'Each section has a different random accent.',
    antiPattern: 'random-colors',
    executionHint: 'Set designSystem once; sections inherit — do not override randomly.',
    verification: 'Sample sections — same primary/CTA/background roles.',
    relatedRules: ['VC-001'], tags: ['color', 'roles', 'core'],
  },
  {
    id: 'CO-002', domain: '05-color-systems', title: 'Color derives from brand/industry/mood',
    rule: 'Derive palette from BRAND → INDUSTRY → MOOD → AUDIENCE → CONTENT → DESIGN DIRECTION.',
    why: 'Teal for dental trust ≠ neon for nightlife.',
    whenToUse: 'Initial palette selection.',
    whenNotToUse: 'Do not change palette mid-generation without brand brief.',
    goodExample: 'Dental: clean teal/blue; restaurant: warm red/orange; law: navy.',
    badExample: 'Dental site in aggressive magenta with no brand reason.',
    executionHint: 'Use INDUSTRY_DEFAULTS as baseline; brand colors override when provided.',
    verification: 'Palette matches industry mood + any brand constraints in brief.',
    relatedRules: ['IP-001'], tags: ['color', 'industry', 'brand'],
  },
  {
    id: 'CO-003', domain: '05-color-systems', title: 'Contrast for text and CTA',
    rule: 'Body text ≥ 4.5:1 contrast vs background; large text ≥ 3:1; CTA label clearly readable on button fill.',
    why: 'Low contrast fails accessibility and conversion.',
    whenToUse: 'All text and buttons.',
    whenNotToUse: 'Decorative non-text graphics (still aim 3:1 for UI components).',
    goodExample: '#F5F5F5 on #080B10; dark text on light CTA fill.',
    badExample: '#AAAAAA on #FFFFFF body copy; light-on-light button.',
    antiPattern: 'low-contrast-text',
    executionHint: 'Prefer dark bg + light text or light bg + dark text; avoid mid-gray on mid-color.',
    verification: 'Contrast check primary text and CTA against their backgrounds.',
    relatedRules: ['AC-001'], tags: ['contrast', 'accessibility', 'core'],
  },
  {
    id: 'CO-004', domain: '05-color-systems', title: 'Semantic and CTA color priority',
    rule: 'One CTA color across the site; reserve semantic success/warn/error for forms and status — not decoration.',
    why: 'Competing “important” colors dilute action.',
    whenToUse: 'Buttons, alerts, form states.',
    whenNotToUse: 'Do not use error red as a general section background.',
    goodExample: 'All primary buttons #1ABC9C; errors only in form validation.',
    badExample: 'Hero CTA green, pricing CTA blue, footer CTA purple.',
    executionHint: 'Single accent token for primary actions.',
    verification: 'All primary buttons share the same fill color.',
    relatedRules: ['CO-001', 'UX-001'], tags: ['cta', 'semantic'],
  },
];
