import type { KnowledgeEntry } from '../types';

export const SPACING_RHYTHM_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'SP-001', domain: '06-spacing-rhythm', title: 'Spacing scale',
    rule: 'Use a spacing scale (4/8/12/16/24/32/48/64/96). Section vertical rhythm uses the high end; component internals the low end.',
    why: 'Arbitrary spacing looks broken; a scale creates rhythm.',
    whenToUse: 'Padding, gaps, margins everywhere.',
    whenNotToUse: 'Do not invent 17px/29px one-offs.',
    goodExample: 'Section py=96; card p=24; gap between cards=24; title→body=8.',
    badExample: 'py 73, 110, 41 across three sections.',
    antiPattern: 'inconsistent-spacing',
    executionHint: 'Prefer multiples of 8; section padding desktop 64–120.',
    verification: 'Sample vertical gaps — multiples of base unit.',
    relatedRules: ['DP-006'], tags: ['spacing', 'scale', 'core'],
  },
  {
    id: 'SP-002', domain: '06-spacing-rhythm', title: 'Too tight vs balanced vs too empty',
    rule: 'Too tight: elements collide or &lt;8px between distinct groups. Balanced: clear grouping + breathing. Too empty: large voids with no content relationship.',
    why: 'All three states look unfinished for different reasons.',
    whenToUse: 'Audit every section after assembly.',
    whenNotToUse: 'Intentional luxury whitespace still aligns to a grid.',
    goodExample: 'Hero text block with 32px between H1 and CTA; 96px to next section.',
    badExample: 'Buttons overlapping text (tight) or 400px gap between H1 and sub (empty).',
    antiPattern: 'insufficient-whitespace | excessive-whitespace',
    executionHint: 'If gap > ~1.5× section padding with no divider/content, reduce.',
    verification: 'No overlaps; no unexplained voids (emptyish=0 in structural checks).',
    relatedRules: ['SP-001'], tags: ['density', 'balance', 'core', 'density-moderate'],
  },
  {
    id: 'SP-003', domain: '06-spacing-rhythm', title: 'Section separation',
    rule: 'Separate sections with consistent vertical padding (or alternating surface color + padding), not random dividers everywhere.',
    why: 'Consistent separation creates page rhythm.',
    whenToUse: 'Stacked marketing sections.',
    whenNotToUse: 'Tight tool UIs use borders instead of huge padding.',
    goodExample: 'All major sections py=80–96 desktop / 48–64 mobile.',
    badExample: 'One section 20px, next 200px, next glued.',
    executionHint: 'Apply same section padding token to all SectionPlans.',
    verification: 'Edge-to-edge scroll: even vertical cadence.',
    relatedRules: ['SP-001'], tags: ['sections', 'rhythm'],
  },
  {
    id: 'SP-004', domain: '06-spacing-rhythm', title: 'Internal component padding',
    rule: 'Buttons ≥12×24 padding; cards 20–32; inputs ≥12 vertical — never cramped touch targets.',
    why: 'Cramped controls feel broken and fail touch guidelines.',
    whenToUse: 'Interactive elements and cards.',
    whenNotToUse: 'Dense data tables may reduce cell padding intentionally.',
    goodExample: 'Primary button 14px 28px; card 24px.',
    badExample: 'Button padding 4px 6px; card text touching edges.',
    antiPattern: 'cramped-components',
    executionHint: 'Set padding on button/card styles from scale.',
    verification: 'Touch targets ≥44px height on mobile for primary actions.',
    relatedRules: ['AC-004'], tags: ['padding', 'components'],
  },
];
