import type { KnowledgeEntry } from '../types';

export const COMPONENT_INTELLIGENCE_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'CM-001', domain: '07-component-intelligence', title: 'Choose component by job, not availability',
    rule: 'Use a component only when its PURPOSE and CONTENT REQUIREMENTS match the section goal.',
    why: 'Library availability is not a design reason.',
    whenToUse: 'Selecting templates for each SectionPlan role.',
    whenNotToUse: 'Do not add gallery/pricing/FAQ components without content and goal fit.',
    goodExample: 'Dental booking → hero, services, testimonials, cta, contact — not product-grid.',
    badExample: 'Inserting pricing table for a free clinic informational page.',
    antiPattern: 'orphan-components',
    executionHint: 'ROLE_TO_LIBRARY_CATEGORY mapping + content completeness check before insert.',
    verification: 'Each inserted component has filled content and serves a goal step.',
    relatedRules: ['IA-002'], tags: ['components', 'selection', 'core'],
  },
  {
    id: 'CM-002', domain: '07-component-intelligence', title: 'Hero component contract',
    rule: 'Hero requires: heading + subheading + primary CTA; optional image slot.',
    why: 'Hero without CTA or value fails its job.',
    whenToUse: 'Page top for marketing sites.',
    whenNotToUse: 'Blog post interiors.',
    goodExample: 'Centered or split hero with filled CTA.',
    badExample: 'Hero with only decorative image and “Welcome”.',
    executionHint: 'After insert, overlay plan hero text via update_node_props.',
    verification: 'Hero shows benefit + CTA in final DOM.',
    relatedRules: ['IA-004'], tags: ['hero', 'component'],
  },
  {
    id: 'CM-003', domain: '07-component-intelligence', title: 'Feature/service grid contract',
    rule: 'Grid needs 3–6 complete items (label + short description); equal structure across cells.',
    why: 'Partial grids look unfinished.',
    whenToUse: 'Services, features, benefits.',
    whenNotToUse: 'Fewer than 3 items → use list or split layout instead.',
    goodExample: '3 services × (title, 1–2 sentence benefit).',
    badExample: '4 cards with 2 empty descriptions.',
    executionHint: 'Generate items from industry knowledge before insert.',
    verification: 'No empty card bodies; equal item counts per row.',
    relatedRules: ['LC-005'], tags: ['grid', 'features', 'services'],
  },
  {
    id: 'CM-004', domain: '07-component-intelligence', title: 'CTA block contract',
    rule: 'CTA section: compelling heading + one primary action (+ optional contact hint). Not a second homepage.',
    why: 'Decision sections must be short and single-minded.',
    whenToUse: 'After trust content, before footer.',
    whenNotToUse: 'Do not stack multiple full CTA sections.',
    goodExample: '“Gotowy na zdrowy uśmiech?” + Umów wizytę.',
    badExample: 'CTA block with 5 buttons of equal weight.',
    antiPattern: 'cta-overload',
    executionHint: 'One filled button; secondary as text link if needed.',
    verification: 'Exactly one primary filled CTA in the block.',
    relatedRules: ['DP-002'], tags: ['cta'],
  },
  {
    id: 'CM-005', domain: '07-component-intelligence', title: 'Testimonials and trust components',
    rule: 'Testimonials need quotes + attribution (name/role); logos need real or clearly generic partner marks; stats need numbers.',
    why: 'Unattributed praise reads fake.',
    whenToUse: 'When trust is a conversion lever (services, medical, B2B).',
    whenNotToUse: 'Skip if industry knowledge has no plausible social proof pattern.',
    goodExample: '“Bezbolesne leczenie… — Marek T.”',
    badExample: 'Three anonymous “Great service!!!” lines.',
    executionHint: 'Industry-plausible sample content allowed when user supplies none.',
    verification: 'Every quote has attribution; stats have units.',
    relatedRules: ['CD-004'], tags: ['testimonials', 'trust'],
  },
];
