import type { KnowledgeEntry } from '../types';

export const CONTENT_DESIGN_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'CD-001', domain: '08-content-design', title: 'No placeholders, no lorem ipsum',
    rule: 'Never ship lorem ipsum, “Tutaj wpisz tekst”, “Opis usługi”, or empty shells. If user gave no copy, write industry-plausible real copy.',
    why: 'Placeholders signal unfinished work and block QA.',
    whenToUse: 'Always.',
    whenNotToUse: 'Never acceptable in final generation.',
    goodExample: '“Nowoczesne implanty stomatologiczne — trwałe uzupełnienie braków.”',
    badExample: '“Lorem ipsum dolor sit amet” or “Opis usługi 1”.',
    antiPattern: 'placeholder-copy | generic-copy',
    executionHint: 'Overlay library defaults with plan content; C3 checks placeholders=0.',
    verification: 'Placeholder scan returns empty list.',
    relatedRules: ['IA-002'], tags: ['content', 'placeholder', 'core'],
  },
  {
    id: 'CD-002', domain: '08-content-design', title: 'Headline clarity over cleverness',
    rule: 'Headlines state outcome or offer; support with specifics. Brevity beats wordplay that hides meaning.',
    why: 'Scanners decide in seconds.',
    whenToUse: 'Hero, section titles, CTA heads.',
    whenNotToUse: 'Long-form editorial can be more literary in body only.',
    goodExample: '“Twój uśmiech to nasza pasja” + concrete subline.',
    badExample: '“Witamy w świecie innowacyjnych rozwiązań jutra”.',
    antiPattern: 'generic-copy',
    executionHint: 'Headline ≤ ~10 words; subline adds audience + benefit.',
    verification: 'Headline communicates offer without jargon-only phrasing.',
    relatedRules: ['IA-004'], tags: ['headlines', 'clarity', 'core'],
  },
  {
    id: 'CD-003', domain: '08-content-design', title: 'Specificity and audience awareness',
    rule: 'Copy names the audience and the concrete benefit; avoid universal empty claims.',
    why: 'Specific copy builds credibility and SEO relevance.',
    whenToUse: 'Subheadlines, feature descriptions, about.',
    whenNotToUse: 'Legal footnotes.',
    goodExample: '“Bezbolesne leczenie i miła obsługa dla pacjentów w każdym wieku.”',
    badExample: '“Najlepsza jakość i profesjonalizm — zawsze.”',
    executionHint: 'Include industry nouns (implanty, menu, nieruchomości) from brief.',
    verification: 'Body contains ≥1 industry-specific term per major section.',
    relatedRules: ['IP-001'], tags: ['specificity', 'audience'],
  },
  {
    id: 'CD-004', domain: '08-content-design', title: 'Tone consistency',
    rule: 'One toneOfVoice across all sections (e.g. professional-warm for dental, playful for café) — match contentStrategy.toneOfVoice.',
    why: 'Tone whiplash breaks brand trust.',
    whenToUse: 'Whole site generation.',
    whenNotToUse: 'Do not mix formal legal tone with meme tone mid-page.',
    goodExample: 'All sections professional + reassuring for medical.',
    badExample: 'Hero corporate, testimonials slang, footer robotic.',
    executionHint: 'Set contentStrategy.toneOfVoice from industry pattern; apply in all overlays.',
    verification: 'Read all headings — consistent register.',
    relatedRules: ['VC-001'], tags: ['tone', 'consistency', 'core'],
  },
  {
    id: 'CD-005', domain: '08-content-design', title: 'CTA copy is a verb + object',
    rule: 'CTA labels are actionable: verb + object (“Umów wizytę”, “Zobacz menu”), not “Więcej” alone when a stronger action exists.',
    why: 'Action labels increase click intent clarity.',
    whenToUse: 'Primary and secondary buttons.',
    whenNotToUse: 'Nav links may stay short nouns.',
    goodExample: '“Umów wizytę”, “Sprawdź ofertę”.',
    badExample: '“Kliknij”, “Submit”, “Continue” without context.',
    executionHint: 'Use industry pattern.commonCta as primary; derive secondary.',
    verification: 'Primary CTA matches conversionStrategy.primaryCTA.',
    relatedRules: ['UX-001'], tags: ['cta', 'copy'],
  },
];
