import type { KnowledgeEntry, IndustryPattern } from '../types';

export const INDUSTRY_PATTERNS: IndustryPattern[] = [
  {
    id: 'IP-dental-medical', industry: 'dentist', businessModel: 'clinic booking / fee-for-service',
    targetAudience: 'patients seeking trust, comfort, appointment ease',
    commonGoals: ['book appointment', 'show specializations', 'build trust'],
    commonContent: ['services', 'specializations', 'team', 'testimonials', 'contact'],
    commonPageStructure: ['navbar', 'hero', 'services', 'about', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'services', 'about', 'team', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Umów wizytę', 'Zadzwoń', 'Sprawdź termin'],
    visualDirection: 'clean trust teal/blue, soft radii, photography of clinic/team',
    commonMistakes: ['scary clinical imagery without warmth', 'weak booking CTA', 'no trust signals'],
    contentTone: 'professional-warm reassuring',
    mediaNeeds: ['clinic interior', 'team photos', 'smile/result imagery', 'icons for services'],
    tags: ['dentist', 'dental', 'medical', 'clinic', 'health'],
  },
  {
    id: 'IP-restaurant', industry: 'restaurant', businessModel: 'hospitality / dine-in + delivery',
    targetAudience: 'local diners, families, event guests',
    commonGoals: ['view menu', 'reserve table', 'show location'],
    commonContent: ['menu highlights', 'story', 'gallery', 'hours', 'reservations'],
    commonPageStructure: ['navbar', 'hero', 'menu', 'about', 'gallery', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'services', 'gallery', 'about', 'testimonials', 'contact', 'footer'],
    commonCta: ['Zobacz menu', 'Zarezerwuj stolik', 'Zamów online'],
    visualDirection: 'warm appetizing reds/oranges, food photography, cozy',
    commonMistakes: ['menu as wall of text', 'no location/hours', 'low-quality food photos'],
    contentTone: 'warm inviting sensory',
    mediaNeeds: ['food photography', 'interior', 'chef/team'],
    tags: ['restaurant', 'food', 'dining', 'cafe', 'hospitality'],
  },
  {
    id: 'IP-realestate', industry: 'realestate', businessModel: 'listings + agent lead-gen',
    targetAudience: 'buyers/renters, investors',
    commonGoals: ['browse listings', 'contact agent', 'schedule viewing'],
    commonContent: ['listings', 'areas', 'agent trust', 'process'],
    commonPageStructure: ['navbar', 'hero', 'listings', 'about', 'process', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'gallery', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz oferty', 'Umów prezentację', 'Skontaktuj się'],
    visualDirection: 'premium neutral gold/navy, architecture photography, spacious',
    commonMistakes: ['no filtering mental model', 'weak agent credibility', 'tiny listing photos'],
    contentTone: 'professional aspirational',
    mediaNeeds: ['property photos', 'aerial/area', 'agent portrait'],
    tags: ['realestate', 'property', 'housing', 'nieruchomości'],
  },
  {
    id: 'IP-construction', industry: 'other', businessModel: 'project-based local service',
    targetAudience: 'homeowners, developers',
    commonGoals: ['request quote', 'see projects', 'trust reliability'],
    commonContent: ['services', 'portfolio projects', 'process', 'certifications'],
    commonPageStructure: ['navbar', 'hero', 'services', 'portfolio', 'process', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'portfolio', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Wyceń projekt', 'Zadzwoń', 'Umów wizytę na budowie'],
    visualDirection: 'solid industrial, strong geometry, project photography',
    commonMistakes: ['no project proof', 'vague services', 'missing license/trust'],
    contentTone: 'direct reliable',
    mediaNeeds: ['before/after projects', 'team on site', 'equipment'],
    tags: ['construction', 'build', 'remont', 'architecture'],
  },
  {
    id: 'IP-architecture', industry: 'other', businessModel: 'studio projects + leads',
    targetAudience: 'clients seeking design-led spaces',
    commonGoals: ['showcase projects', 'win inquiries', 'express design philosophy'],
    commonContent: ['projects', 'philosophy', 'team', 'awards'],
    commonPageStructure: ['navbar', 'hero', 'portfolio', 'about', 'process', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'portfolio', 'about', 'team', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz projekty', 'Porozmawiajmy'],
    visualDirection: 'editorial minimal, large imagery, restrained type',
    commonMistakes: ['cluttered grid killing photos', 'weak captions', 'no contact path'],
    contentTone: 'confident editorial',
    mediaNeeds: ['high-res project photography', 'plans/detail shots'],
    tags: ['architecture', 'studio', 'design'],
  },
  {
    id: 'IP-photography', industry: 'portfolio', businessModel: 'booking + packages',
    targetAudience: 'clients for portraits/events/products',
    commonGoals: ['view portfolio', 'book session', 'see packages'],
    commonContent: ['gallery', 'packages', 'about style', 'booking'],
    commonPageStructure: ['navbar', 'hero', 'gallery', 'services', 'about', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'portfolio', 'features', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz portfolio', 'Zarezerwuj sesję'],
    visualDirection: 'image-first minimal chrome, consistent crop',
    commonMistakes: ['UI competing with photos', 'inconsistent aspect ratios', 'no booking CTA'],
    contentTone: 'visual concise personal',
    mediaNeeds: ['hero portfolio pieces', 'series galleries'],
    tags: ['photography', 'fotograf', 'portfolio', 'gallery'],
  },
  {
    id: 'IP-creative-agency', industry: 'agency', businessModel: 'project retainers',
    targetAudience: 'brands needing creative work',
    commonGoals: ['show work', 'generate leads', 'demonstrate POV'],
    commonContent: ['case studies', 'services', 'team', 'clients'],
    commonPageStructure: ['navbar', 'hero', 'work', 'services', 'about', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'portfolio', 'features', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz prace', 'Zacznijmy projekt'],
    visualDirection: 'bold creative, strong brand expression, case study visuals',
    commonMistakes: ['style over clarity', 'no results/metrics', 'hidden contact'],
    contentTone: 'bold provocative confident',
    mediaNeeds: ['case study imagery', 'campaign shots'],
    tags: ['agency', 'creative', 'design studio', 'marketing'],
  },
  {
    id: 'IP-marketing-agency', industry: 'agency', businessModel: 'retainer lead-gen',
    targetAudience: 'SMEs wanting growth',
    commonGoals: ['book call', 'show results', 'explain services'],
    commonContent: ['services', 'case results', 'process', 'team'],
    commonPageStructure: ['navbar', 'hero', 'services', 'cases', 'process', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Umów konsultację', 'Pokaż wyniki'],
    visualDirection: 'confident modern, data highlights, CTA-forward',
    commonMistakes: ['jargon walls', 'no proof numbers', 'weak offer'],
    contentTone: 'persuasive direct',
    mediaNeeds: ['dashboard/metric visuals', 'team'],
    tags: ['marketing', 'agency', 'reklama', 'growth'],
  },
  {
    id: 'IP-law-firm', industry: 'law', businessModel: 'consultation lead-gen',
    targetAudience: 'clients with legal issues',
    commonGoals: ['contact attorney', 'practice areas', 'trust expertise'],
    commonContent: ['practice areas', 'attorneys', 'credentials', 'contact'],
    commonPageStructure: ['navbar', 'hero', 'services', 'about', 'team', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'about', 'team', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Skonsultuj sprawę', 'Umów spotkanie'],
    visualDirection: 'authoritative navy/gold, restrained, professional portraits',
    commonMistakes: ['cold unapproachable tone', 'no attorney bios', 'buried phone'],
    contentTone: 'formal trustworthy precise',
    mediaNeeds: ['attorney portraits', 'office'],
    tags: ['law', 'legal', 'kancelaria', 'adwokat'],
  },
  {
    id: 'IP-fitness', industry: 'fitness', businessModel: 'membership + classes',
    targetAudience: 'local fitness enthusiasts',
    commonGoals: ['join/trial', 'see classes', 'trainers'],
    commonContent: ['programs', 'schedule', 'trainers', 'pricing/trial'],
    commonPageStructure: ['navbar', 'hero', 'programs', 'trainers', 'pricing', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'team', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Dołącz teraj', 'Wypróbuj za darmo', 'Zobacz plany'],
    visualDirection: 'energetic high-contrast, motion photography',
    commonMistakes: ['no trial offer', 'cluttered schedule', 'weak transformation proof'],
    contentTone: 'motivating energetic',
    mediaNeeds: ['training action shots', 'trainer portraits', 'facility'],
    tags: ['fitness', 'gym', 'trening', 'workout'],
  },
  {
    id: 'IP-beauty', industry: 'beauty', businessModel: 'appointment booking',
    targetAudience: 'clients seeking aesthetic services',
    commonGoals: ['book', 'see services/prices', 'trust results'],
    commonContent: ['services', 'portfolio/results', 'team', 'booking'],
    commonPageStructure: ['navbar', 'hero', 'services', 'gallery', 'about', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'portfolio', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zarezerwuj termin', 'Zobacz cennik'],
    visualDirection: 'elegant soft, refined palette, beauty photography',
    commonMistakes: ['no price anchors', 'inconsistent visual style', 'hard booking path'],
    contentTone: 'elegant friendly',
    mediaNeeds: ['results gallery', 'salon interior', 'team'],
    tags: ['beauty', 'salon', 'uroda', 'kosmetyki'],
  },
  {
    id: 'IP-hotel', industry: 'other', businessModel: 'direct bookings',
    targetAudience: 'travelers',
    commonGoals: ['book stay', 'see rooms', 'location'],
    commonContent: ['rooms', 'amenities', 'gallery', 'location'],
    commonPageStructure: ['navbar', 'hero', 'rooms', 'amenities', 'gallery', 'reviews', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Sprawdź dostępność', 'Zarezerwuj pokój'],
    visualDirection: 'hospitality warm premium, interior photography',
    commonMistakes: ['booking widget buried', 'dark unreadable photos', 'no amenity clarity'],
    contentTone: 'welcoming hospitable',
    mediaNeeds: ['rooms', 'amenities', 'location views'],
    tags: ['hotel', 'travel', 'nocleg', 'hospitality'],
  },
  {
    id: 'IP-travel', industry: 'other', businessModel: 'packages + leads',
    targetAudience: 'vacation planners',
    commonGoals: ['browse trips', 'inquire', 'inspire'],
    commonContent: ['destinations', 'packages', 'testimonials', 'contact'],
    commonPageStructure: ['navbar', 'hero', 'destinations', 'packages', 'about', 'reviews', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'portfolio', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz wyjazdy', 'Zapytaj o ofertę'],
    visualDirection: 'vivid destination photography, optimistic',
    commonMistakes: ['stock-only feel', 'no clear package next step'],
    contentTone: 'inspiring adventurous',
    mediaNeeds: ['destination hero images', 'experience shots'],
    tags: ['travel', 'tourism', 'wakacje', 'wyjazdy'],
  },
  {
    id: 'IP-saas', industry: 'saas', businessModel: 'subscription freemium',
    targetAudience: 'teams evaluating tools',
    commonGoals: ['start trial', 'see features', 'pricing clarity'],
    commonContent: ['value prop', 'features', 'pricing', 'social proof', 'docs'],
    commonPageStructure: ['navbar', 'hero', 'features', 'pricing', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'pricing', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Wypróbuj za darmo', 'Zobacz demo', 'Rozpocznij'],
    visualDirection: 'product UI screenshots, clean modern, purple/blue common',
    commonMistakes: ['feature dump without outcomes', 'pricing hidden', 'no trial CTA'],
    contentTone: 'clear benefit-driven technical-friendly',
    mediaNeeds: ['product screenshots', 'UI mockups', 'logos'],
    tags: ['saas', 'software', 'app', 'platform', 'subscription'],
  },
  {
    id: 'IP-startup', industry: 'tech', businessModel: 'growth / waitlist / funding story',
    targetAudience: 'early adopters, investors, talent',
    commonGoals: ['sign up', 'explain differentiation', 'build credibility'],
    commonContent: ['vision', 'product', 'traction', 'team'],
    commonPageStructure: ['navbar', 'hero', 'features', 'about', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'about', 'stats', 'cta', 'contact', 'footer'],
    commonCta: ['Dołącz do listy', 'Wypróbuj beta'],
    visualDirection: 'modern bold, product-forward',
    commonMistakes: ['vague vision', 'no social proof', 'weak CTA'],
    contentTone: 'energetic clear ambitious',
    mediaNeeds: ['product UI', 'founder photos'],
    tags: ['startup', 'launch', 'beta', 'tech'],
  },
  {
    id: 'IP-technology', industry: 'tech', businessModel: 'B2B/B2C product',
    targetAudience: 'tech buyers and users',
    commonGoals: ['demo request', 'feature understanding', 'trust'],
    commonContent: ['platform capabilities', 'integrations', 'security', 'cases'],
    commonPageStructure: ['navbar', 'hero', 'features', 'cases', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Umów demo', 'Dowiedz się więcej'],
    visualDirection: 'technical clean, diagrams/screenshots',
    commonMistakes: ['buzzword soup', 'no architecture clarity'],
    contentTone: 'precise credible',
    mediaNeeds: ['architecture diagrams', 'UI', 'logos'],
    tags: ['technology', 'tech', 'digital', 'platform'],
  },
  {
    id: 'IP-portfolio', industry: 'portfolio', businessModel: 'personal brand / commissions',
    targetAudience: 'prospective clients/employers',
    commonGoals: ['show work', 'contact', 'hire'],
    commonContent: ['projects', 'bio', 'skills', 'contact'],
    commonPageStructure: ['navbar', 'hero', 'work', 'about', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'portfolio', 'about', 'features', 'cta', 'contact', 'footer'],
    commonCta: ['Zobacz projekty', 'Napisz do mnie'],
    visualDirection: 'personal brand, work-first',
    commonMistakes: ['too much chrome around work', 'no contact CTA'],
    contentTone: 'personal confident concise',
    mediaNeeds: ['project covers', 'process shots'],
    tags: ['portfolio', 'personal', 'showcase', 'freelance'],
  },
  {
    id: 'IP-freelancer', industry: 'portfolio', businessModel: 'service contracts',
    targetAudience: 'clients needing one expert',
    commonGoals: ['hire', 'see services', 'trust reliability'],
    commonContent: ['services', 'work', 'process', 'availability'],
    commonPageStructure: ['navbar', 'hero', 'services', 'work', 'about', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'portfolio', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Sprawdź dostępność', 'Omów projekt'],
    visualDirection: 'clean personal professional',
    commonMistakes: ['no clear offer', 'hidden rates/trust'],
    contentTone: 'direct approachable',
    mediaNeeds: ['work samples', 'portrait'],
    tags: ['freelancer', 'consultant', 'services', 'independent'],
  },
  {
    id: 'IP-ecommerce', industry: 'ecommerce', businessModel: 'product sales',
    targetAudience: 'shoppers comparing products',
    commonGoals: ['purchase', 'browse catalog', 'trust checkout'],
    commonContent: ['products', 'categories', 'offers', 'policies'],
    commonPageStructure: ['navbar', 'hero', 'products', 'benefits', 'testimonials', 'cta', 'footer'],
    usefulSections: ['navbar', 'hero', 'products', 'features', 'testimonials', 'cta', 'footer'],
    commonCta: ['Kup teraz', 'Zobacz produkty', 'Do koszyka'],
    visualDirection: 'product photography first, clear price hierarchy',
    commonMistakes: ['cluttered promo banners', 'weak product imagery', 'no trust badges'],
    contentTone: 'commercial clear urgent-when-needed',
    mediaNeeds: ['product shots', 'lifestyle usage'],
    tags: ['ecommerce', 'shop', 'store', 'sklep', 'retail'],
  },
  {
    id: 'IP-local-service', industry: 'other', businessModel: 'local lead-gen',
    targetAudience: 'nearby customers',
    commonGoals: ['call/book', 'service area', 'trust'],
    commonContent: ['services', 'area', 'reviews', 'contact'],
    commonPageStructure: ['navbar', 'hero', 'services', 'about', 'testimonials', 'contact', 'footer'],
    usefulSections: ['navbar', 'hero', 'features', 'about', 'testimonials', 'cta', 'contact', 'footer'],
    commonCta: ['Zadzwoń', 'Umów wizytę', 'Wyślij zapytanie'],
    visualDirection: 'friendly local trustworthy, clear phone CTA',
    commonMistakes: ['no phone visibility', 'service area missing', 'generic stock only'],
    contentTone: 'friendly straightforward',
    mediaNeeds: ['local/team photos', 'service imagery'],
    tags: ['local', 'service', 'uslugi', 'small-business'],
  },
];

export const INDUSTRY_PATTERN_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'IP-001', domain: '09-industry-patterns', title: 'Industry pattern is a starting point',
    rule: 'Industry patterns inform structure, tone, CTA, media — but final decisions come from the brief (business, audience, goal).',
    why: 'Patterns without brief-awareness become rigid templates.',
    whenToUse: 'When planning structure and content defaults.',
    whenNotToUse: 'When brief explicitly overrides pattern defaults.',
    goodExample: 'Dental pattern suggests booking CTA; brief about implantology adds specialization services.',
    badExample: 'Ignoring brief and pasting generic restaurant IA onto a dental brief.',
    executionHint: 'Merge pattern defaults with brief signals in DecisionContext.designHints.',
    verification: 'Plan sections ≈ pattern usefulSections ∩ brief goals.',
    relatedRules: ['IA-001'], tags: ['industry', 'patterns', 'core'],
  },
  {
    id: 'IP-002', domain: '09-industry-patterns', title: 'Specialization narrows content',
    rule: 'When brief names specializations (implantology, orthodontics…), reflect them in services/features copy and hero subline.',
    why: 'Specific offer beats generic “we care about smiles”.',
    whenToUse: 'Brief contains domain-specific terms.',
    whenNotToUse: 'Generic brief without specialization cues.',
    goodExample: 'Implantology + aesthetic dentistry → services emphasize implants, whitening, veneers.',
    badExample: 'Dental brief with implantology ignored; only generic “stomatologia”.',
    executionHint: 'Pass specializations from extractBriefSignals into content generation.',
    verification: 'Services section mentions specialization terms from brief.',
    relatedRules: ['CD-003'], tags: ['specialization', 'content'],
  },
  {
    id: 'IP-003', domain: '09-industry-patterns', title: 'Industry CTA vocabulary',
    rule: 'Use industry-native CTAs (booking for clinic, menu for restaurant, trial for SaaS) as primary.',
    why: 'Mismatched CTA language confuses intent.',
    whenToUse: 'Always when pattern provides commonCta.',
    whenNotToUse: 'When brief supplies explicit CTA copy.',
    goodExample: 'Dental → “Umów wizytę” not “Start free trial”.',
    badExample: 'SaaS “Buy now” on a law firm consultation page.',
    executionHint: 'conversionStrategy.primaryCTA = pattern.commonCta[0] unless brief overrides.',
    verification: 'Primary CTA matches industry vocabulary.',
    relatedRules: ['CD-005'], tags: ['cta', 'industry'],
  },
];
