import type { KnowledgeEntry } from '../types';

export const IMAGE_MEDIA_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'IM-001', domain: '10-image-media', title: 'Image only when it proves or delights',
    rule: 'Add imagery when it proves quality (product/clinic/portfolio), sets mood, or explains — not because a gallery component exists.',
    why: 'Empty or irrelevant images add noise and QA failures.',
    whenToUse: 'Hero proof, portfolio, product, team, before/after.',
    whenNotToUse: 'Text-only conceptual sections without assets.',
    goodExample: 'Dental hero with clinic/smile photo.',
    badExample: 'Gallery section on a page with no visual content strategy.',
    antiPattern: 'meaningless-galleries',
    executionHint: 'assetStrategy.imageStyle + industry pattern.mediaNeeds drive image slots.',
    verification: 'Every image has role, alt intent, and content relevance.',
    relatedRules: ['IA-002'], tags: ['media', 'images', 'core'],
  },
  {
    id: 'IM-002', domain: '10-image-media', title: 'Aspect ratio and crop consistency',
    rule: 'Keep consistent aspect ratios within a gallery/grid (e.g. all 16:9 or 4:3); crop around focal point.',
    why: 'Mixed ratios read as broken collection.',
    whenToUse: 'Galleries, portfolios, product grids, team grids.',
    whenNotToUse: 'Editorial hero can be unique.',
    goodExample: 'All portfolio cards 4:3 with centered subject.',
    badExample: 'One square, one portrait, one panoramic in the same row.',
    executionHint: 'object-fit: cover; fixed aspect-ratio on media wrappers.',
    verification: 'Grid media share aspect-ratio; faces/products not awkwardly cropped.',
    relatedRules: ['LC-005'], tags: ['aspect-ratio', 'crop'],
  },
  {
    id: 'IM-003', domain: '10-image-media', title: 'Image/text balance in heroes',
    rule: 'Hero image supports the message — does not fight text contrast; use overlay/scrim when text sits on photo.',
    why: 'Unreadable hero text fails UX and a11y.',
    whenToUse: 'Photo backgrounds with text overlay.',
    whenNotToUse: 'Solid color heroes with separate image column.',
    goodExample: 'Dark gradient scrim under white headline on photo.',
    badExample: 'Busy photo + light text no scrim.',
    executionHint: 'Add dark overlay opacity when text overlays media.',
    verification: 'Headline contrast over image still readable.',
    relatedRules: ['CO-003'], tags: ['hero', 'contrast', 'media'],
  },
  {
    id: 'IM-004', domain: '10-image-media', title: 'Media hierarchy',
    rule: 'One dominant hero visual per viewport; secondary images support sections — do not compete equally.',
    why: 'Equal-weight imagery flattens hierarchy.',
    whenToUse: 'Multi-image pages.',
    whenNotToUse: 'Photo essays may intentionally equalize.',
    goodExample: 'Large hero image; smaller service icons/thumbnails below.',
    badExample: 'Three equally large competing banners stacked.',
    executionHint: 'Size hero media largest; section images medium; icons small.',
    verification: 'Largest visual is the intended focal point.',
    relatedRules: ['DP-001'], tags: ['hierarchy', 'media'],
  },
];
