import type { KnowledgeEntry } from '../types';

export const UX_CONVERSION_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'UX-001', domain: '11-ux-conversion', title: 'Define primary and secondary goal + CTA',
    rule: 'Every site plan declares PRIMARY GOAL, SECONDARY GOAL, PRIMARY CTA, SECONDARY CTA derived from business purpose.',
    why: 'CTA without business goal is decoration.',
    whenToUse: 'At plan time for every brief.',
    whenNotToUse: 'Never ship ambiguous “Dowiedz się więcej” as only action when a stronger verb exists.',
    goodExample: 'Dental: primary=book visit “Umów wizytę”; secondary=call.',
    badExample: 'Three competing filled CTAs of equal weight.',
    executionHint: 'Map purpose → conversionStrategy.primaryCTA + primaryCTALocation.',
    verification: 'One clear primary CTA in hero + repeated strategically.',
    relatedRules: ['IA-006'], tags: ['cta', 'goals', 'conversion', 'core'],
  },
  {
    id: 'UX-002', domain: '11-ux-conversion', title: 'Trust before the hard ask',
    rule: 'Place trust (testimonials, credentials, guarantees, stats) before or adjacent to major conversion blocks.',
    why: 'Trust reduces friction at decision time.',
    whenToUse: 'Lead-gen, booking, high-consideration purchases.',
    whenNotToUse: 'Impulse micro-CTAs in nav.',
    goodExample: 'Testimonials section immediately before final CTA.',
    badExample: 'CTA with zero social proof anywhere on page.',
    executionHint: 'Order: hero → value → trust → CTA → contact/footer.',
    verification: 'Trust section exists above final CTA for lead-gen briefs.',
    relatedRules: ['CM-005'], tags: ['trust', 'conversion'],
  },
  {
    id: 'UX-003', domain: '11-ux-conversion', title: 'Navigation hierarchy matches IA',
    rule: 'Nav labels mirror main page sections/audience jobs; max ~5–7 top-level items; primary CTA in nav.',
    why: 'Nav is the map; mismatch increases bounce.',
    whenToUse: 'Navbar construction.',
    whenNotToUse: 'Do not list every footer link in top nav.',
    goodExample: 'Strona główna, Usługi, O nas, Opinie, Kontakt + CTA.',
    badExample: '12 vague top-level links.',
    executionHint: 'Derive nav items from planned section roles.',
    verification: 'Nav items correspond to real sections/pages.',
    relatedRules: ['IA-003'], tags: ['navigation', 'ia'],
  },
  {
    id: 'UX-004', domain: '11-ux-conversion', title: 'Reduce friction on forms and contact',
    rule: 'Ask only necessary fields; provide phone/mail alternatives; make contact section easy to find.',
    why: 'Every extra field and buried form kills leads.',
    whenToUse: 'Contact, booking, newsletter.',
    whenNotToUse: 'Do not multi-step a simple callback request without value.',
    goodExample: 'Name, phone, message + clear submit + phone number.',
    badExample: '15-field form as only contact method.',
    executionHint: 'Keep contact copy short; CTA verb matches form intent.',
    verification: 'Contact path reachable from nav and footer; fields minimal.',
    relatedRules: ['UX-001'], tags: ['forms', 'friction', 'contact'],
  },
];
