import type { KnowledgeEntry } from '../types';

export const RESPONSIVE_DESIGN_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'RD-001', domain: '12-responsive-design', title: 'Design three breakpoints intentionally',
    rule: 'Plan desktop, tablet, mobile as compositions — not a scaled-down desktop screenshot.',
    why: 'Stacking and priority change on small screens.',
    whenToUse: 'All public marketing pages.',
    whenNotToUse: 'Desktop-only internal tools (still avoid horizontal scroll).',
    goodExample: 'Mobile: stacked hero, full-width CTA, collapsible nav.',
    badExample: '3-column grid forced onto 360px width.',
    executionHint: 'responsiveStrategy: stacked hero, hamburger nav, type scale ~0.85.',
    verification: 'No horizontal overflow at 360px; tap targets usable.',
    relatedRules: ['RD-002'], tags: ['responsive', 'breakpoints', 'core'],
  },
  {
    id: 'RD-002', domain: '12-responsive-design', title: 'Column collapse and stacking',
    rule: 'Multi-column layouts collapse to 1 column on mobile; preserve logical reading order.',
    why: 'Side-by-side columns become unreadable slivers.',
    whenToUse: 'Grids, split heroes, feature rows.',
    whenNotToUse: 'When a deliberate 2-up micro layout still fits.',
    goodExample: '4 cards → 1 col mobile, 2 col tablet, 4 col desktop.',
    badExample: 'Fixed 4-col at all widths with 8px cards.',
    executionHint: 'Use auto-fit minmax grids or breakpoint classes.',
    verification: 'DOM order = visual order after collapse.',
    relatedRules: ['LC-002'], tags: ['stacking', 'grid'],
  },
  {
    id: 'RD-003', domain: '12-responsive-design', title: 'Typography and spacing adapt',
    rule: 'Scale type down modestly on mobile (H1 ~32–40); reduce section padding; keep line-height readable.',
    why: 'Desktop type/padding crowds mobile viewports.',
    whenToUse: 'All breakpoints.',
    whenNotToUse: 'Do not shrink body below ~16px for readability.',
    goodExample: 'Section py 96→56; H1 56→36.',
    badExample: 'Same 64px H1 and 120px padding on mobile.',
    executionHint: 'responsiveStrategy.mobileTypographyScale; media queries for padding.',
    verification: 'Mobile screenshots: no clipped headings, comfortable density.',
    relatedRules: ['TY-001'], tags: ['typography', 'spacing', 'mobile'],
  },
  {
    id: 'RD-004', domain: '12-responsive-design', title: 'Mobile navigation and CTA',
    rule: 'Mobile: hamburger or minimal nav; primary CTA remains visible (sticky or in hero); thumb-reachable.',
    why: 'Mobile conversion depends on persistent action access.',
    whenToUse: 'Marketing sites on small screens.',
    whenNotToUse: 'Do not hide the only booking CTA behind a menu with no hero CTA.',
    goodExample: 'Hero full-width CTA + hamburger for links.',
    badExample: 'Desktop nav with 7 links wrapping into unusable rows.',
    executionHint: 'mobileNavStyle=hamburger; ensure hero CTA full-width on small screens.',
    verification: 'Primary CTA visible without opening menu on mobile.',
    relatedRules: ['UX-001'], tags: ['mobile', 'nav', 'cta'],
  },
];
