import type { KnowledgeEntry } from '../types';

export const ACCESSIBILITY_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'AC-001', domain: '13-accessibility', title: 'Contrast is non-negotiable',
    rule: 'Text and essential UI meet WCAG AA contrast (4.5:1 body, 3:1 large/UI).',
    why: 'Low contrast excludes users and fails QA.',
    whenToUse: 'All text, buttons, links on images.',
    whenNotToUse: 'Purely decorative elements (still avoid confusion).',
    goodExample: 'High-contrast body on surface cards.',
    badExample: 'Muted gray on pastel gradient.',
    executionHint: 'Check designSystem text vs background; add scrims on photos.',
    verification: 'Contrast audit on primary text and CTAs.',
    relatedRules: ['CO-003'], tags: ['contrast', 'core', 'accessibility'],
  },
  {
    id: 'AC-002', domain: '13-accessibility', title: 'Semantic heading hierarchy',
    rule: 'One H1 per page view; hierarchical H2/H3; do not skip levels for size reasons alone.',
    why: 'Screen readers and scanners rely on structure.',
    whenToUse: 'All sections.',
    whenNotToUse: 'Never use H1 for decorative footer text.',
    goodExample: 'H1 hero → H2 section titles → H3 card titles.',
    badExample: 'Multiple H1s; H4 as first heading.',
    executionHint: 'Section heading nodes use correct heading levels.',
    verification: 'Heading outline is a logical tree.',
    relatedRules: ['TY-001'], tags: ['semantics', 'headings'],
  },
  {
    id: 'AC-003', domain: '13-accessibility', title: 'Clear buttons and links',
    rule: 'Interactive elements look interactive (contrast, affordance, focus states); labels describe destination/action.',
    why: 'Ambiguous “click here” and invisible links fail users.',
    whenToUse: 'All CTAs and inline links.',
    whenNotToUse: 'Non-interactive text should not look like links.',
    goodExample: '“Umów wizytę” button + underlined text links with clear names.',
    badExample: 'Gray text link with no underline next to identical body copy.',
    executionHint: 'Ensure button styles distinct; link color differs from body.',
    verification: 'Tab focus visible; labels action-oriented.',
    relatedRules: ['CD-005'], tags: ['buttons', 'links'],
  },
  {
    id: 'AC-004', domain: '13-accessibility', title: 'Touch targets and keyboard',
    rule: 'Touch targets ≥44×44px (or adequate padding); interactive elements keyboard-reachable in logical order.',
    why: 'Mobile and AT users cannot use tiny or mouse-only controls.',
    whenToUse: 'Mobile layouts, icon buttons, nav.',
    whenNotToUse: 'Dense desktop tables still need reasonable targets.',
    goodExample: 'Full-width mobile CTA with generous padding.',
    badExample: '12px icon-only close button as sole action.',
    executionHint: 'Button min-height; avoid hover-only interactions for primary actions.',
    verification: 'Mobile tap target check; logical tab order.',
    relatedRules: ['SP-004'], tags: ['touch', 'keyboard', 'mobile'],
  },
];
