import type { KnowledgeEntry } from '../types';

export const ANTI_PATTERN_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'AP-001', domain: '15-anti-patterns', title: 'Too many sections',
    rule: 'Cap sections to what the goal needs (typically 6–10 content sections for a marketing page).',
    why: 'Section sprawl dilutes message and increases QA surface.',
    whenToUse: 'Plan review before execution.',
    whenNotToUse: 'Do not cut required trust/contact frame sections.',
    goodExample: 'navbar, hero, services, about, testimonials, cta, footer.',
    badExample: '15 near-duplicate feature bands.',
    antiPattern: 'too-many-sections',
    executionHint: 'If a section does not advance a goal step, drop it.',
    verification: 'Section count sane; no near-duplicate roles.',
    relatedRules: ['IA-001'], tags: ['sections', 'core'],
  },
  {
    id: 'AP-002', domain: '15-anti-patterns', title: 'Placeholder and generic copy',
    rule: 'Ban lorem ipsum, “Opis usługi”, empty cards — replace with industry-specific real copy.',
    why: 'Placeholders mean the site is not done.',
    whenToUse: 'Content QA always.',
    whenNotToUse: 'Never allow in final output.',
    goodExample: 'Concrete implantology benefit copy.',
    badExample: '“Lorem ipsum” / “Tutaj wpisz tekst”.',
    antiPattern: 'placeholder-copy | generic-copy',
    executionHint: 'Fail generation QA if placeholder patterns detected.',
    verification: 'Placeholder scanner = 0 hits.',
    relatedRules: ['CD-001'], tags: ['content', 'placeholder'],
  },
  {
    id: 'AP-003', domain: '15-anti-patterns', title: 'CTA overload and weak CTA',
    rule: 'One primary filled CTA per section; avoid both “no CTA” and “five equal CTAs”.',
    why: 'Overload paralyzes; absence loses leads.',
    whenToUse: 'Every conversion-capable section.',
    whenNotToUse: 'Pure reading content.',
    goodExample: 'Single “Umów wizytę” filled; secondary text links only.',
    badExample: 'Same row: Call / Chat / Email / Buy / Learn — all filled rainbow.',
    antiPattern: 'cta-overload | weak-cta',
    executionHint: 'Primary filled, secondaries outline/text.',
    verification: '≤1 filled primary CTA per section.',
    relatedRules: ['DP-002'], tags: ['cta'],
  },
  {
    id: 'AP-004', domain: '15-anti-patterns', title: 'Inconsistent typography and colors',
    rule: 'Do not change fonts, heading scales, or primary colors between sections.',
    why: 'Inconsistency is the top “template dump” signal.',
    whenToUse: 'Visual QA.',
    whenNotToUse: 'Intentional accent sections still share base type/color roles.',
    goodExample: 'Global Inter + teal primary everywhere.',
    badExample: 'Hero serif gold, services sans blue, footer mono green.',
    antiPattern: 'inconsistent-typography | random-colors',
    executionHint: 'Inherit designSystem; forbid random hex in section styles.',
    verification: 'Sample type + color roles across ≥3 sections.',
    relatedRules: ['VC-001'], tags: ['typography', 'color'],
  },
  {
    id: 'AP-005', domain: '15-anti-patterns', title: 'Oversized headings and tiny body',
    rule: 'H1 not so large it wraps to 6 lines on desktop; body not below ~16px; maintain ratio.',
    why: 'Extreme scales hurt hierarchy and readability.',
    whenToUse: 'Type QA.',
    whenNotToUse: 'Display moments still respect line length.',
    goodExample: 'H1 48–64 desktop, body 16–18.',
    badExample: 'H1 120px broken mid-phrase; body 12px light gray.',
    antiPattern: 'oversized-heading | tiny-body-text',
    executionHint: 'Clamp font sizes; check mobile scale.',
    verification: 'H1 line count and body size within scale.',
    relatedRules: ['TY-001'], tags: ['typography'],
  },
  {
    id: 'AP-006', domain: '15-anti-patterns', title: 'Whitespace extremes',
    rule: 'Fix both glued sections (insufficient gap) and vast voids (excessive unexplained gap).',
    why: 'Both look unfinished.',
    whenToUse: 'Spacing QA after assembly.',
    whenNotToUse: 'Intentional whitespace still has alignment and purpose.',
    goodExample: 'Even section cadence 64–96px.',
    badExample: '0px between cards bands; 400px empty hero bottom.',
    antiPattern: 'insufficient-whitespace | excessive-whitespace',
    executionHint: 'Normalize section padding tokens; remove empty spacers.',
    verification: 'emptyish=0; overlaps=0 in structural audit.',
    relatedRules: ['SP-002'], tags: ['spacing'],
  },
  {
    id: 'AP-007', domain: '15-anti-patterns', title: 'Meaningless galleries and repetitive sections',
    rule: 'Galleries need real media roles; do not stack near-identical sections.',
    why: 'Padding content with duplicates erodes trust.',
    whenToUse: 'Structure QA.',
    whenNotToUse: 'Portfolio/restaurant may have multiple galleries if content differs.',
    goodExample: 'One strong portfolio grid with captions.',
    badExample: 'Three identical “feature” sections with synonym titles.',
    antiPattern: 'meaningless-galleries | repetitive-sections',
    executionHint: 'Deduplicate section roles in plan; skip gallery without mediaNeeds.',
    verification: 'No duplicate role+heading pairs.',
    relatedRules: ['AP-001'], tags: ['gallery', 'structure'],
  },
  {
    id: 'AP-008', domain: '15-anti-patterns', title: 'Poor mobile composition',
    rule: 'Do not ship desktop-only layouts: no horizontal scroll, readable type, reachable CTA.',
    why: 'Majority of local traffic is mobile.',
    whenToUse: 'Responsive QA.',
    whenNotToUse: '—',
    goodExample: 'Stacked columns, full-width CTA, hamburger nav.',
    badExample: '4-col grid at 360px, 10px text, CTA below 3 screens.',
    antiPattern: 'poor-mobile-composition',
    executionHint: 'Apply responsiveStrategy; verify at 360/768/1440.',
    verification: 'Viewport tests: no overflow; CTA in first screen.',
    relatedRules: ['RD-001'], tags: ['mobile', 'responsive'],
  },
  {
    id: 'AP-009', domain: '15-anti-patterns', title: 'Orphan components and empty containers',
    rule: 'Every component has content and a parent context; no empty boxes or floating leftovers.',
    why: 'Orphans signal incomplete assembly.',
    whenToUse: 'Post-generation structural audit.',
    whenNotToUse: '—',
    goodExample: 'All sections non-empty; children have text.',
    badExample: 'Empty card grid cells; spacer-only sections.',
    antiPattern: 'orphan-components | empty-containers',
    executionHint: 'Verify node text density; remove empty section plans.',
    verification: 'emptyish=0; placeholder count=0.',
    relatedRules: ['IA-002'], tags: ['structure', 'empty'],
  },
  {
    id: 'AP-010', domain: '15-anti-patterns', title: 'Overdone gradients and visual noise',
    rule: 'Limit gradients/glow/noise to brand moments; never behind dense body text.',
    why: 'Noise reduces readability and conversion focus.',
    whenToUse: 'Accent backgrounds only.',
    whenNotToUse: 'Body copy sections, forms, pricing tables.',
    goodExample: 'Subtle gradient CTA band with high-contrast text.',
    badExample: 'Animated rainbow mesh behind every paragraph.',
    antiPattern: 'excessive-gradients | visual-noise',
    executionHint: 'experienceStrategy intensity subtle by default; mesh/particles opt-in.',
    verification: 'Body sections have calm backgrounds.',
    relatedRules: ['DP-008'], tags: ['gradients', 'noise'],
  },
];
