import type { KnowledgeEntry, QaCheck } from '../types';

export const QA_CHECKS: QaCheck[] = [
  { id: 'QA-C-01', category: 'CONTENT', question: 'Any lorem ipsum or placeholder strings?', failSignal: 'placeholder-match found', fixHint: 'Replace with industry-plausible copy via overlay.', tags: ['core', 'content'] },
  { id: 'QA-C-02', category: 'CONTENT', question: 'Headlines state clear value/offer?', failSignal: 'vague welcome-only headings', fixHint: 'Rewrite to outcome + audience specificity.', tags: ['core', 'content'] },
  { id: 'QA-C-03', category: 'CONTENT', question: 'Primary CTA label is verb+object and industry-native?', failSignal: 'mismatched or empty CTA', fixHint: 'Use industry pattern.commonCta / brief CTA.', tags: ['core', 'content', 'cta'] },
  { id: 'QA-S-01', category: 'STRUCTURE', question: 'Navbar and footer present?', failSignal: 'missing frame sections', fixHint: 'Insert navbar first, footer last.', tags: ['core', 'structure'] },
  { id: 'QA-S-02', category: 'STRUCTURE', question: 'Section count matches goal (no sprawl/duplicates)?', failSignal: 'duplicate roles or >12 content sections', fixHint: 'Deduplicate and drop non-goal sections.', tags: ['core', 'structure'] },
  { id: 'QA-S-03', category: 'STRUCTURE', question: 'Hero contains value + CTA?', failSignal: 'hero without CTA', fixHint: 'Overlay hero heading/sub/CTA.', tags: ['core', 'structure', 'hero'] },
  { id: 'QA-D-01', category: 'DESIGN', question: 'Single visual direction across sections?', failSignal: 'mixed style languages', fixHint: 'Align to designSystem + visualDirection.', tags: ['core', 'design'] },
  { id: 'QA-D-02', category: 'DESIGN', question: 'No overlapping elements?', failSignal: 'overlaps>0', fixHint: 'Fix spacing/absolute positioning.', tags: ['core', 'design'] },
  { id: 'QA-T-01', category: 'TYPOGRAPHY', question: 'Type scale within hierarchy (no random sizes)?', failSignal: 'heading sizes unbounded', fixHint: 'Normalize to scale steps.', tags: ['core', 'typography'] },
  { id: 'QA-T-02', category: 'TYPOGRAPHY', question: 'Body readable (size, line-height, line length)?', failSignal: 'tiny body or huge line length', fixHint: '16–18px, lh 1.5–1.7, max ~65ch.', tags: ['core', 'typography'] },
  { id: 'QA-CL-01', category: 'COLOR', question: 'Primary/CTA colors consistent with designSystem?', failSignal: 'random hex per section', fixHint: 'Reapply designSystem tokens.', tags: ['core', 'color'] },
  { id: 'QA-CL-02', category: 'COLOR', question: 'Text contrast adequate?', failSignal: 'low-contrast pairs', fixHint: 'Adjust text/bg or add scrim.', tags: ['core', 'color', 'accessibility'] },
  { id: 'QA-SP-01', category: 'SPACING', question: 'Section spacing even and sufficient?', failSignal: 'glued or huge voids', fixHint: 'Normalize section padding.', tags: ['core', 'spacing'] },
  { id: 'QA-SP-02', category: 'SPACING', question: 'Component padding within scale?', failSignal: 'cramped controls', fixHint: 'Apply spacing scale to buttons/cards.', tags: ['core', 'spacing'] },
  { id: 'QA-M-01', category: 'MEDIA', question: 'Images have role + relevance + consistent ratios?', failSignal: 'empty/irrelevant/mixed ratios', fixHint: 'Fix slots or remove gallery.', tags: ['core', 'media'] },
  { id: 'QA-U-01', category: 'UX', question: 'Primary goal CTA discoverable (hero + repeat)?', failSignal: 'CTA buried', fixHint: 'Add CTA to nav/hero/mid/footer.', tags: ['core', 'ux', 'cta'] },
  { id: 'QA-U-02', category: 'UX', question: 'Trust elements before final ask (lead-gen)?', failSignal: 'no testimonials/proof', fixHint: 'Insert testimonials/stats before CTA.', tags: ['core', 'ux', 'trust'] },
  { id: 'QA-R-01', category: 'RESPONSIVE', question: 'No horizontal overflow on mobile?', failSignal: 'scroll-x at 360px', fixHint: 'Stack columns, constrain widths.', tags: ['core', 'responsive'] },
  { id: 'QA-R-02', category: 'RESPONSIVE', question: 'Primary CTA visible on first mobile screen?', failSignal: 'CTA off-screen', fixHint: 'Full-width hero CTA / sticky.', tags: ['core', 'responsive', 'cta'] },
  { id: 'QA-A-01', category: 'ACCESSIBILITY', question: 'Heading hierarchy logical (one H1)?', failSignal: 'skipped/duplicate H1', fixHint: 'Fix heading levels.', tags: ['core', 'accessibility'] },
  { id: 'QA-A-02', category: 'ACCESSIBILITY', question: 'Buttons/links clear and large enough?', failSignal: 'tiny/ambiguous targets', fixHint: 'Increase padding, clarify labels.', tags: ['core', 'accessibility'] },
  { id: 'QA-TQ-01', category: 'TECHNICAL', question: 'No fake SUCCESS (mutations > 0 when claiming done)?', failSignal: 'success without mutation', fixHint: 'Honest fail — rerun execution.', tags: ['core', 'technical'] },
  { id: 'QA-TQ-02', category: 'TECHNICAL', question: 'No batch_execute leak in request tools?', failSignal: 'batch_execute present', fixHint: 'Restrict tool surface.', tags: ['core', 'technical'] },
  { id: 'QA-TQ-03', category: 'TECHNICAL', question: 'Console errors = 0 during generation?', failSignal: 'console errors', fixHint: 'Investigate failing tool/overlay.', tags: ['core', 'technical'] },
];

export const QA_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'QA-001', domain: '16-quality-assurance', title: 'Run full QA checklist before complete',
    rule: 'HACP must evaluate CONTENT, STRUCTURE, DESIGN, TYPOGRAPHY, COLOR, SPACING, MEDIA, UX, RESPONSIVE, ACCESSIBILITY, TECHNICAL before declaring a site finished.',
    why: 'Completion without QA is unverified success.',
    whenToUse: 'End of every generation, before “complete”.',
    whenNotToUse: 'Do not claim QA_PASS without running checks.',
    goodExample: 'Checklist executed; issues fixed; then complete.',
    badExample: '“Strona gotowa” with placeholders and overlaps.',
    antiPattern: 'fake-success-qa',
    executionHint: 'DecisionContext.qaChecks drive final verification pass.',
    verification: 'QA category coverage present in DecisionContext; structural checks pass.',
    relatedRules: ['QA-002'], tags: ['qa', 'core', 'checklist'],
  },
  {
    id: 'QA-002', domain: '16-quality-assurance', title: 'Self-correction loop',
    rule: 'On QA fail: diagnose (symptom→cause), apply fix (anti-pattern FIX), re-verify — do not ignore or redeclare success.',
    why: 'Professional output requires iterate-until-pass.',
    whenToUse: 'Any failed QA or structural check.',
    whenNotToUse: 'Do not “fix” by deleting required sections wholesale.',
    goodExample: 'Placeholder found → overlay real copy → rescan = 0.',
    badExample: 'Overlap found → declare done anyway.',
    executionHint: 'Soft tool failures → retry/alternate; content fails → overlay; structure fails → adjust plan.',
    verification: 'Re-run failed check → PASS before complete.',
    relatedRules: ['AP-002'], tags: ['qa', 'correction', 'core'],
  },
  {
    id: 'QA-003', domain: '16-quality-assurance', title: 'Anti-fake knowledge and QA claims',
    rule: 'Never claim “applied rule X” without DecisionContext evidence; never claim QA/visual audit without executed checks.',
    why: 'Fake knowledge claims poison trust in HACP.',
    whenToUse: 'Reporting and completion messages.',
    whenNotToUse: '—',
    goodExample: 'Report cites retrieved entryIds + check results.',
    badExample: '“Zastosowałem zasadę hierarchy” with empty retrievalLog.',
    antiPattern: 'fake-retrieval | fake-qa-claim',
    executionHint: 'retrievalLog must be non-empty if knowledge is cited.',
    verification: 'Knowledge claims ↔ DecisionContext.entryIds / qaChecks.',
    relatedRules: ['QA-001'], tags: ['qa', 'honesty', 'core'],
  },
];
