import type { KnowledgeEntry, WebsiteBlueprint } from '../types';

export const WEBSITE_BLUEPRINTS: WebsiteBlueprint[] = [
  {
    id: 'BP-dental-clinic', name: 'Dental clinic',
    businessGoal: 'Book appointments; establish clinical trust',
    informationArchitecture: ['navbar', 'hero', 'services', 'about', 'team', 'testimonials', 'cta', 'contact', 'footer'],
    content: ['specialization services', 'comfort/pain-free messaging', 'team credentials', 'patient quotes', 'booking CTA'],
    components: ['hero-split', 'service-grid', 'team', 'testimonials', 'cta-block', 'contact'],
    designDirection: 'clean trust teal/blue, soft radius, clinic photography',
    cta: 'Umów wizytę',
    media: ['clinic interior', 'team', 'smile results', 'service icons'],
    qa: ['placeholder=0', 'booking CTA in hero+mid+footer', 'trust before final CTA', 'contrast AA'],
    tags: ['dentist', 'dental', 'clinic', 'medical', 'stomatolog'],
  },
  {
    id: 'BP-restaurant', name: 'Restaurant',
    businessGoal: 'Drive reservations and menu views',
    informationArchitecture: ['navbar', 'hero', 'menu', 'about', 'gallery', 'testimonials', 'contact', 'footer'],
    content: ['menu highlights', 'story', 'hours/address', 'reservation CTA'],
    components: ['hero-photo', 'feature/menu', 'gallery', 'testimonials', 'contact'],
    designDirection: 'warm food photography, appetizing palette',
    cta: 'Zarezerwuj stolik',
    media: ['food', 'interior', 'dishes'],
    qa: ['hours visible', 'reservation path clear', 'food image ratios consistent'],
    tags: ['restaurant', 'food', 'menu', 'cafe'],
  },
  {
    id: 'BP-real-estate', name: 'Real estate',
    businessGoal: 'Generate viewing leads; showcase listings',
    informationArchitecture: ['navbar', 'hero', 'listings', 'about', 'process', 'testimonials', 'contact', 'footer'],
    content: ['listing previews', 'area strengths', 'agent trust', 'viewing CTA'],
    components: ['hero', 'property grid', 'process steps', 'testimonials', 'contact'],
    designDirection: 'premium neutral, large property imagery',
    cta: 'Umów prezentację',
    media: ['exteriors', 'interiors', 'agent portrait'],
    qa: ['listing images large enough', 'contact/CTA repeated', 'no empty cards'],
    tags: ['realestate', 'property', 'nieruchomości'],
  },
  {
    id: 'BP-creative-agency', name: 'Creative agency',
    businessGoal: 'Win projects via demonstrated craft',
    informationArchitecture: ['navbar', 'hero', 'work', 'services', 'about', 'testimonials', 'contact', 'footer'],
    content: ['case studies with outcomes', 'services', 'POV/philosophy', 'contact'],
    components: ['hero-bold', 'portfolio', 'service-grid', 'testimonials', 'cta'],
    designDirection: 'bold editorial, strong brand type',
    cta: 'Zacznijmy projekt',
    media: ['case visuals', 'campaign shots'],
    qa: ['work dominates', 'one clear contact path', 'consistent type voice'],
    tags: ['agency', 'creative', 'design studio'],
  },
  {
    id: 'BP-photographer', name: 'Photographer',
    businessGoal: 'Show portfolio and book sessions',
    informationArchitecture: ['navbar', 'hero', 'gallery', 'packages', 'about', 'contact', 'footer'],
    content: ['selected work', 'session packages', 'style bio', 'booking'],
    components: ['hero-image', 'portfolio grid', 'pricing/services', 'contact'],
    designDirection: 'image-first minimal chrome',
    cta: 'Zarezerwuj sesję',
    media: ['hero portfolio', 'series galleries'],
    qa: ['consistent aspect ratios', 'UI does not compete with photos', 'booking CTA present'],
    tags: ['photography', 'portfolio', 'fotograf'],
  },
  {
    id: 'BP-saas', name: 'SaaS product',
    businessGoal: 'Start free trial / demo',
    informationArchitecture: ['navbar', 'hero', 'features', 'pricing', 'testimonials', 'cta', 'footer'],
    content: ['outcome-led value prop', 'feature benefits', 'clear pricing', 'social proof'],
    components: ['hero-product', 'feature-grid', 'pricing', 'testimonials', 'cta'],
    designDirection: 'product screenshots, modern clean',
    cta: 'Wypróbuj za darmo',
    media: ['app screenshots', 'logo wall'],
    qa: ['pricing discoverable', 'trial CTA repeated', 'no feature dump without outcomes'],
    tags: ['saas', 'software', 'app', 'platform'],
  },
  {
    id: 'BP-architecture-studio', name: 'Architecture studio',
    businessGoal: 'Attract project inquiries through portfolio',
    informationArchitecture: ['navbar', 'hero', 'portfolio', 'about', 'process', 'contact', 'footer'],
    content: ['project narratives', 'philosophy', 'team', 'inquiry CTA'],
    components: ['hero-editorial', 'portfolio', 'about', 'contact'],
    designDirection: 'editorial minimal, photography-led',
    cta: 'Porozmawiajmy',
    media: ['project photography', 'details/plans'],
    qa: ['images large', 'captions present', 'contact clear'],
    tags: ['architecture', 'studio', 'design'],
  },
  {
    id: 'BP-local-service', name: 'Local service business',
    businessGoal: 'Calls and bookings from nearby customers',
    informationArchitecture: ['navbar', 'hero', 'services', 'about', 'testimonials', 'contact', 'footer'],
    content: ['service list', 'service area', 'reviews', 'phone/booking'],
    components: ['hero-local', 'service-grid', 'testimonials', 'contact'],
    designDirection: 'friendly trustworthy, phone-forward',
    cta: 'Zadzwoń',
    media: ['local team', 'service photos'],
    qa: ['phone visible early', 'service area stated', 'mobile CTA thumb-reachable'],
    tags: ['local', 'service', 'uslugi'],
  },
  {
    id: 'BP-ecommerce', name: 'Ecommerce storefront',
    businessGoal: 'Product sales and checkout',
    informationArchitecture: ['navbar', 'hero', 'products', 'benefits', 'testimonials', 'cta', 'footer'],
    content: ['product grid', 'offers', 'shipping/trust', 'policies'],
    components: ['hero-offer', 'product grid', 'benefits', 'testimonials'],
    designDirection: 'product photography first, price hierarchy',
    cta: 'Kup teraz',
    media: ['product shots', 'lifestyle'],
    qa: ['prices legible', 'trust badges/shipping info', 'no promo clutter'],
    tags: ['ecommerce', 'shop', 'store', 'sklep'],
  },
  {
    id: 'BP-portfolio', name: 'Personal portfolio',
    businessGoal: 'Land clients/jobs via work + contact',
    informationArchitecture: ['navbar', 'hero', 'work', 'about', 'contact', 'footer'],
    content: ['project highlights', 'short bio', 'skills/services', 'contact'],
    components: ['hero-personal', 'portfolio', 'about', 'cta'],
    designDirection: 'personal brand, work-first',
    cta: 'Napisz do mnie',
    media: ['project covers'],
    qa: ['work above the fold-ish', 'contact never hidden', 'consistent personal brand'],
    tags: ['portfolio', 'personal', 'freelance'],
  },
];

export const BLUEPRINT_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'BP-001', domain: '17-website-blueprints', title: 'Blueprints are maps, not molds',
    rule: 'Blueprint shows BUSINESS GOAL → IA → CONTENT → COMPONENTS → DESIGN → CTA → MEDIA → QA path; adapt to brief — never paste blindly.',
    why: 'Blueprints accelerate decisions without removing judgment.',
    whenToUse: 'When brief matches a known pattern as starting skeleton.',
    whenNotToUse: 'When brief contradicts blueprint goals.',
    goodExample: 'Dental blueprint + implantology specialization from brief.',
    badExample: 'Ignoring brief and emitting fixed blueprint section list only.',
    executionHint: 'Merge blueprint IA with brief-driven section pruning/additions.',
    verification: 'Plan reflects both blueprint defaults and brief overrides.',
    relatedRules: ['IP-001', 'IA-001'], tags: ['blueprint', 'core'],
  },
];
