import type { KnowledgeEntry, TrainingCase } from '../types';

export const TRAINING_CASES: TrainingCase[] = [
  {
    id: 'TC-01', level: 1,
    brief: 'Prosta strona usługowa dla hydraulika — jedna usługa hydrauliczna w mieście, cel: telefony.',
    business: 'local plumbing', audience: 'homeowners', goal: 'phone calls',
    expectedDecisions: ['local-service pattern', 'single primary CTA=Zadzwoń', 'lean sections'],
    expectedStructure: ['navbar', 'hero', 'services', 'testimonials', 'contact', 'footer'],
    contentRequirements: ['service list', 'service area', 'phone CTA'], designDirection: 'friendly trustworthy',
    mediaNeeds: ['local work photos'], cta: 'Zadzwoń',
    qualityChecks: ['phone visible', 'no placeholders', 'mobile CTA'],
    commonFailureModes: ['too many sections', 'no trust', 'buried phone'],
    tags: ['level1', 'local', 'simple'],
  },
  {
    id: 'TC-02', level: 1,
    brief: 'Landing page dla webinara o marketingu — zapisy.',
    business: ' webinar', audience: 'marketers', goal: 'registrations',
    expectedDecisions: ['landing-page purpose', 'single form CTA', 'few sections'],
    expectedStructure: ['navbar', 'hero', 'benefits', 'cta', 'footer'],
    contentRequirements: ['value bullets', 'date/speaker', 'signup CTA'], designDirection: 'bold modern',
    mediaNeeds: ['speaker photo'], cta: 'Zapisz się',
    qualityChecks: ['one primary CTA', 'form friction low'], commonFailureModes: ['CTA overload', 'no agenda clarity'],
    tags: ['level1', 'landing', 'simple'],
  },
  {
    id: 'TC-03', level: 1,
    brief: 'Portfolio fotografa ślubnego — galeria i kontakt.',
    business: 'wedding photography', audience: 'couples', goal: 'booking inquiries',
    expectedDecisions: ['image-first', 'minimal chrome', 'gallery with consistent ratios'],
    expectedStructure: ['navbar', 'hero', 'portfolio', 'about', 'contact', 'footer'],
    contentRequirements: ['style statement', 'packages optional', 'contact'], designDirection: 'editorial romantic',
    mediaNeeds: ['wedding series'], cta: 'Zapytaj o termin',
    qualityChecks: ['ratios consistent', 'photos dominate'], commonFailureModes: ['UI competes with photos', 'mixed ratios'],
    tags: ['level1', 'photography'],
  },
  {
    id: 'TC-04', level: 2,
    brief: 'Wielosekcyjna strona szkoły językowej — kursy, lektorzy, cennik, zapisy.',
    business: 'language school', audience: 'students/parents', goal: 'course signups',
    expectedDecisions: ['informational+booking mix', 'courses as services', 'pricing present'],
    expectedStructure: ['navbar', 'hero', 'courses', 'about', 'team', 'pricing', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['course list', 'levels', 'teachers', 'prices'], designDirection: 'friendly professional education',
    mediaNeeds: ['classroom', 'teachers'], cta: 'Zapisz się na kurs',
    qualityChecks: ['pricing readable', 'signup path clear'], commonFailureModes: ['course walls of text', 'weak CTA'],
    tags: ['level2', 'education'],
  },
  {
    id: 'TC-05', level: 2,
    brief: 'Strona kancelarii adwokackiej — prawo rodzinne i karne, formularz kontaktowy.',
    business: 'law firm', audience: 'clients with legal issues', goal: 'consultations',
    expectedDecisions: ['authoritative navy', 'practice areas as services', 'attorney trust'],
    expectedStructure: ['navbar', 'hero', 'services', 'about', 'team', 'testimonials', 'contact', 'footer'],
    contentRequirements: ['practice areas', 'credentials', 'contact'], designDirection: 'formal trustworthy',
    mediaNeeds: ['portraits', 'office'], cta: 'Skonsultuj sprawę',
    qualityChecks: ['tone formal', 'phone/email visible'], commonFailureModes: ['cold unapproachable', 'no bios'],
    tags: ['level2', 'law'],
  },
  {
    id: 'TC-06', level: 2,
    brief: 'Strona restauracji włoskiej z galerią dań i rezerwacją.',
    business: 'restaurant', audience: 'diners', goal: 'reservations + menu views',
    expectedDecisions: ['warm palette', 'menu section', 'gallery ratios'],
    expectedStructure: ['navbar', 'hero', 'menu', 'gallery', 'about', 'contact', 'footer'],
    contentRequirements: ['menu highlights', 'hours', 'address'], designDirection: 'warm appetizing',
    mediaNeeds: ['food', 'interior'], cta: 'Zarezerwuj stolik',
    qualityChecks: ['hours visible', 'food ratios'], commonFailureModes: ['menu text wall', 'stock-only feel'],
    tags: ['level2', 'restaurant'],
  },
  {
    id: 'TC-07', level: 3,
    brief: 'Silny brand direction: minimalistyczne luxury studio projektowe — dużo whitespace, serif, monochrom.',
    business: 'design studio', audience: 'premium clients', goal: 'project inquiries with brand aura',
    expectedDecisions: ['enforce luxury minimal everywhere', 'restraint over feature count', 'editorial type'],
    expectedStructure: ['navbar', 'hero', 'work', 'approach', 'contact', 'footer'],
    contentRequirements: ['short manifesto', 'selected work', 'contact'], designDirection: 'luxury minimal monochrome serif',
    mediaNeeds: ['high-contrast project photos'], cta: 'Porozmawiajmy',
    qualityChecks: ['no random gradients', 'whitespace intentional', 'type consistent'],
    commonFailureModes: ['SaaS cards breaking luxury', 'excessive decoration', 'inconsistent radius'],
    tags: ['level3', 'brand', 'luxury'],
  },
  {
    id: 'TC-08', level: 3,
    brief: 'Playful kids club — jasne kolory, zaokrąglenia, angażujące CTA dla rodziców.',
    business: 'kids club', audience: 'parents', goal: 'trial signups',
    expectedDecisions: ['playful friendly direction consistent', 'parent-focused trust + fun visuals'],
    expectedStructure: ['navbar', 'hero', 'activities', 'benefits', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['activities', 'safety/trust', 'trial offer'], designDirection: 'playful rounded bright',
    mediaNeeds: ['kids activities (tasteful)', 'space photos'], cta: 'Zapisz dziecko na próbne',
    qualityChecks: ['readability for parents', 'contrast still AA'], commonFailureModes: ['too childish for parent buyer', 'low contrast pastel text'],
    tags: ['level3', 'playful'],
  },
  {
    id: 'TC-09', level: 3,
    brief: 'Dark futuristic fintech — neon accents, techy copy, product UI forward.',
    business: 'fintech app', audience: 'tech-savvy users', goal: 'app downloads/registrations',
    expectedDecisions: ['dark system coherent', 'product UI hero', 'security trust signals'],
    expectedStructure: ['navbar', 'hero', 'features', 'security', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['value props', 'security', 'how it works'], designDirection: 'dark futuristic neon-accent',
    mediaNeeds: ['app UI'], cta: 'Pobierz aplikację',
    qualityChecks: ['neon not behind body text', 'contrast'], commonFailureModes: ['visual noise', 'unreadable glow text'],
    tags: ['level3', 'fintech', 'dark'],
  },
  {
    id: 'TC-10', level: 4,
    brief: 'Gabinet stomatologiczny specjalizujący się w implantologii i stomatologii estetycznej; cel: umówienie wizyty.',
    business: 'dental implantology clinic', audience: 'patients needing implants/aesthetic care', goal: 'book appointments',
    expectedDecisions: ['dental industry pattern', 'specializations in services+hero', 'trust+booking CTA ladder'],
    expectedStructure: ['navbar', 'hero', 'services', 'about', 'team', 'testimonials', 'cta', 'contact', 'footer'],
    contentRequirements: ['implantology/aesthetic services', 'comfort messaging', 'team', 'quotes'], designDirection: 'clean trust teal/blue',
    mediaNeeds: ['clinic', 'team', 'smile results'], cta: 'Umów wizytę',
    qualityChecks: ['specialization terms present', 'placeholder=0', 'CTA booking vocabulary', 'QA checklist'],
    commonFailureModes: ['generic dentist copy missing specializations', 'weak CTA', 'scary clinical imagery'],
    tags: ['level4', 'dentist', 'dental', 'implantology', 'medical'],
  },
  {
    id: 'TC-11', level: 4,
    brief: 'Kancelaria patentowa B2B — skomplikowana specjalizacja, decydenci prawnicy i inżynierowie.',
    business: 'patent law', audience: 'inventors/companies', goal: 'qualified consultations',
    expectedDecisions: ['authoritative precise tone', 'expertise-first structure', 'low hype'],
    expectedStructure: ['navbar', 'hero', 'services', 'cases', 'team', 'contact', 'footer'],
    contentRequirements: ['IP services', 'credentials', 'process'], designDirection: 'corporate precise',
    mediaNeeds: ['team', 'subtle tech visuals'], cta: 'Umów konsultację',
    qualityChecks: ['jargon explained', 'contact clear'], commonFailureModes: ['buzzword soup', 'marketing-fluffy tone'],
    tags: ['level4', 'law', 'b2b', 'patent'],
  },
  {
    id: 'TC-12', level: 4,
    brief: 'SaaS dla laboratoriów medycznych — regulacje, integracje, zaufanie instytucjonalne.',
    business: 'lab SaaS', audience: 'lab managers', goal: 'demo requests',
    expectedDecisions: ['technical credibility', 'compliance signals', 'product UI'],
    expectedStructure: ['navbar', 'hero', 'features', 'integrations', 'security', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['integrations', 'compliance', 'ROI outcomes'], designDirection: 'clean technical medical-adjacent',
    mediaNeeds: ['dashboard UI'], cta: 'Umów demo',
    qualityChecks: ['claims specific', 'no fake certifications'], commonFailureModes: ['generic SaaS boilerplate', 'missing compliance context'],
    tags: ['level4', 'saas', 'medical', 'b2b'],
  },
  {
    id: 'TC-13', level: 4,
    brief: 'Biuro architektoniczne z nagrodami — portfolio musi dominować, teksty krótkie.',
    business: 'award architecture studio', audience: 'developers/clients', goal: 'RFP/inquiries',
    expectedDecisions: ['photography-led IA', 'short editorial copy', 'awards as trust'],
    expectedStructure: ['navbar', 'hero', 'portfolio', 'awards', 'about', 'contact', 'footer'],
    contentRequirements: ['project blurbs', 'awards list'], designDirection: 'editorial minimal',
    mediaNeeds: ['large project photos'], cta: 'Omów inwestycję',
    qualityChecks: ['images dominant', 'captions present'], commonFailureModes: ['text-heavy clutter', 'small images'],
    tags: ['level4', 'architecture'],
  },
  {
    id: 'TC-14', level: 5,
    brief: 'Kompleksowy brief: sieć klinik weterynaryjnych 3 miasta, 2 językiPL/EN, booking online, promocje, blog, zespół 20 lekarzy.',
    business: 'multi-clinic vet network', audience: 'pet owners', goal: 'bookings + content marketing',
    expectedDecisions: ['multi-location structure', 'booking primary + blog secondary', 'scalable IA'],
    expectedStructure: ['navbar', 'hero', 'services', 'locations', 'team', 'blog teaser', 'testimonials', 'cta', 'contact', 'footer'],
    contentRequirements: ['location list', 'services', 'team scale story', 'promo slot'], designDirection: 'friendly medical warm',
    mediaNeeds: ['clinics', 'vets with pets', 'locations'], cta: 'Umów wizytę',
    qualityChecks: ['locations scannable', 'booking repeated', 'no section sprawl beyond goal'],
    commonFailureModes: ['too many sections', 'promo noise', 'duplicate service bands'],
    tags: ['level5', 'clinic', 'network', 'complex'],
  },
  {
    id: 'TC-15', level: 5,
    brief: 'Marka D2C kosmetyków naturalnych — sklep, historia marki, wartości eko, sezonowe kampanie, newsletter.',
    business: 'D2C cosmetics ecommerce', audience: 'eco-conscious buyers', goal: 'sales + list growth',
    expectedDecisions: ['ecommerce structure + brand story', 'newsletter secondary', 'product photography priority'],
    expectedStructure: ['navbar', 'hero', 'products', 'values', 'story', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['product highlights', 'ingredients/values', 'offer'], designDirection: 'natural soft earthy',
    mediaNeeds: ['product', 'ingredients', 'lifestyle'], cta: 'Kup teraz',
    qualityChecks: ['price hierarchy', 'trust', 'no promo clutter'], commonFailureModes: ['banner chaos', 'weak product shots', 'inconsistent brand'],
    tags: ['level5', 'ecommerce', 'beauty', 'complex'],
  },
  {
    id: 'TC-16', level: 5,
    brief: 'Platforma edukacyjna B2B2C: dla szkół i rodziców — dwie audiencje, dwie ścieżki konwersji.',
    business: 'edtech platform', audience: 'schools + parents', goal: 'dual demos/signups',
    expectedDecisions: ['dual-audience IA clarity', 'segmented CTAs without chaos', 'trust institutional'],
    expectedStructure: ['navbar', 'hero', 'for-schools', 'for-parents', 'features', 'proof', 'cta', 'footer'],
    contentRequirements: ['two value props', 'security/privacy', 'case schools'], designDirection: 'modern approachable education',
    mediaNeeds: ['product UI', 'classroom'], cta: 'Wypróbuj dla szkoły / dla rodzica',
    qualityChecks: ['audiences not confused', 'CTA hierarchy clear'], commonFailureModes: ['muddy dual messaging', 'CTA overload', 'generic copy'],
    tags: ['level5', 'education', 'saas', 'complex', 'dual-audience'],
  },
  {
    id: 'TC-17', level: 5,
    brief: 'Restauracja fine dining z rezerwacjami VIP i wydarzeniami prywatnymi — dwa segmenty gośći.',
    business: 'fine dining', audience: 'diners + event planners', goal: 'reservations + private event leads',
    expectedDecisions: ['elevated visual direction', 'events section separate from menu', 'reservation CTA primary'],
    expectedStructure: ['navbar', 'hero', 'menu philosophy', 'events', 'gallery', 'reservations', 'contact', 'footer'],
    contentRequirements: ['chef story', 'private events', 'hours/location'], designDirection: 'elegant editorial dark-warm',
    mediaNeeds: ['plated food', 'interior'], cta: 'Zarezerwuj stolik',
    qualityChecks: ['two audiences served', 'tone elevated consistent'], commonFailureModes: ['casual tone mismatch', 'events buried', 'stock food clichés only'],
    tags: ['level5', 'restaurant', 'events', 'complex'],
  },
  {
    id: 'TC-18', level: 5,
    brief: 'Startup hardware z crowdfoundingiem — story produktu, specyfikacja, roadmapa, media kit dla prasy.',
    business: 'hardware startup', audience: 'backers + press', goal: 'campaign support + press',
    expectedDecisions: ['product-hero storytelling', 'specs scannable', 'press section'],
    expectedStructure: ['navbar', 'hero', 'product', 'specs', 'story', 'press', 'cta', 'footer'],
    contentRequirements: ['problem/solution', 'specs table highlights', 'press assets'], designDirection: 'bold product-tech',
    mediaNeeds: ['product renders', 'founder'], cta: 'Wesprzyj kampanię',
    qualityChecks: ['specs readable', 'CTA campaign-aligned'], commonFailureModes: ['spec walls', 'weak story', 'hidden campaign CTA'],
    tags: ['level5', 'startup', 'hardware', 'complex'],
  },
  {
    id: 'TC-19', level: 5,
    brief: 'Organizacja non-profit z darami, wolontariatem i wpływem (stats) — trzy ścieżki konwersji priorytetyzowane.',
    business: 'nonprofit', audience: 'donors/volunteers', goal: 'donations primary, volunteer secondary',
    expectedDecisions: ['donation CTA primary', 'impact stats trust', 'volunteer secondary not competing filled CTA'],
    expectedStructure: ['navbar', 'hero', 'mission', 'impact', 'programs', 'stories', 'cta', 'footer'],
    contentRequirements: ['impact numbers', 'programs', 'donation path'], designDirection: 'hopeful trustworthy green/warm',
    mediaNeeds: ['field photos', 'beneficiaries (ethical)'], cta: 'Wesprzyj nas',
    qualityChecks: ['CTA hierarchy', 'stats believable units'], commonFailureModes: ['CTA overload equal weight', 'guilt-trip visual noise', 'no impact proof'],
    tags: ['level5', 'nonprofit', 'complex'],
  },
  {
    id: 'TC-20', level: 5,
    brief: 'Marka modowa z lookbookiem, e-sklepem i historią zrównoważonego rozwoju — balans sprzedaż vs narracja.',
    business: 'fashion ecommerce', audience: 'style-conscious shoppers', goal: 'sales with brand depth',
    expectedDecisions: ['editorial brand sections + product grid', 'sustainability as trust not greenwash spam', 'mobile commerce critical'],
    expectedStructure: ['navbar', 'hero', 'products', 'lookbook', 'values', 'testimonials', 'cta', 'footer'],
    contentRequirements: ['product highlights', 'sustainability specifics', 'offer'], designDirection: 'editorial fashion monochrome+accent',
    mediaNeeds: ['lookbook', 'product'], cta: 'Kup kolekcję',
    qualityChecks: ['mobile shop usability', 'consistent brand', 'prices clear'], commonFailureModes: ['editorial mess blocking shop', 'inconsistent type', 'tiny product info'],
    tags: ['level5', 'ecommerce', 'fashion', 'complex'],
  },
];

export const TRAINING_CASE_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'TC-000', domain: '18-training-cases', title: 'Training cases encode expected decisions',
    rule: 'Each case maps BRIEF → expected decisions, structure, content, design, media, CTA, QA, failure modes across levels 1–5.',
    why: 'Cases train and regression-test decision quality without running full generation.',
    whenToUse: 'Knowledge QA, planner evaluation, onboarding.',
    whenNotToUse: 'Not a substitute for live E2E — expected outputs are guidelines.',
    goodExample: 'TC-10 dental implantology expects specialization-aware services + booking CTA.',
    badExample: 'Treating expectedStructure as immutable template for any brief.',
    executionHint: 'Compare plan against expectedDecisions/structure as soft assertions.',
    verification: '≥20 cases across levels 1–5 exist and are retrievable by tags.',
    relatedRules: ['IP-001'], tags: ['training', 'core'],
  },
];
